### PR TITLE
macOS: Rewrote version checks to explicitly write the built version to file

### PR DESCRIPTION
**Pull request by kintel**
@t-paul This should perhaps make the CI build for macOS more robust. Still doesn't manage dependencies though.
Update: As the  rabbit hole always goes a bit deeper than we think, this took some more time, but it looks good now.

TODO:
* [x] Rebuild all dependencies on circleci and upload manually to server
* [x] Test by creating `circleci-macos` branch
* [x] If possible, test by upgrading a single package and verify that the CI rebuilds and re-uploads the archive

### CODE REVIEW

**Comment by kintel** [comment]
@t-paul This should be good to go now, in case you want to have a look

**Comment by t-paul** [comment]
Automatically scheduled build [looks good](https://app.circleci.com/jobs/github/openscad/openscad/3818). Unfortunately I can't see a way to configure something like "daily build but only when SCM changed". But maybe we can just do 5 days (like skip Tu/Th) a week which should amount to about 200 of the 500 allowed minutes.

**Comment by kintel** [comment]
Yeah, sounds good!
At some point, we could auto-upload the nightlies, including the SHA, in which case we could check that first.

**Comment by kintel** [comment]
Could you write a ticket (if it doesn't exist). I can try to poke at the server.

**Comment by t-paul** [comment]
Sure, I'll collect the info and try to create a test case with some dummy html file.

**Pull request merged**
