### PR TITLE
Issue warning when overwritting parameters passed to modul #340

### PR DESCRIPTION
**Pull request by MichaelPFrey**
partially addresses #340 

The main challenge is to get the relevant information to where I need them.

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
bildschirmfoto von 2018-12-09 20-57-53

bildschirmfoto von 2018-12-09 21-01-31

bildschirmfoto von 2018-12-09 21-04-02

**Comment by kintel** [comment]
Looking at this again: This could end up being very noisy. Argument shadowing tends to be more of a coding style choice than a real warning.
Perhaps we should have this off by default and let people tune warnings using cmd-line flags or Preferences? ..although that's a fair bit more plumbing to set up..

**Comment by MichaelPFrey** [comment]
I think I am very specif about the warning.

Declaring a parameter just to overwrite it in the module is non-sense:
```
module mytest(a=5){
    a=1;
    echo(a);
}

mytest(2);
```
no matter how I turn it:
```
module mytest(a=5){
    echo(a);
    a=1;
}
```
```
module mytest(a){
    echo(a);
    a=1;
}

mytest(2);
```
```
module mytest(a=1){
    a="test";
    echo(a);
}

mytest();
```

Note that this does not trigger a warning:
```
module mytest(a){
    if(a==2){
        a=1;
        echo(a);
    }
}
mytest(1);
mytest(2);
mytest(3);
```
as the if is its own scope.

Okay, this can be discussed:
```
module mytest(){
    a="test";
    echo(a);
    echo(b);
}

mytest(a=2,b=3);
```
```
WARNING: Module mytest: Parameter a is overwritten, in file openscad, line 2
ECHO: "test"
ECHO: 3
```
but especially when someone assumes that he can use undocumented parameters, the warning that this does not work might be helpful.

Feel free to throw me some test case, maybe I am overlooking a legitimate use case.

But I like the general direction. If someone manages to shadow an assignment in a way, that there is no scenario where the assignment can have any effect, then we should warn.

I would not want to give people the option to turn this on and off. People might want to write libraries. Together with #2630 (and building on top of it https://github.com/MichaelPFrey/openscad/tree/trace), warnings will become are more and more relevant tool. Giving the people options does not help, as libraries are written assuming one or the other.

**Comment by MichaelAtOz** [comment]
I'd also like to point out that we (presuming) all do bad stuff when debugging, overriding a variable in the middle of chunks of code is one such thing. If that happens to be within a repeatedly called nest, think a large `for` in a recursive module, then [warning overload ](https://psychologydictionary.org/warning-overload/)will happen.
I'm wondering if a key code toggle may be appropriate, or some such?

**Comment by MichaelAtOz** [comment]
noting that the preview panel message will/should still show:
warning in gui

**Comment by MichaelPFrey** [comment]
> ```
> function clamp(a) = a > 10 ? 10 : a < 0 ? 0: a;
> 
> module mytest(a=5){
>     a=clamp(a);
>     echo(a);
> }
> 
> mytest(20);
> ```

Okay - I accept that as a legitimate use case.

But at the same time, this does get confusing quickly:
```
function clamp(a) = a > 10 ? 10 : a < 0 ? 0: a;

module mytest(a=5){
    echo(a);  
    a=clamp(a);
    echo(a);
}

mytest(20);
```

```
function clamp(a) = a > 10 ? 10 : a < 0 ? 0: a;

module mytest(a=5){
    echo(a);  
    a=clamp(echo(a) a);
    echo(a);
}

mytest(20);
```
The echo function being executed before the echo modules is what it is, but that we have two different `a` within the same scope, can result in interesting things:
```
function clamp(a) = a > 10 ? 10 : a < 0 ? 0: a;

module mytest(a=5){
    b=min(a,50);
    rotate(min(a,50))cube();
    rotate(b)cube();
    a=clamp(echo(a) a);
}

mytest(45);
```
do be fair, this has nothing to do with modules, as it is a simple scoping issue:
```
function clamp(a) = a > 10 ? 10 : a < 0 ? 0: a;

a=45;
if(true){
    b=min(a,50);
    rotate(min(a,50))cube();
    rotate(b)cube();
    a=clamp(echo(a) a);
}
```

Uff..

**Comment by MichaelPFrey** [comment]
Regarding:

> [warning overload ](https://psychologydictionary.org/warning-overload/)

#2630 should help in that regard.

**Comment by MichaelAtOz** [comment]
> do be fair, this has nothing to do with modules, as it is a simple scoping issue:

That can't be fixed until we 'fix' the -D cmdline problem that causes it.

**Comment by kintel** [comment]
Cool, let's give this a shot :)

**Pull request merged**
