### PR TITLE
shrink margin on demand

### PR DESCRIPTION
**Pull request by jasleenkaur**
This will shrink the margin when Line numbers get disabled.

### CODE REVIEW

**Comment by t-paul** [comment]
Did you check the case @kintel mentioned in his comment https://github.com/openscad/openscad/pull/1612#issuecomment-204749726?

**Comment by kintel** [comment]
On my build, the margin reappears if you type anything into the editor.

**Comment by jasleenkaur** [comment]
@t-paul  I noticed the error indicator overrides the line number ; @kintel  I will check it.

**Comment by jasleenkaur** [comment]
Solved both issues: margin re-appears and overriding markers with line numbers.  :)

**Pull request merged**
