### PR TITLE
inputdriver 5: expose rotate2 via dbus 

### PR DESCRIPTION
**Pull request by MichaelPFrey**
this is building on #2280 (which are the first two commits in this pull request)

Naming it rotate2 is not ideal, but I am unable to come up with a better one.

The name rotate2 comes from the method of the same name that was unused in qglview.

Naming it relative rotate would be confusing with the relative flag of the normal rotate function.

On the other-hand: Rotate2 could be confused with RotateTo which is not ideal either.

### CODE REVIEW

**Comment by t-paul** [comment]
As it's still all experimental, I guess we are still able to change things (a.k.a. not-yet-stable-interface). So maybe we can introduce some more logical names in the interface, regardless of what's used internally.

**Comment by MichaelPFrey** [comment]
I am open to suggestions. Hhmm... the description of rotate2 is
>     // This vector describes the rotation.
>     // The direction of the vector is the angle around which to rotate, and
>     // the length of the vector is the angle by which to rotate
RotateByVector ?

**Comment by kintel** [comment]
Using the length of the vector an an angle is a bit odd. Any particular reason for this?
I would try to make it more explicit.

**Comment by MichaelPFrey** [comment]
You are asking a good question. The rotate2 method in qglview is currently actually unused, so... no idea where this method was coming from and what the intention of it was. The comment is also directly lifted from there.
Using it on a joystick feels like a natural control.

Note that the current rotate function even when set to "relative" is kind of awkward.
To explain what I mean: open the candleStand example (any version of openSCAD - it does not need to be from this feature branch), (candle holders looking up) and rotate it around its axis.
Then turn it upside down (candle holder looking down) and turn it around its axis. The rotation is inverted.
There is no issue with that as long as I use the mouse to rotate the object, but my intuition blocks when I use a 3D mice or gamepad and axis get inverted for no apparent reason.

**Pull request merged**
