### PR TITLE
Origin/emscriptenation

### PR DESCRIPTION
**Pull request by mattminuti**
(First pull request, apologies if I'm doing it wrong!)
Working on getting openscad to build via emscripten. Instructions in doc/build-emscripten.txt.
emcc-build-dependencies.sh does allow for building most of the dependencies, but isn't done yet.
CGAL's not seeing boost quite right, but it shouldn't be an issue since we'll link it all in the end when we build openscad proper, plus I think this might be the preferred way to do it in emscripten, since shared libs aren't really doable in JS. The extra files at tests/CGAL_\* are slight modifications of the equivalents found in CGAL 4.4, to show cmake how to run the tests (with nodejs).

Dependencies to finish:
- [ ] glib2
- [ ] gettext
- [ ] fontconfig
- [ ] harfbuzz
- [ ] Qt?

Would be nice:
- [ ] Unit tests

### CODE REVIEW

**Comment by mattminuti** [comment]
Almost forgot - this assumes that you've already set the emscripten environment variables as normal, by running `source emsdk_set_env.sh` in the emsdk root.

**Comment by kintel** [comment]
Thanks for the pull request! As this is work in progress, and you don't actually touch any existing source files, it's safe to keep this request open for a bit. Any subsequent commits to your branch will automatically be added to the pull request.
I'd say we keep this open until either a working toolchain is established, or more people get involved, in which case we should continue development in an official branch or master.

Some suggestions/questions:
* Keep a TODO list with checkboxes for remaining tasks needed for completion of the project associated with the pull request, see e.g. https://github.com/openscad/openscad/pull/834
* What is the purpose of CGAL_*.cmake ?
* Adding a text-file documenting the emscripten build process would be helpful, e.g. in doc/

**Comment by t-paul** [comment]
There was some discussion of making ```text()``` compile-time optional. This would make fontconfig, freetype and harfbuzz optional.

I'm not sure Qt is needed. The GUI will be different anyway and the core does not depend on Qt at all (see the test suite that compiles without Qt).

**Comment by kintel** [comment]
I agree that Qt should be kept out of this.
We also have some deep OpenGL dependencies which need sorting out.
Compile-time switch for text() could make sense.

**Comment by mattminuti** [comment]
I've added some basic documentation on how to attempt a build with emscripten. I think it's accurate, but I haven't yet built on a different machine.

Compile-time switch for text() does make sense, but text() is such a nice feature that I'd still like to get it working! :)

Strangely, building OpenCSG didn't give me many problems. Emscripten has nearly-full support for OpenGL ES 2.0, and anything WebGL. There's emulation for GL1.x, too. I don't plan on actually using any of it, but I imagine it could be useful to have it.

**Comment by kintel** [comment]
@mattminuti Out of curiosity: If you don't plan to use any of the rendering code, how do you plan to do rendering?

**Comment by mattminuti** [comment]
Three.js, ideally.

**Comment by kintel** [comment]
@mattminuti In that case, we probably need to create clean interfaces between the core OpenSCAD code and the rendering - otherwise you'll end up chasing a moving target, as this code will likely be refactored quite a bit. See the following suggested GSoC project: https://github.com/openscad/openscad/wiki/Project%3A-Improve-OpenGL-rendering

**Comment by mmiscool** [comment]
Anything happening with this? Is there a WASM build of openSCAD working some place?

**Comment by MichaelAtOz** [comment]
Double posting does not change the [answer](https://github.com/openscad/openscad/issues/466#issuecomment-739532900).

**Comment by mmiscool** [comment]
I am willing to pay a $400 bounty to get a functioning wasm build of openSCAD with the following conditions. 

- Documentation of javascript API to push and pull file data from the webassembly virtual file system. 
- Capability to execute all the command line operations that would be applicable in a headless no GUI environment and return what normally would be the result executing in a command line terminal.

**Comment by mmiscool** [comment]
Bump. Bounty is now $500

**Comment by DSchroer** [comment]
For those working on the porting of OpenSCAD to WASM. I decided to take on the bounty mentioned above. I have a working version of it now that you can find here: https://github.com/DSchroer/openscad-wasm

All of the dependencies for the current version of OpenSCAD are good but with NULLGL not working I am only able to build the 2019 version. There is still lots to test and fix but its a great starting point as it can reliably compile everything.

**Comment by t-paul** [comment]
@DSchroer this is great news. What's the issues with NULLGL? That's hopefully not too difficult to fix.

@mmiscool As far as I can see, the bounty you mentioned is not posted on Bountysource. Are you still up for that, and would it be ok to go via Bountysource? I can create a separate feature request ticket for that.

**Comment by mmiscool** [comment]
@t-paul I have already been talking with @DSchroer and am in the process of testing and validating build. 

No need to create a bounty on another website.

**Comment by t-paul** [comment]
Confirmed working here. Changed example to `$fn = 100; cylinder(20, 5, 10);` which was generated successfully.

**Comment by DSchroer** [comment]
@t-paul Thanks for testing it out. I just pushed a fix for the main branch checkout issues. Also adding a section in the README about the SharedArrayBuffer error and how to fix it. Finally I hope you don't mind but I added your example to the test cases. Feel free to PR some more if you want as well. 

Regarding the NULLGL error I don't think it would be too hard. Essentially there are some `#ifdefs` in the code base that get triggered to remove OpenGL dependencies when its enabled. It was fixed in 2019 but then broke sometime later. Probably just a bit of tinkering should fix that up. It's a known issue in the current CMake configuration.

**Comment by t-paul** [comment]
Closing, superseded by https://github.com/DSchroer/openscad-wasm

**Pull request closed without merging**
