### PR TITLE
Update working of No option in reload

### PR DESCRIPTION
**Pull request by RomitKumar**
The reload confirmation dialog box counter-intuitively turns off automatic reload on choosing No option. The pr removes this behavior and No option simply does not reload the file.

### CODE REVIEW

**Comment by RomitKumar** [comment]
Are you suggesting to add different preference setting(checkbox) for auto-reload and manual reload? The auto-reload or manual reload works only if the corresponding checkbox is ticked.
My intended functionality is that "Never" option simply does the work of "No"  while "No" doesn't do anything.

**Comment by kintel** [comment]
I'm not sure what the best solution is. Right now it's a bit confusing since "Never" won't work for manual reloads. Getting GUI like this right is tricky.

**Comment by RomitKumar** [comment]
"Never" should only stop auto-reload. It can be strange when user triggers manual reload, and the file is not reloaded because of some preference setting set sometime in the past. I guess any manual reload should ideally reload the file irrespective of preference setting.
Yeah, the name "Never" can be confusing. I guess we can replace that with "No and stop auto-reload" or something more concise.

**Comment by MichaelAtOz** [comment]
OP "counter-intuitively turns off automatic reload on choosing No option."
So how about just not doing that. Leave it to the user to sort out preferences.
Mostly auto-reload is used with external editors, it would be rare to want to change that too often.
or
Maybe "Disable auto-reload" instead of "Never". But I prefer the do nothing option.

**Pull request merged**
