### PR TITLE
Lexertl integration - upgrade syntax coloring

### LINKED ISSUE #1172: Syntax highlighting: # affects the whole line
This is likely due to QScintilla's C++ parser tagging the whole line as a preprocessor directive.
The solution is probably to write our own parser component for QScintilla.

screen shot 2015-01-21 at 19 13 38 pm
## 

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/7943701-syntax-highlighting-affects-the-whole-line?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ChrisCoxArt**
Integrate lexertl lexer (header only code) to give us a custom lexer for syntax coloring, based on incomplete attempt in https://github.com/openscad/openscad/tree/lexertl/src with updated code from https://github.com/BenHanson/lexertl14
Fixes #1172

Add new categories for syntax colors, more options for custom syntax keywords and colors, and 3 new color schemes based loosely on colors in other editors.

### CODE REVIEW

**Comment by ChrisCoxArt** [comment]
Filed the issues CodeQL found at https://github.com/BenHanson/lexertl14/issues/7

**Comment by t-paul** [comment]
Nice! Don't worry about the merge conflict, I'm having a look locally and have the conflict solved already.

**Comment by t-paul** [comment]
I've updated a couple of the rules, all entries from the cheatsheet now look like that:
```
// line comment

/*
 * block
 * comment
*/


// Syntax
var1 = 3;
var2 = true ? 1 : 0;
func = function (x) x + x
module mod() { }
function func() { }
include <>
use <>


// Constants
c1 = true;
c2 = false;
c3 = undef;
c2 = PI;


// Operators
a = 1 + 2;
b = 1 - 2;
c = 1 * 2;
d = 1 / 2;
e = 1 % 2;
f = 1 ^ 2;
g = 1 < 2;
h = 1 <= 2;
i = 1 == 2;
j = 1 != 2;
k = 1 >= 2;
l = 1 > 2;
m = 1 && 2;
n = 1 || 2;
o = !1;


// Special variables
$fa = 2;
$fs = 0.5;
$fn = 20;
$t = 1;
$vpr = [0, 0, 0];
$vpt = [0, 0, 0];
$vpd = 10;
$vpf = 20;
$children = 10;
$preview = 1;


// Modifier characters
* cube();
! cube();
# cube();
% cube();


// 2D
circle();
square();
polygon();
text();
import();
projection();


// 3D
sphere();
cube();
cylinder();
polyhedron();
linear_extrude();
rotate_extrude();
surface();
roof();

// Transformations
translate();
rotate();
scale();
resize();
mirror();
multmatrix();
color();
offset();
hull();
minkowski();


// Lists
list = [1, 2, 4];
var = list[2];
var = list.z;


// Boolean operations
union()
difference()
intersection()


// List Comprehensions
generate1 = [ for (i = range|list) i ];
generate2 = [ for (init;condition;next) i ];
flatten = [ each i ];
conditions1 = [ for (i = …) if (condition(i)) i ];
conditions2 = [ for (i = …) if (condition(i)) x else y ];
assignments = [ for (i = …) let (assignments) a ];


// Flow Control
for (i = [start:end]) { }
for (i = [start:step:end]) { }
for (i = [1,2,4]) { }
for (i = 1, j = 2) { }
(i = [start:end]) { }
intersection_for(i = [start:step:end]) { }
intersection_for(i = [1,2,4]) { }
if (true) { }
let (i = false) { }


// Type test functions
is_undef();
is_bool();
is_num();
is_string();
is_list();
is_function();


// Other
echo();
render(convexity);
children([idx]);
assert(condition, message);
child(); // deprecated
assign() { } // deprecated


// Functions
f1 = concat();
f2 = lookup();
f3 = str();
f4 = chr();
f5 = ord();
f6 = search();
f7 = version();
f8 = version_num();
f9 = parent_module(idx);


// Mathematical
m1 = abs();
m2 = sign();
m3 = sin();
m4 = cos();
m5 = tan();
m6 = acos();
m7 = asin();
m8 = atan();
m9 = atan2();
m10 = floor();
m11 = round();
m12 = ceil();
m13 = ln();
m14 = len();
m15 = let();
m16 = log();
m17 = pow();
m18 = sqrt();
m19 = exp();
m20 = rands();
m21 = min();
m22 = max();
m23 = norm();
m24 = cross();
```

**Comment by ChrisCoxArt** [comment]
Thanks.  There were several of the keywords that were debatable for placement.  I tried to balance between the old branch and current code, but wasn't sure about some.
Darnit, why didn't I find that cheetsheet earlier...  (I made my own condensed version for testing)

**Comment by t-paul** [comment]
Some cases to look at (later :smile:)
grafik

**Comment by ChrisCoxArt** [comment]
The good news is that we now have LOTS of flexibility for keywords and groupings.
The bad news is that everyone will have a differing opinion about groups, and colors.

**Comment by MichaelAtOz** [comment]
I don't suppose this is documented anywhere other than going thru the source changes?? 
Particularly the custom bit.

**Comment by ChrisCoxArt** [comment]
Well, you can read the sample highlighting styles. The VisualStudio style defines some custom keywords.
But yes, the most complete documentation would be the source code.

**Pull request merged**
