### PR TITLE
Bump manifold to latest version (v2.2.1-3-gb6eea01).

### PR DESCRIPTION
**Pull request by t-paul**

### CODE REVIEW

**Comment by pca006132** [comment]
is the failure related to how manifold reorders boolean operands?

**Comment by t-paul** [comment]
@pca006132 I would assume so, yes. But we already have a feature that sorts faces and vertices at export to produce a deterministic output, it's just not enabled by default for STL.

I'm planning of just removing the experimental flag from that feature so we always get the sorted STL output. I think that's nothing Manifold should take care of, at least not always as there's probably a good number of use cases where the sorting order does not matter and impacting those performance wise seems not ideal.

**Comment by pca006132** [comment]
FYI: discussion about deterministic results in https://github.com/elalish/manifold/issues/545

**Comment by pca006132** [comment]
In particular, there should be no guarantee in how we triangulate the result, other than the triangulation should be valid.
I guess this may make testing harder as you can no longer compare the edges of the mesh.

**Comment by pca006132** [comment]
Wondering what is the blocker for this PR? Is it some issue in manifold?

**Comment by pca006132** [comment]
the triangulator refactor is merged, maybe we can bump the version again and get this merged?

**Comment by pca006132** [comment]
For the manifold-stlexport_stl-export it is expected due to changes in the triangulation. I have no idea about those png failures, will investigate them later.

**Comment by pca006132** [comment]
I am unable to reproduce the png error when using the latest master with updated manifold submodule. Maybe you can try to update this and see if it still fails? I think there are a few patches related to OpenGL recently.

**Comment by t-paul** [comment]
@pca006132 thanks a lot, and I'm sorry for not having time to really look into the issues yet. I'm assuming the test case issues are on OpenSCAD side. @kintel is also currently fixing some inconsitencies in the test suite that have crept in via all the new feature.

**Comment by pca006132** [comment]
Sure, I saw the PR by kintel. It looks interesting that the png tests still failed after updating to the master. Maybe I should try if I can reproduce the issue with docker.

**Comment by pca006132** [comment]
I tried merging with master (after @kintel's recent PRs), and I only get the following failures now:
```
	1273 - cgalstlcgalpngtest_bad-stl-tardis (Failed)
	1292 - cgalbinstlcgalpngtest_bad-stl-tardis (Failed)
```

both got the error `ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron.`. And if I understand the names correctly it seems that the test is using bad input files?

**Comment by kintel** [comment]
I feel like think the tartis issue is a completely different bug. If you look at the test report:
```
/home/runner/work/openscad/openscad/b/openscad /home/runner/work/openscad/openscad/tests/data/scad/misc/bad-stl-tardis.scad -o /home/runner/work/openscad/openscad/b/tests/output/cgalstlcgalpngtest/bad-stl-tardis.scad.stl --enable=fast-csg --render=cgal --export-format asciistl
Converted to Nef polyhedron
Geometries in cache: 2
Geometry cache size in bytes: 523888
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.273
Top level object is a 3D object:
   Simple:     yes
   Vertices:      810
   Halfedges:    2880
   Edges:        1440
   Halffacets:   1262
   Facets:        631
   Volumes:         2
```


-> Why is it using CGAL for the geometry when manifold is enabled?

**Comment by pca006132** [comment]
Not sure about the internals, I think it currently just loads the stl as a CGAL object, and lazily convert it into a manifold object when needed (which is not needed in the test because there is no CSG operations).

**Comment by kintel** [comment]
I did some digging: Surprisingly, the two tests pass _without_ `--enable=predictible-output`, and fail _with_ `--enable=predictible-output`. Since this PR makes the predictible output default, it fails.

@t-paul Any ideas?

**Comment by pca006132** [comment]
Can we merge with master to see if the CI can pass (except the known failures that are unrelated to manifold). This manifold update should fix #4679, #4766, #4769 which I think are the major issues people get when using manifold.

**Comment by t-paul** [comment]
It was already rebased, but I've dropped the predictible-output for now as it seems we may not depend on it.

**Comment by t-paul** [comment]
It's green, so lets go :snail: :grin:. Thank you @pca006132!

**Comment by kintel** [comment]
Since this seems to be causing crashes on Windows, I wonder if we should revert this PR until we can figure that out.

**Comment by t-paul** [comment]
I'll have a look, maybe just the Manifold update instead off full revert. That way we could rule out the other changes.

**Comment by kintel** [comment]
Yeah, rolling back Manifold to some safe version would be good for now, as it seems to be tricky to reproduce the current issue.

**Comment by pca006132** [comment]
I am thinking if the crashes are actually caused by manifold. The examples are pretty simple, with no tricky 2D geometry which may stress our new triangulator. No one managed to reproduce the crash with msys2/macos/linux, or a clean build with MXE. The crash is also very weird as we normally won't segfault directly, we usually just throw an index out of range exception. And I tried using debug build and enabled address sanitizer for manifold on Windows, which we found no memory corruption, indicating that it is quite unlikely to have such severe bug for simple model like the `logo.scad`.

This kinds of make me wonder if this is something one-off like the binary getting corrupted by random-hardware-fault or some issue with MXE. The first hypothesis can be ruled out if we managed to reproduce the crash with a clean MXE build, because the probability with 2 consecutive corruption which causes similar error is rare. For the second one we can try to reproduce it with something other than MXE...

**Pull request merged**
