### PR TITLE
 #1647 remove workarounds for older versions of boost

### PR DESCRIPTION
**Pull request by DrCodeWizzard**
another config

another one

### CODE REVIEW

**Comment by DrCodeWizzard** [comment]
any ideas why these tests are failing? On my local linux box they all pass.

**Comment by t-paul** [comment]
Xvfb did not start, seems to happen now and then lately. I've re-triggered the Travis run.

**Comment by DrCodeWizzard** [comment]
How do i re-trigger travis for future reference?

**Comment by t-paul** [comment]
There's a restart button on the top right, but I don't know if this is tied to some access control. I suspect it's restricted to repository team members.

**Comment by DrCodeWizzard** [comment]
how do i get this merged in?

**Comment by kintel** [comment]
Could you write a sentence about what you did, and what's remaining (e.g. required boost version)?
-> then I can review it and merge.

**Comment by DrCodeWizzard** [comment]
I have removed support for boost version earlier than 1.46. I have removed all calls to boosty::* methods from the project which have direct support in boost version 1.46 and greater. I have not moved minimum boost support requirements to 1.48 as that requires modifying travis configuration extensively. 

I have removed from boosty.h definitions of all methods which were required to support boost versions prior to boost v1.46

**Pull request merged**
