### PR TITLE
Update manifold

### PR DESCRIPTION
**Pull request by cjmayo**
Please check carefully, I've just looked at the manifold code for how things have changed.

### CODE REVIEW

**Comment by kintel** [comment]
Manifold changed a bit. I'm planning to look into this soon, hopefully next week.

**Comment by t-paul** [comment]
Manifold 3.0: https://github.com/elalish/manifold/pull/1024

**Comment by pca006132** [comment]
Wow, this is simpler than I thought!

**Comment by kintel** [comment]
Enabling TBB only in experimental mode sounds wrong - that's probably an oversight by me when moving Manifold out of experimental.

**Comment by kintel** [comment]
I would suggest: Remove ENABLE_TBB, remove the MANIFOLD_PAR check, and always enable MANIFOLD_PAR (except for Emscripten I guess). That should simplify the CMake setup a bit.

If we need to be able to build a non-parallel Manifold in the future, we can bring this back with a more concrete use-case in mind.

**Comment by kintel** [comment]
@cjmayo Feel free to take on the above changes, but I'm fine to merge this and deal with the TBB/experimental stuff separately.

**Review by kintel — APPROVED** [review]

**Pull request merged**
