### PR TITLE
Inputdriver5 automatically generate the actions for the button comboxes

### PR DESCRIPTION
**Pull request by MichaelPFrey**
I do not want to maintain the action list, so I would like to automate it:
bildschirmfoto von 2018-01-09 05-09-24
I do not want to maintain the translation of the action list, so I would just reuse the translation of the menu:
bildschirmfoto von 2018-01-09 05-08-58

Please merge  #2254 first - I will think about how to integrate it here.
Now, #2255 becomes more important as the action list is generated dynamically.
The code is currently a bodge job,  I am locking into improve it.

### CODE REVIEW

**Comment by MichaelAtOz** [comment]
Are you going to manually handle left/right/middle clicks or something tricky?

**Comment by MichaelPFrey** [comment]
@MichaelAtOz this for  #2130 which is in turn for #1433
In short: This is work on the GUI for the 3D-Mice/Joystick driver.

But your question is valid: I better change the title of this pull request and I should add "use more meaning full icons" to my to do list.

**Comment by MichaelPFrey** [comment]
So, now I am happy with the look and coding. Feel free to merge/squash this pull request.

bildschirmfoto von 2018-01-30 04-40-31

**Comment by t-paul** [comment]
Awesome, that looks very nice.

**Pull request merged**
