### PR TITLE
Proposal for a decision of issue #1064

### PR DESCRIPTION
**Pull request by SlesarevIlya**
Hello, I made a design option for launchscreen, adding a checkbox with a choice of startup options.
Please view and comment it.

Accordingly, in an embodiment of the buttons it is possible to open the double-click the file.
openscad1
In an embodiment without buttons the file is opened with a single click.
openscad2

### CODE REVIEW

**Comment by kintel** [comment]
Thanks for your pull request.

I think that for this issue, we're looking to make the UI more user friendly. I think that adding more checkboxes is a bit of a step in the wrong direction.
Good UI design isn't trivial, so such things tends to take a bit of time to figure out properly..

**Comment by Pointedstick** [comment]
Indeed. More checkboxes is generally the wrong answer.

**Comment by SlesarevIlya** [comment]
Okay, i understand you, thanks.

**Comment by donbright** [comment]
you know, i'm not sure i really understand this. 

is there more description of what "one click the file" means? thanks

**Comment by MichaelAtOz** [comment]
> is there more description of what "one click the file" means? thanks

Single click on a leaf of the recent file list or the example tree, opens that file, v's double clicking it as now.

(I'm ambivalent on the subject)

**Comment by t-paul** [comment]
It's about issue #1064. I don't have any problem with the current layout, but also don't see an issue with changing it a bit.
Although what's been discussed so far (here and in #1064) does not feel like an improvement to me, just different.

**Comment by kintel** [comment]
Closing this as this doesn't improve usability. I'm still interested in an improvement - make it cleaner, more intuitive, perhaps fewer buttons.

**Comment by donbright** [comment]
oh my,  i missed the title. ok. thanks for explaining.

it seems like if you took this and got rid of the check box, it would basically be like @atartanian 's suggestion on #1064 which seems to make sense to me.

**Comment by atartanian** [comment]
+1 for just making the checked behavior the only way it works. there is just no need for those "open" buttons, the filenames can provide direct access, which is more intuitive and reduces the complexity of the UI

**Comment by t-paul** [comment]
I'm against using a way to select the files that's going against the normal UI behavior, e.g. using single clicks where the default is double click.

**Comment by MichaelAtOz** [comment]
> I'm against using a way to select the files that's going against the normal UI behavior, e.g. using single clicks where the default is double click.

+1. That is web browsing UI, not application UI.

I'm not suggesting this, but to get consistent UI with a single click would need to change the file/example names to links like those below, with the underline when hovered behaviour (example from Control-panel/Power-options);
link ui

**Comment by t-paul** [comment]
That type of links is fine in general, we have it already for the warnings. And we hopefully get it sometimes in the log window pointing to errors.

In case of list boxes or the tree for the examples, that's not easy to solve though. I don't see how to convert this to web style without losing the start dialog feel. It would make sense if we had some "start" document like some IDEs do, but right now that's not really possible with the single file text editor.

**Comment by donbright** [comment]
Even if this particular issue (splash screen) is kept as "desktop ui" style for now, eventually in the future some kid will change it to web style. like how mac OSX changed the way mouse scrolls because they know in the future everything will be touchscreen.... so too in the future everything will be fingers single-tapping on icons.  

Web is future of ui. qt is moving to qml which is basically a flavor of javascript. all the kids are growing up are learning to code ui in javascript. touching with fingers, swiping, and all that. 

OpenSCAD's own file/examples/ menu is one click, ubuntu dash is one click, ubuntu side bar is one click, Chrome startup "dialer" is one click. Android is one click, iOS is one click. Desktop PC market is dying, phone market is rising.  most common "open file" operation people do these days is people opening a podcast episode or a netflix video or a tweet or an instagram post or a youtube video. They are opening a "document", it just so happens to be an audio or video document. All of this is single click. We are the last desktop generation. When we fade away, desktop ui will go with us. We will keep the flame a live for a while but the new generations have their own ideas. 

https://blog.codinghorror.com/double-click-must-die/

**Comment by MichaelAtOz** [comment]
Don, where are you making these comments? It doesn't show under the 'view it on GitHub' link.

 

  _____

**Comment by MichaelAtOz** [comment]
I think the point should be that things like Qt & operating system APIs should translate program calls to match target UI. e.g. a file/open dialog, and make the UI suit the locale. The worst outcome is an application which does not match the behaviour of the platform it is running on.

**Pull request closed without merging**
