### PR TITLE
redo find-replace highlights and word count fix MCAD

### PR DESCRIPTION
**Pull request by kipbits**
redo find-replace highlights and word count fix MCAD

### CODE REVIEW

**Comment by kipbits** [comment]
continued from #1922 

still the problem with MCAD I had the same error while cloning:
screen shot 2017-02-11 at 8 24 26 pm
screen shot 2017-02-11 at 8 31 40 pm

**Comment by kipbits** [comment]
Ok trying again using git clone git://github.com/openscad/openscad.git from readme

**Comment by kintel** [comment]
That's weird - that commit totally exists: https://github.com/openscad/MCAD/commit/85794e4b4f2294a1b445a4d928866bedd5cc64ec

Are you perhaps pulling MCAD from another location?

**Comment by kipbits** [comment]
ok i tried in the terminal:
```
frankenstein:openscadGit kipplebits$ git clone git://github.com/openscad/openscad.git
Cloning into 'openscad'...
remote: Counting objects: 45355, done.
remote: Compressing objects: 100% (96/96), done.
remote: Total 45355 (delta 43), reused 0 (delta 0), pack-reused 45258
Receiving objects: 100% (45355/45355), 45.16 MiB | 65.00 KiB/s, done.
Resolving deltas: 100% (31600/31600), done.
Checking connectivity... done.
frankenstein:openscadGit kipplebits$ git submodule update --init
fatal: Not a git repository (or any of the parent directories): .git
frankenstein:openscadGit kipplebits$
```

MCAD is still empty

**Comment by kipbits** [comment]
aHA! I will try downloading  openscad/MCAD i have been using SolidCode/MCAD

**Comment by kipbits** [comment]
or wait before i change anything else my current github desktop looks like this
screen shot 2017-02-11 at 8 46 10 pm

should i commit this change?

**Comment by kipbits** [comment]
I haven't made any changes to MCAD yet

**Comment by kintel** [comment]
You should run `git submodule update --init` from inside the OpenSCAD folder.
I think manually overwriting MCAD with your own clone is the root of your problems.

**Comment by kipbits** [comment]
That seamed to do the trick! MCAD is now full!

**Comment by kintel** [comment]
Good to have that sorted. I guess you should just kill this branch and recommit to get rid of that one remaining MCAD commit

**Comment by kipbits** [comment]
ok give me a bit. I'm not used to git in the terminal

**Comment by kipbits** [comment]
did that do it?

**Comment by kipbits** [comment]
whoops! fixed the wrong PR. well it is fixed here. hope that works for everybody?

**Comment by kipbits** [comment]
tried to fix the old pr, but ran into some complications probably best to use this PR

**Comment by kipbits** [comment]
looks like i clicked the wrong button. lets see if i can revert my last commit...

**Comment by kipbits** [comment]
continue on #1947

**Pull request closed without merging**
