### PR TITLE
DBus interface debugged

### PR DESCRIPTION
**Pull request by MichaelPFrey**
This rework is based on the car example from QT.

I have a simple implementation of the other side of the interface.
I will clean it up and then upload to github as a reference implementation.

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
https://github.com/MichaelPFrey/openscad-dbus-reference

Next step is making something useful using this Interface and a BBC Microbit.

**Comment by MichaelAtOz** [comment]
So this is a IPC mechanism to drive the OpenSCAD UI?

**Comment by MichaelPFrey** [comment]
Yes, D-Bus is a inter-process communication mechanism that can be used to drive the OpenSCAD UI.
D-Bus is linux only.

I have to say: This is an awesome way to write a custom driver.
https://github.com/MichaelPFrey/openscad-dbus-microbit
(the BBC microbit has an accelerometer, an electronic compass and two buttons)

**Comment by t-paul** [comment]
Awesome, I just got a Micro:bit too...

**Pull request merged**
