### PR TITLE
Improve Emacs mode

### PR DESCRIPTION
**Pull request by minad**
A set of small fixes to the Emacs package, which brings it up to current standards. See the commit messages for the reasoning of each commit.

### CODE REVIEW

**Comment by minad** [comment]
In case you are looking for a maintainer of the Emacs package, I offer to help out. I already maintain a number of packages on [GNU ELPA](http://elpa.gnu.org/packages/) and [MELPA](https://melpa.org/#/?q=minad&sort=downloads&asc=false).

**Comment by thehans** [comment]
I'm not an Emacs user, so I have no strong opinion here.  
Nor do I have much ability to evaluate the utility or validity of such changes (though to my untrained eye they do at least seem well thought out).

@minad As a maintainer of other packages, would it make sense to split Emacs support into its own official git repo?

If that is the case, then @teepee what would you think of creating a repo e.g. `openscad/emacs-scad-mode` (or whatever name is desirable) and granting write permission for minad?

**Comment by t-paul** [comment]
Yes, sounds good to me, if a separate repo would be useful, I can create that.

**Comment by minad** [comment]
Yes, a separate repository would be useful. Then I can inform the package registries (MELPA, NonGNU ELPA) to point to the new location. A small separate repository is preferable for the registries in contrast to a monorepo, see for example  https://github.com/melpa/melpa/issues/8172.

**Comment by thehans** [comment]
OK, sounds good.  @minad Did you have any preference for the repo name, or is my suggestion of `emacs-scad-mode` fine?

**Comment by minad** [comment]
@thehans emacs-scad-mode is fine.

**Comment by t-paul** [comment]
Created as [`emacs-scad-mode`](https://github.com/openscad/emacs-scad-mode) and invitation sent, we can update the name if anything else sounds better :grinning:.

**Comment by t-paul** [comment]
Neat, 2 comments with the age ticking as same value in seconds :timer_clock:.

**Comment by minad** [comment]
Thanks! I imported scad-mode.el in https://github.com/openscad/emacs-scad-mode/commit/e64d93cdb2f998ee1ad8e5759aea357f8b133f4c and pushed these commits there.

**Comment by minad** [comment]
@thehans I suggest to remove contrib/scad-mode.el as soon as https://github.com/melpa/melpa/pull/8266 is merged to avoid potential confusion regarding the source location of the Emacs package.

**Comment by t-paul** [comment]
Thanks, subscribed to that PR.

**Comment by t-paul** [comment]
Oh, already merged, that was quick. I'll create a PR to remove the file here, but I guess we'll give it a couple of days before actually merging it.

**Pull request closed without merging**
