### PR TITLE
Set Windows Registry Defaulticon For Document Icon

### PR DESCRIPTION
**Pull request by TDeagan**
Response to #1082 Update Windows document icon.

* New multi-resolution document icon created based on document icon from Mac OS X. 
* Code added to openscad_win32.rc to insert this icon into openscad.exe.
* Code added to src/openscad.cc cmdline and gui functions to set the Windows Registry key HKEY_CURRENT_USER/Software/Classes/OpenSCAD_File/DefaultIcon/Default to the value of the index of the icon added to openscad.exe (1)

Notes from issue #1082:
In the cmdline and gui functions in openscad.cc I added:
```
#ifdef Q_OS_WIN
    QSettings reg_setting(QLatin1String("HKEY_CURRENT_USER"), QSettings::NativeFormat);
    QString appPath = QDir::toNativeSeparators(app.applicationFilePath() + QLatin1String(",1"));
    reg_setting.setValue(QLatin1String("Software/Classes/OpenSCAD_File/DefaultIcon/Default"),QVariant(appPath));
#endif
```
I tried moving this into PlatformUtils_win.cc and as a separate function in openscad.cc, but I kept running into problems with complaints about private nature of the app object and the way it's a QApplication object in gui and a QCoreApplication object in cmdline and such.  Ultimately, there was a lot less surgery all around to just dupe the block above in gui and cmdline. I'm happy to keep working on that if it provides value in some way.

Notes:
* Changing this registry key only takes effect when:
 * Computer restarts
 * User logs off and logs on again
 * explorer.exe is restarted (which is the relevant part of what's going on in the first two)
* Setting the key in HKEY_CURRENT_USER works, but only for the current user.  Not for 'all users'.  That would require setting in HKEY_LOCAL_MACHINE, and that would take running in admin mode.  Otherwise, it throws a QSettings::AccessError (doesn't break the app, the error is only discernible with a QSettings.status() call.)  Even in admin mode the app pops up a warning modal asking the user if they want to allow changes to the system.  Of course, any user who launches OpenSCAD will reset it for themselves.

### CODE REVIEW

**Comment by t-paul** [comment]
I think we can't do it in the ```cmdline()``` method. This is also used from the test framework which does not link with Qt. See [Travis log](https://travis-ci.org/openscad/openscad/builds/47071682):
```
/home/travis/build/openscad/openscad/src/openscad.cc:46:16: fatal error: QDir: No such file or directory
```
I guess it's fine to set the icon key only when launching the GUI.

**Comment by TDeagan** [comment]
Makes sense. I went back and forth about the relevancy of the doc icons to the cmdline usage. Figured it would be better to get it working and choose not to go there rather than not have it if folks wanted it. 

Would you like me to submit a different pull request with the cmdline section removed or would you like to deal with it in this request?

**Comment by t-paul** [comment]
You can just push the change to your branch that this pull request is based on. Github will automatically add this to the pull request then.

**Comment by TDeagan** [comment]
Removal of the relevant code block has been committed and pushed to the pull request branch (https://github.com/tdeagan/openscad/tree/defaulticon )

**Comment by t-paul** [comment]
Hmm, it's still producing a compile error on Travis...

**Comment by t-paul** [comment]
Ahh, it's complaining about the QDir include at https://github.com/TDeagan/openscad/blob/defaulticon/src/openscad.cc#L46 which is outside the ```#ifdef OPENSCAD_QTGUI```

The is one already at https://github.com/TDeagan/openscad/blob/defaulticon/src/openscad.cc#L560

**Comment by TDeagan** [comment]
Gack!  Sorry, I missed that conditional include at line 560. (https://github.com/TDeagan/openscad/blob/defaulticon/src/openscad.cc#L560)

Will fix and push.

**Comment by TDeagan** [comment]
MechaGack!!  How can these tests fail based on my removal of a redundant include?  So Sorry!!

**Comment by t-paul** [comment]
Those 3 failing test cases is where @kintel is working on, so don't worry about those.

**Comment by kintel** [comment]
Code works for me. I feel the icon could be a bit more clear, but I don't know what Windows users expect from icons (we can change that later).

**Comment by kintel** [comment]
@TDeagan When testing this on Windows 8.1, it looks like the document icons don't work there. Do you know if that version of Windows requires special care?

**Comment by TDeagan** [comment]
Grrrp!! Hmmm.  I have both a win 7 and win 8.1 box that I switch back and
forth to dev on.  I was pretty sure I'd tested/dev'd this on the win8.1,
but maybe not.

I'm pulling that environment up and will test/investigate right now.

--tim

**Comment by TDeagan** [comment]
wierd.  I'm in front of the win 8.1 laptop and even before I get the dev
environment up I can see that the document icons are working as intended on
it for .scad files.  Is there a particular fork that you're testing from
that I can clone and test?

--tim

**Comment by TDeagan** [comment]
I just deleted the registry entry, ran a copy of openscad built from the master branch and it added the defaulticon icon back.  The document icons are showing up. 

NOTE: you do have to reboot/logout to get the icons to display.

**Comment by kintel** [comment]
I tried rebooting. It looks like Windows uses the main application icon instead. Could it be that when I associate a file type with an application, it will override the document icon?

**Comment by TDeagan** [comment]
I just tried associating a .scad file with OpenSCAD (which as it turned out
it was already associated with) and (even after rebooting) I still show the
new doc icon.

If you open regedit, what do you see for the following keys?:

HKEY_CURRENT_USER/Software/Classes/OpenSCAD_File/DefaultIcon/Default

HKEY_CLASSES_ROOT/OpenSCAD_File/DefaultIcon/Default

HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon

The first is the one that the code is setting, the second is the one read
by the system which is derived from the first and third.

--tim

**Comment by kintel** [comment]
* HKEY_CURRENT_USER/Software/Classes/OpenSCAD_File/DefaultIcon/Default
   * C:\Users\IEUser\Desktop\openscad-2015.02.05\openscad.exe,1
* HKEY_CLASSES_ROOT/OpenSCAD_File/DefaultIcon/Default
   * C:\Users\IEUser\Desktop\openscad-2015.02.05\openscad.exe,1
* HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon
   * Not found

**Comment by TDeagan** [comment]
Fraggle Rock!  That's exactly what the values should be based on the goal of the code (those values match mine exactly.  Unless somehow, the document icon isn't getting compiled into the exe in the version you're using.  Which is unlikely, my build off a recently pulled master found it fine.

You don' see the scad text at the bottom at any resolution? (small, medium or large icons?)

I'll start digging for interwebs indications that this is a win 8.1 problem in general.

**Comment by kintel** [comment]
Btw., I used the latest development snapshop (32-bit zip) for this test.

**Comment by kintel** [comment]
Here's a screenshot. The icon size I choose doesn't really influence the OpenSCAD icon:

screen shot 2015-02-06 at 00 38 43 am

**Comment by t-paul** [comment]
Maybe it's a problem with the MXE build system? How to verify the icon is actually in the .exe?

**Comment by TDeagan** [comment]
I'm using Visual Studio to check the icons stored in the exe.  I'll look
around for a lightweight way to do so.  I haven't tried them but I see a
couple:
http://www.codeproject.com/Articles/32617/Extracting-Icons-from-EXE-DLL-and-Icon-Manipulatio
http://www.neuber.com/free/iconview/


  I'm building master on my windows 8.1 64 bit system, I'll try going the
same route you are.  Are you working on a 32 bit machine?

**Comment by TDeagan** [comment]
I have the same problem you report when using the 32 bit zip.  Investigating.

**Comment by TDeagan** [comment]
Frak,  I now see the document icon.  
image

I can NOT imagine how opening the exe in Visual Studio made the icon work, but that's the extra step I took.  I'll try the sequence again.

**Comment by TDeagan** [comment]
te registry entry.
2. reboot
3. No document icon 
image
4. run 32 bit (Zip delivered) OpenSCAD.
5. No Document icon in explorer (as expected prior to reboot)
6. Document icon IS visible in Save As dialog for app (notepad++) 
image
7.reboot
8. document Icon shows in explorer
image

**Comment by TDeagan** [comment]
So, I'm stuck.  I can't replicate the problem on my 64-bit win 8.1 box.  I can try downloading a win8.1 32-bit iso and setting up a virtual machine to test on.  That will take a little bit but I should have it up and running by this afternoon.

**Comment by TDeagan** [comment]
urp.  make that tonight.   I'm at work, but using my (personal) laptop off my phone's hotspot.  They've disabled USB drives, so I have no way to download the ISO on my work machine and get it to the laptop.  I'll have to wait until I'm on my home network tonight.  I'll see if I can remote to my home box, make it downoad the iso while I'm at work and use that win7 box to VM a win8.1 iso.

**Comment by TDeagan** [comment]
shazbot!  the machine I'm remoting to is giving me the dreaded "vt-x/amd-v hardware acceleration is not available" from virtualbox.  At best this means I need to enable virtualization in the BIOS, which I can't do remotely.  So it will be late this evening(US Central time) before I'm in front of that machine and can build the win 8.1 32-bite VM (unless I can think of some way to get a 2.8GB file off my work desktop onto my personal laptop (not using a network, USB or DVD, security is a b#tch.)

**Comment by MichaelAtOz** [comment]
> unless I can think of some way to get a 2.8GB file off my work desktop onto my personal laptop (not using a network, USB or DVD, security is a b#tch

Serial port? ;)

**Comment by MichaelAtOz** [comment]
> I'm using Visual Studio to check the icons stored in the exe. I'll look around for a lightweight way to do so. 

Right click on the .exe, Properties/Change-Icon shows two icons for me (2015.02.05) one with the Sphere/Cylinder, and one with that plus 'scad'.

**Comment by TDeagan** [comment]
Wow, good trick!  I've never tried checking via right click properties.

This is frustrating.
1) Registry entries are set correctly
2) Registry entries point to a valid icon image present in the exe

This should be all it takes to show Document Icons.  It only works for the
account that installed/runs OpenSCAD.  I'd ask if you'd installed as a
different user, but then you wouldn't be seeing the HKEY_CURRENT_USER (and
by extension the HKEY_CLASSES_ROOT which is derived from it,) value.

Works on Win 8.1 Enterprise 64-bit (and Win 7.)  Gaaargh!

If you look at a .scad file with a Save As or Open dialog rather than
explorer, do you see the document icon version?

**Comment by MichaelAtOz** [comment]
*       If you look at a .scad file with a Save As or Open dialog rather than explorer, do you see
the document icon version?

 

If by document icon, you mean the icon with 'scad', yes for both Open & Save As.

 

I also switched users to an admin account which has not had OpenSCAD run/installed before. It
showed document icon in explorer.

(W7/64)

 

Hope that helps.

 

  _____

**Comment by TDeagan** [comment]
So, let me see if I have understood the situation.

Definitions:
* App Icon: Icon without the SCAD text
* Document Icon: Icon with the SCAD text

Statements (True or False?):
A. you're on a Win 8.1 32-bit system
B. You've installed the latest development snapshot (32-bit zip) (http://files.openscad.org/snapshots/OpenSCAD-2015.02.05-x86-32.zip)
C. You've unzipped and run openscad.exe
D. You've rebooted the system after running openscad.exe
E. (Post D.) The following registry keys are valid on the syste m:
 * HKEY_CURRENT_USER/Software/Classes/OpenSCAD_File/DefaultIcon/Default
   * C:\Users\IEUser\Desktop\openscad-2015.02.05\openscad.exe,1
 * HKEY_CLASSES_ROOT/OpenSCAD_File/DefaultIcon/Default
   * C:\Users\IEUser\Desktop\openscad-2015.02.05\openscad.exe,1
 * HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon
    * Not found

F. (Post D.) You DO NOT see the document icon in Windows Explorer for .scad files
G. (Post D.) You DO see the document icon for .scad files in 'Save as' and 'Open' dialogs
H. (Post D.) You DO see the document icon for .scad files in explorer when using an admin account

So at this point, F is the problem?

**Comment by MichaelAtOz** [comment]
If you are asking me. 

a. no I am not on Win 8.1, I'm on Win 7 64 bit.
b. I have NOT 'installed' (...Installer.exe) the latest 64 bit snapshot 2015.02.05 64-bit, but,
c. I have unzipped the latest 2015.02.05 64-bit zip file and run that openscad.exe
d. I have not rebooted since c. (I have a number of previous versions of openscad.exe in place prior to my last reboot)
e. NOT post d. ie I have not rebooted.
* First two keys have
 * C:\Program Files\openscad-2015.01.23\openscad.exe,1
 * (probably the last run openscad before last reboot)
* HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon 
 * has C:\Program Files (x86)\OpenSCAD\openscad.exe,0
 * that is the last version I 'installed' (2014.03 32-bit)

f. Not post d. I DO see the document icon in Windows Explorer for .scad files
g. Not post d. I DO see " in 'Save As' and 'Open' dialogs
h. Not post d. I DO see " for .scad files in my admin account.

I don't have a problem (well at least in this context), that I know of...

**Comment by kintel** [comment]
a. Win 8.1 32-bit
b. Yes, I've downloaded http://files.openscad.org/snapshots/OpenSCAD-2015.02.05-x86-32.zip
c. Yes, unzipped to Desktop and run openscad.exe
d. then rebooted
e. registry is exactly as listed
f. I do _not_ see the document icon for .scad files, but I see the app icon instead
g. I do _not_ see the document icon for .scad files in Save As an Open dialogs, but I see the app icon instead
h. I don't know if I have an Admin account.


In terms of Admin accounts, I'm using a VM from https://www.modern.ie. It gives me an "IEUser" account, but I don't know how to establish if that's an admin account or not. The account manager says "Local Account", but it also says I need to activate Windows before personalizing my account.

**Comment by MichaelAtOz** [comment]
I created a new account and switched users.

In that account:
b. I have NOT 'installed' (...Installer.exe) the latest 64 bit snapshot 2015.02.05 64-bit,
c. I have NOT unzipped the latest 2015.02.05 64-bit zip file and First time NOT run that openscad.exe

* .scad files in Explorer showed a blank-page icon
* I ran OpenSCAD 15.02.05/64, .scad file shows as blank-page icon in Open & Save As dialogs

d. I have not rebooted since
e. NOT post d. ie I have not rebooted.

While logged on as new user.
* First two keys have 
 * C:\Program Files\openscad-2015.02.05\openscad.exe,1
       
* HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon
  * has C:\Program Files (x86)\OpenSCAD\openscad.exe,0

f. Not post d. I DO NOT see the document icon in Windows Explorer for .scad files
g. Not post d. I DO NOT see " in 'Save As' and 'Open' dialogs

I presume you would like me to reboot & check the new account?

**Comment by TDeagan** [comment]
My apologies.  I was trying to be responsive to the problem (eeeek! bugs in my code!!) while also trying to be at work and it led to me adding to the confusion in the thread.  I wasn't paying enough attention to MichaelAtOz's input in the thread, mixing it in my head with Marius's initial problem of not seeing the document icon.

So far it's working on;
*  win 7 64 bit (MichaelAtOz)
*  win 8.1 64 bit (TDeagan)

Failing on:
* win 8.1 32 bit (kintel)

I'll test tonight on win 7 32 bit and win 8.1 32 bit VMs to see if I can replicate the fail.

**Comment by TDeagan** [comment]
I have duplicated the fail, it _appears_ to be a 32-bit problem.  I'm downloading a win 7 32 bit iso and will try it there.

So far it's working on;
*  win 7 64 bit (MichaelAtOz)
*  win 8.1 64 bit (TDeagan)

Failing on:
* win 8.1 32 bit (kintel, TDeagan)

**Comment by MichaelAtOz** [comment]
> it appears to be a 32-bit problem.... So far it's working on win 7 64 bit (MichaelAtOz)

Yes & No.

On my usual account it (64-bit) works.

I rebooted, logged on as the new test account mentioned above, now it doesn't work (on the test account).

BTW @kintel 
* the progress dialog on Font Cache creation works properly on that new test account, so something funny in my usual account...
* but that shows that for multiple users on one PC, it will have multiple caches, even tho fonts are system wide.

Back on topic.
In summary

A. I'm on a Win 7 64-bit system
B.  OpenSCAD-2015.02.05-x86-64.zip was already downloaded and unzipped into program_files
C. In the Test account I had run openscad.exe before rebooting (blank-page icons shown before & after)
D. I rebooted the system after running openscad.exe on the test account
E. (Post D.) The following registry keys are valid on the system test account

* HKEY_CURRENT_USER/Software/Classes/OpenSCAD_File/DefaultIcon/Default
 * C:\Program Files\openscad-2015.02.05\openscad.exe,1
* HKEY_CLASSES_ROOT/OpenSCAD_File/DefaultIcon/Default
 * C:\Program Files\openscad-2015.02.05\openscad.exe,1
* HKEY_LOCAL_MACHINE/SOFTWARE/Classes/OpenSCAD_File/DefaultIcon
 * C:\Program Files (x86)\OpenSCAD\openscad.exe,0


F. (Post D.) I DO NOT see the document icon in Windows Explorer for .scad files
G. (Post D.) I DO NOT see the document icon for .scad files in 'Save as' and 'Open' dialogs
H. (Post D.) You DO see the document icon for .scad files in explorer and 'Save as' and 'Open' dialogs when using my usual account

So at this point, F & G are the problem on a newly created account (user).

**Comment by TDeagan** [comment]
I have now tested on four platforms:

Working as expected;
*  win 7 64 bit 
*  win 8.1 64 bit 

Failing to display document icon:
* win 7 32 bit 
* win 8.1 32 bit 

Due to the need (described in #1082,) to avoid triggering a permissions modal, the document icon should only display for users who run openscad.exe. 

This is very frustrating.  I cannot find any documentation suggesting that there is a known issue with 32-bit OS's and the DefaultIcon setting.

The registry settings are appropriate and openscad.exe contains the both icons.    

I extracted the .ico from openscad.exe and changed the registry to point to it.  No luck. 

I modified the icon to use lower bit-depth values and pointed to it. No luck.

I can get the non-SCAD text version to appear if I do a file association, and that icon is coming from openscad.exe and is of the same bit depth as the desired icon, so I'm baffled.  

I'll keep thinking.

**Comment by TDeagan** [comment]
Wow.  I had a brainfart and changed the DefaultIcon value in the registry for CompressedFolder to the exact value we have failing for the .scad files.  And it WORKS!  The frakking zip files show up with the OpenSCAD icon with SCAD underneath.  (all on the win 8.1 32-bit machine)

This, at least, proves that:
* there is no problem with the icon stored in openscad.exe
* the registry key value (as a valid designator for the icon stored in openscad.exe)

I'm not sure what that leaves.

**Comment by kintel** [comment]
Btw., there's a secondary issue that the icon seems to not resize, like the other icons do.
I assume that's unrelated, but just good to keep in mind : /

**Comment by MichaelAtOz** [comment]
a.
> Right click on the .exe, Properties/Change-Icon shows two icons

That was on a shortcut, doesn't work on an exe

b.
I thought it may be due to Admin privileges, so added a TestingAdmin account, no difference, does NOT work for 32 or 64 bit.

c. Only diff now is my usual account has UAC off, I'll try that next. (but I never got any UAC screens on the test accounts)

d. 
>  the icon seems to not resize

For me, small & medium work, large & extra-large show as medium size.

e. I'll add some font observations to the text() issue.

**Comment by TDeagan** [comment]
The resizing issue is strange, but not as strange.  

The original openscad icon embedded in openscad.exe has only one size:
* 128 x 128 32-bit

When I created the doc icon, I thought I'd extend this to a larger set:
* 32 x 32 32-bit
* 48 x 48 32-bit
* 64 x 64 32-bit
* 128 x 128 32-bit

image

(32-bit icons are really a 24-bit image with an 8-bit alpha channel.  Systems using less than True Color will treat the 32-bit image as a 24-bit with an AND mask constructed from the alpha channel.)

As an experiment, I used the free but really nice, icon tool I've been liking (Greenfish Icon Editor http://greenfishsoftware.blogspot.hu/2012/07/greenfish-icon-editor-pro.html) to construct an icon file with the 'standard set' of sizes and depths:

image

I pointed the HKEY_CLASSES_ROOT DefaultIcon value for CompressedFile at this new multi-size icon file and it resized nicely to small, medium, large and extra large.

I undertook some jiggery-pokery with the OpenSCAD_File registry (rebooting after each);
A. tried pointing the HKEY_CURRENT_USER key at the multi-size.ico (that works with compressed files,) no luck
B. Deleted (A) tried changing HKEY_CURRENT_USER  data type (to the one used by CompressedFile,) no luck
C. Deleted (B) tried deleting the HKEY_CURRENT_USER key and writing it directly to HKEY_CLASSES_ROOT, no luck
D. Deleted (C) tried changing HKEY_CLASSES_ROOT  data type (identical to the one used successfully by CompressedFile,) no luck
E. deleted (D) and created an HKEY_CLASSES_ROOT DefaultIcon key for .scad, **WORKED!!**  
F. deleted (E) and created an HKEY_CURRENT_USER DefaultIcon key for .scad, **ALSO WORKED!!**  

F is important since the code is not really able to write to HKEY_CLASSES_ROOT without getting into a lot of security foo.

I will now go test this approach on the other 32-bit and 64-bit machines.  Worst case we have to write both keys.  I am depressed, the current approach in code is the 'best practice' approach and works in 64-bit, so that's just weird.

We're looking at a swap of the icon file and a code change for the pull that will fix this.

**Comment by TDeagan** [comment]
FRAK!@!

If the user has done an association of .scad files to openscad.exe the registry key that is created:
```
hkey_current_user\software\microsoft\windows\currentversion\explorer\fileExts\.scad
```
overrides the DefaultIcon value and puts the regular (no SCAD text) icon on the .scad files (inside a little paper icon.)

I'll try seeing if I can change the icon inside this.  I'm not sure at all that we would want to automatically associate .scad files with openscad.exe.  I, for one, want my .scad files opening in notepad++.

Gaarrrgh!  this is a frustrating feature!!!!!

**Comment by TDeagan** [comment]
Geez, I'm turning this into a freaking blog.  (but we're at a decision point, see bottom of note)

GOOD NEWS: I downloaded a program called DefaultProgramEditor and got it to reset the icon for .scad files, which worked.  It did so by creating the following key:
[HKEY_CURRENT_USER\Software\Classes\scad_auto_file\DefaultIcon]
This still allowed the file association with openscad.

BAD NEWS: I then tried changing the file association for .scad to notepad, which changed the icon for the .scad file to the notepad icon.  Rerunning the .reg file to set the [HKEY_CURRENT_USER\Software\Classes\scad_auto_file\DefaultIcon] key did nothing.

So.  Here's where things are;
1. The method that's working on 64-bit systems is not working on 32-bit systems
2. There is an alternate method of setting the document icon that works on 32-bit systems, (currently untested on 64-bit systems, but if it doesn't we could do both methods or try to detect the system and use the appropriate one)
3. On both 32-bit and 64-bit systems, setting the file association for .scad files overrides the DefaultIcon setting and replaces it with the icon of the associated exe (notepad++, openscad, etc.)

(3) is the killer.  *Should we continue with number 2 above or bow to the inevitability of number 3?*

**Comment by MichaelAtOz** [comment]
You don't seem to notice that I have NOT been able to get the icon (either of them) to show against .scad files with 2015.02.05 (either 32 or 64 bit), for new user accounts I created on my Win 7 64 bit system.

Given the document icon shows on my usual account, and I looked at the icons in my recent shortcuts, the document icon is in the 2015.01.16 exe but not 2015.01.16 exe.

I have 2015.  01.13, 01.16, 01.23 02.05 'installed' via zip (ie un-zip into program_files, create a shotcut in start/programs). 

One of the last three must have setup the document icon.

It is possible that 01.16 or 01.23 correctly set the document icon, and 02.05 does NOT.

As I have NOT been able to get the icon into the test accounts with 02.05, I will try 01.16 in one, and 01.23 in the other.

**Comment by MichaelAtOz** [comment]
Note: I only 'Install' with installer.exe, the release version, so current file association is set to 2014.03. When I double-click a scad file it opens in that version. [not to self, test installer.exe in another account]

I have NOT manually made any file associations. 

So something changed the 2014.03 icon, to the new document icon.

**Comment by TDeagan** [comment]
> You don't seem to notice that I have NOT been able to get the icon (either of them) to show against .scad files with 2015.02.05 (either 32 or 64 bit), for new user accounts I created on my Win 7 64 bit system.

My apologies, it's not that I haven't noticed, it's just that I confused the situation earlier by mixing up your and Marius's responses and since then have been attempting to solve one problem at a time.

Marius had a simple problem that has led to a lot of complexity as I've been troubleshooting it.  As I've gotten closer to an understanding of what's going on with it, I've been trying to incorporate your notes into my troubleshooting.

If I'm understanding what you're noting above, that the icon showed for your usual account, but not for new accounts, that is expected behavior.  If the new account runs openscad.exe and then, after a reboot, does not see the icon, that would be a problem,  

I'm very sorry, but I'm not clear at all about which versions had which features.  I'm doing all my troubleshooting against the latest dev snapshot (2015.02.05).

In the end, the recent issues I've identified regarding file association overriding the document icon leaves me wondering if the entire document icon approach shouldn't be abandoned all together. (hence the emphasis at the end of my previous message.)

If your notes have been trying to communicate something that I'm clearly missing, I apologize.  I'm trying to troubleshoot this while dealing with a lot of family drama going on in my house and may not be applying sufficient attention to the problem.

**Comment by MichaelAtOz** [comment]
> If the new account runs openscad.exe and then, after a reboot, does not see the icon, that would be a problem, 

That IS a problem. OpenSCAD 02.05 (both 32 & 64 bit), have been run in those new accounts, the system rebooted, yet the .scad files still show as a blank-page icon, both in Explorer and in Open/Save-As.

> the entire document icon approach shouldn't be abandoned all together

Perhaps deferred to the next release? Not my call tho.

> a lot of family drama

Family drama trumps missing icons every time. Hope it sorts itself out.

**Comment by TDeagan** [comment]
> That IS a problem. OpenSCAD 02.05 (both 32 & 64 bit), have been run in those new accounts, the system rebooted, yet the .scad files still show as a blank-page icon, both in Explorer and in Open/Save-As.

Sidestepping the issue of the file association wiping out the document icon, I _believe_ we could overcome the account problem you're seeing if we're willing to have the security modal pop up for the user.  This is the dialog that darkens the whole screen and demands you indemnify windows for the dangerous installation you're about to commit.  I really felt like this was a lot to ask of the user for an icon change, but perhaps not. 

The issue is that we currently set HKEY_CURRENT_USER, if we're willing to do the equivalent of a 'install for all users', we could write to HKEY_LOCAL_MACHINE.

 I'd need to mod the code to only try setting the registry value if it's not currently set (no biggie.)

But all that would be for nought if they set a file association for .scad files.   Gack!

> Hope it sorts itself out.

Thanks,  I fear it's more of a lifestyle at this point.  so it goes...

**Comment by nophead** [comment]
If it's any consolation: a lot of Windows applications change the document
icon to their program icon when they grab file associations. For example I
installed VLC and now all my media files look like traffic cones, very
annoying.

Visually studio grabs the file associations for .h, .cpp, etc, but gives
them different icons according to their type. I think OpenScad should work
the same way but I don't think there is anything you can do to prevent
other apps subsequently changing the document icon if they are associated
to .scad. For this reason I leave .scad associated to OpenScad and use
right click Open with Notepad++ if I want to edit them.

**Pull request merged**
