### PR TITLE
surface / heightmap performance improvements, take 2

### PR DESCRIPTION
**Pull request by ChrisCoxArt**
Improve performance and reduce memory usage when using surface("file") aka heightmaps.
The remaining time is mostly in CGAL and Eigen code.
This could be faster still with a suballocator (which someone else is working on).

Performance with a 1024x1024 PNG image:
2021.01 Release
Total rendering time: 0:00:06.903

Baseline 2021 source code
Total rendering time: 0:00:05.978

New code
Total rendering time: 0:00:04.191

### CODE REVIEW

**Comment by ChrisCoxArt** [comment]
Odd. The mac build is failing for test 1105*, but passes on other platforms, and passes on my machine (MacOS 12.0.1, x86_64).

**Comment by ChrisCoxArt** [comment]
OK, I can fix the "security violations" (which are unlikely integer overflows).
But even with the latest libraries and a full rebuild - I can't reproduce the test errors on MacOS.

**Comment by t-paul** [comment]
Hmm, the test result upload did not work for the macos build, I'll have a look. Maybe it's again some OpenGL software renderer issue.

**Comment by ChrisCoxArt** [comment]
Is there any way (other than submitting a new PR) that I can get the macOS failure report?  Or trigger a new run and report?

**Comment by t-paul** [comment]
I don't know if there's a way to force the use of software rendering locally (assuming this is what's causing the failure). The CI is just running the normal test suite via `ctest`.

**Comment by ChrisCoxArt** [comment]
Normal build - all tests pass on my system.

Forcing SW rendering in OffscreenContextCGL.mm  (and recompiling each time) :
kCGLRendererGenericID - all tests pass except
	1334 - openscad-viewoptions-edges_view-options-tests (Failed)
	1335 - openscad-viewoptions-axes-scales-edges_view-options-tests (Failed)
kCGLRendererAppleSWID - ALL CGAL tests fail
kCGLRendererGenericFloatID - all tests pass except
	1334 - openscad-viewoptions-edges_view-options-tests (Failed)
	1335 - openscad-viewoptions-axes-scales-edges_view-options-tests (Failed)

Sigh. Still can't reproduce the CI errors.

**Comment by ChrisCoxArt** [comment]
Interesting. Even with that change commented out, the test still fails on the mac VM.

**Comment by ChrisCoxArt** [comment]
OK, that is weird.  A change to vector hashing caused/cured the issue 1105 failure?

**Comment by ChrisCoxArt** [comment]
@t-paul Can you take another look now that I've solved the mystery test issue?

**Comment by ChrisCoxArt** [comment]
@t-paul could you take another look at this?

**Comment by ChrisCoxArt** [comment]
KIntel just made the same change I did in the setenv script.  Let me go undo that.

**Comment by ChrisCoxArt** [comment]
crud, accidentally checked in a color theme change with the setenv rollback.

**Review by t-paul — APPROVED** [review]
I don't mind the color scheme change, it's new and yours anyway :smile:.

**Pull request merged**
