### PR TITLE
Angle parameter for rotate_extrude

### PR DESCRIPTION
**Pull request by thehans**
This is a proposed patch for Issue #1191 

It works correctly as far as I can tell, but this is my first dive into openscad code.

### CODE REVIEW

**Comment by kintel** [comment]
Thanks!
There are a few things needed from here, primarily tests and documentation.
See https://github.com/openscad/openscad/blob/master/doc/testing.txt and https://github.com/openscad/openscad/blob/master/doc/hacking.txt

I'll come back in a while and add a checklist to the pull request, so we can get it all merged.
If you want, we can temporarily merge this into a feature branch if you don't want to manage pull requests no this feature yourself.

**Comment by thehans** [comment]
I noticed it failed pretty much every rotate_extrude test.  I haven't looked into how the tests work yet, but I'm guessing it doesn't like that I flipped the starting angle.

Lines 835, 839, 841 would have had -M_PI/2 in them, i made it positive.  My reason for this was that I noticed it was starting the arc on the negative side of the x axis rather than the positive.

Also I wasn't sure for partial angles, which direction to rotate.  Currently it goes clockwise when viewed from the top(linear_extrude with twist seems to do this also), but counterclockwise from X+ is how I've always pictured angles in cartesian grids.

**Comment by kintel** [comment]
I think we should rotate counter-clockwise, starting from the positive X axis.
Some parts of OpenSCAD violate some default convention, but let's fix those later.

**Comment by thehans** [comment]
I changed the default rotation to counter-clockwise as discussed.  

I noticed Issue #1282 while I was at it, and addressed that as well.  Geometries in the negative X side now start their arc from that side.

The code also now allow for negative angle inputs, which arc from the X axis in the clockwise direction.
Here is a quick test I used to verify faces for all combinations of positive/negative inputs.

```
module face(x) {
  translate([x,0]) difference() {
    square(5,center=true);
    circle(2);
  }
}
rotate_extrude(angle=45) face(10);
rotate_extrude(angle=45) face(-10);
rotate_extrude(angle=-45) face(20);
rotate_extrude(angle=-45) face(-20);
rotate_extrude() face(30);
rotate_extrude() face(-40);
```

**Comment by thehans** [comment]
OK, so I am more confident now that the code is performing correctly.  

There are two types of test errors to deal with.  

1) The image tests fail because as mentioned before they are starting the rotation from the +X axis.  This is really apparent in the $fn=3 case for example, or other odd numbers.  Should I just commit my new generated output pngs into the tests/regression path?

2) The dump tests fail since there is a new parameter in the text.  One thing that is still possibly open to change is the ordering of the parameters.  Teepee had mentioned in irc that it might be worthwhile to position angle as the first param for convenience, but this would technically break backwards compatibility.  Though i noticed the whole file parameter thing is deprecated anyways.  Even disregarding the dxf file parameters, I currently have angle placed after convexity.

Here is what my code is outputting at the moment.  What do you think should be done?

    // example with file parameter
    -rotate_extrude(file = "open-polyline.dxf", layer = "", origin = [0, 0], scale = 1, convexity = 2, $fn = 0, $fa = 12, $fs = 2);
    +rotate_extrude(file = "open-polyline.dxf", layer = "", origin = [0, 0], scale = 1, convexity = 2, angle = 360, $fn = 0, $fa = 12, $fs = 2);

    // example without file parameter
    -rotate_extrude(convexity = 3, $fn = 0, $fa = 12, $fs = 2) {
    +rotate_extrude(convexity = 3, angle = 360, $fn = 0, $fa = 12, $fs = 2) {

Additionally there are two tests that failed locally which are omitted from travis CI
411 - opencsgtest_rotate_extrude-tests (Failed)
This has the above mentioned difference of starting on +X axis

465 - opencsgtest_issue1165 (Failed)
this has some z fighting artifacts unrelated to rotate_extrude, which i'm assuming is just difference in graphics cards or something.

**Comment by kintel** [comment]
Moved to #1478 to facilitate collaboration

**Pull request closed without merging**
