### PR TITLE
double-conversion library

### PR DESCRIPTION
**Pull request by thehans**
Testing a branch on openscad repo so test uploads work

Issue #2744

### CODE REVIEW

**Comment by kintel** [comment]
Looks like some unrelated stuff, like tessellation, snuck into this PR..

**Comment by thehans** [comment]
Yes I based this branch off of some prior optimizations from #2738.  
This included the tesselation change, and some beginning of the `toStream` optimization, which I did some more work on in this branch also.  

My reason for this was that all the changes were working towards optimize the same [script/use-case](https://gist.github.com/nophead/fd4ca58b5f6b19dc25bb98f7edbae90f) and made it easier for me to profile performance differences with the other bottlenecks out of the way.  

I didn't intend to be sneaky about it.  Would you prefer I split out the tesselation change?  I feel like the `toStream` changes particularly was integral to making the most out of faster double to string conversions, so I think that would ideally be kept in this PR.

**Comment by kintel** [comment]
I'll review this as is - I was just checking if it was a mistake..

**Comment by MichaelAtOz** [comment]
> One small missing piece

I just looked at the commit titles and didn't see it, was it added to the help/library-info?

**Comment by thehans** [comment]
@MichaelAtOz It has not been added to library info.  Unfortunately there is no version information provided in the headers or any other way that I can see to retrieve it.

**Pull request merged**
