### PR TITLE
Calculate STL normals from string formatted vertex data for consistency

### PR DESCRIPTION
**Pull request by thehans**
for #1853

### CODE REVIEW

**Comment by kintel** [comment]
Looks good!
Is there a way you could write a single test case that confirms that the output matches the input?
(not to validate that your code is correct, but to catch failed attempts to refactor this in the future)

**Comment by thehans** [comment]
Ok, I'm looking into creating a test, but the workflow for this test is unlike any existing tests.  They all basically expect to compare two pngs at the end.

I guess I'm looking at creating another script similar to 
 ```export_import_pngtest.py``` , call it ```export_import_stltest.py``` and then figuring how to work that into the rest of the ctest framework

Any tips or suggestions?

**Comment by kintel** [comment]
I think this should be doable with the current python script by doing smth. like this:
```
add_cmdline_test(mytest EXE ${OPENSCAD_BINPATH} ARGS -o SUFFIX stl FILES ${MY_TEST_FILES})
```

The script should pick up on the stl suffix and compare the STL files.

**Comment by thehans** [comment]
@kintel that would require me to push an "expected" STL to github right?  The problem is because of #420.  I don't think the ordering of the triangles will be guaranteed across platforms.

The test procedure which I've done manually so far is:
1. Open a `issue1853.scad` file, and do an STL export.  (this will count as our "expected" file later)
2. Import that STL and export to STL again.
3. diff the two STL files

That seems to work ok since its all done from the same build. 

In the comments of the tests/CMakeLists.txt here, it lists the different cmdline test types: https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L1612-L1628
A couple are STL related, but these ultimately compare against png files at the end:
```
# o stlpngtest: Export to STL, Re-import and render to PNG (--render)
# o stlcgalpngtest: Export to STL, Re-import and render to PNG (--render=cgal)
```
So that's why I'm thinking there would need to be a new test type, with its own .py script:
`# o stlstltest: Export to STL, Re-import and export to STL again, compare with first export.`

Or maybe I should just say this is blocked by #420 and start working on that.

**Comment by kintel** [comment]
ok, sounds fair. If it's too much work, time is probably best spend elsewhere.

**Comment by MichaelAtOz** [comment]
I seem to recall @nophead had a method that sorted the STL so they could be compared.

**Comment by thehans** [comment]
@MichaelAtOz Yes, it's mentioned in the initial comment of #420 :stuck_out_tongue: 

And to save you an extra click, the direct link:
https://github.com/nophead/Mendel90/blob/master/c14n_stl.py

I think the ultimate solution for #420 should be rewritten to be handled by the c++ stl export code, but maybe this python script would be a good addition to the test suite in this case.

**Comment by kintel** [comment]
@thehans Re-reading this PR. Consistent normal output is only implemented for PolySet exports, not for CGAL Nef3 export. Is this just an oversight or was this done on purpose?

**Comment by thehans** [comment]
@kintel I don't think the function `static void append_stl(const CGAL_Polyhedron &P, std::ostream &output)` is ever called with the current code and I guess I feel like it should be deleted but wasn't going to bother with it in this PR.  All the code paths end up converting to polyset if its not already.  

Is there a reason to keep this always true conditional or any of its `else` block code ?
https://github.com/thehans/openscad/blob/f2a42bc3a3f29a9c52e34bd7e693c7bdbd8c5f4e/src/export_stl.cc#L177-L185
because I think the only call to the CGAL_Polyhedron method is in the unused else branch.

**Comment by kintel** [comment]
Good point. The always-true `if` was introduced when fixing #337 a couple of years back. I guess we could kill the always-false branch now.

**Pull request merged**
