### PR TITLE
Search function simplification

### PR DESCRIPTION
**Pull request by clothbot**
Now that more list operators exist, simplify search function for more
intuitive usage.

Creating pull request to see how travis-ci likes the changes, see if I've updated all the affected test properly.

### CODE REVIEW

**Comment by kintel** [comment]
I just haven't had time to look at this. Will try to get to it soon..

**Comment by kintel** [comment]
@clothbot I briefly looked at this. Am I correct in that you're breaking some previous less useful use-cases of search() in favour of using more convenient built-in functionality? If so, did you think about how to deal with existing OpenSCAD code?

**Comment by kintel** [comment]
@clothbot thx. However, this still means that existing designs depending on the legacy behaviour would fail. We generally strive towards supporting existing designs, except in cases where the expected number of users of said functionality is small enough that it won't have any real impact (or said users are power users and happy to update and haven't shared their design with "the world").

Any idea how that would relate to your changes?

**Comment by kintel** [comment]
heh, yeah. I have some scripts that I run against ca. 2500 Thingiverse models for correctness and performance testing. They could be expanded to record some more info, but that's a bit of work: https://github.com/openscad/statistics-scripts

**Comment by kintel** [comment]
The MakerBot guys appear to be too busy for that sort of stuff, so I try not to ask anything more from them, except an occasional friendly reminder to upgrade to the latest version.

**Comment by kintel** [comment]
Travis CI don't retain any state between builds, so to do that it has to download all designs, all previous results and run the script - which would take ~10 hours or so. If any free or reasonably priced service exist which offers this, I'd be interested.

**Comment by ArchimedesPi** [comment]
@kintel If this is a thing that would be useful I can set up a semi-regular cron job on a server I own to do run the script every couple days.

**Comment by kintel** [comment]
@ArchimedesPi That would be interesting indeed. I started writing a bunch of scripts for managing this, but it gets messy pretty fast: https://github.com/openscad/statistics-scripts

Some of this is will probably look a lot cleaner if we're not doing everything over the filesystem. ..but using Makefiles really makes things more manageable.

**Comment by kintel** [comment]
Cleaning up some old PR which we, unfortunately, didn't give enough love to see through.

**Pull request closed without merging**
