### PR TITLE
Upgrade Qt and QScintilla for macOS

### PR DESCRIPTION
**Pull request by kintel**
Qt: 5.15.2
QScintilla: 2.11.6

Notes:
* Qt 5.15.2 requires macOS >= 10.13 "High Sierra". They actually use system calls introduced on 10.13 with no way of #ifdef'ing out of it, so there is no trivial way of supporting older versions of macOS.
* x86_64 only, but this upgrade does offer a theoretical pathway to arm64 (and universal binary support)

### CODE REVIEW

**Comment by kintel** [comment]
Giving it some soaking time to let people in #3775 test this.

**Comment by t-paul** [comment]
Good idea. Unfortunately I'm out at this point as the MacOS version of my old MacBook is too old. But I guess we have to move eventually.

**Comment by kintel** [comment]
If your MacBook Pro is from 2010 or later, you _should_ be able to put 10.13 on it

**Comment by t-paul** [comment]
Hmm, it already feels slower than a Raspi1 as it is, but I guess there's not a huge amount to lose trying to upgrade. If they would sell Mac Minis for at least half reasonable prices, I might be a bit interested. We'll see :grinning:.

**Comment by kintel** [comment]
heh, yeah, slow is expected. I use an 8 year old laptop running 10.13 in a VM. Now, _that_ is slow :)

**Comment by t-paul** [comment]
Looks like the github build (MacPorts) asks for a rebuild too:
```
Error: Current platform "darwin 20" does not match expected platform "darwin 19"
```
I'll trigger that...

**Comment by kintel** [comment]
Which build is that?

**Comment by t-paul** [comment]
`macos-release`
https://github.com/openscad/openscad/runs/4063856881

**Comment by kintel** [comment]
Looks like the GitHub build has other issues; MacPorts' cmake pick up libbz2 and libz from MacPorts instead of the system:

```
% otool -L /Volumes/T7/code/OpenSCAD/ci-cache/GitHub/libraries-gh/lib/libzip.dylib 
/Volumes/T7/code/OpenSCAD/ci-cache/GitHub/libraries-gh/lib/libzip.dylib:
	@rpath/libzip.dylib (compatibility version 5.0.0, current version 5.0.0)
	/opt/local/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/opt/local/lib/libbz2.1.0.dylib (compatibility version 1.0.0, current version 1.0.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
```

May be better solved against master.

Ironically, this sounds a bit like the same problem which caused us to manually build libzip in the first place. See similar problem I had with Poppler: https://github.com/openscad/openscad/issues/3920#issuecomment-954904503

**Comment by kintel** [comment]
-> I'll try to pull together a GitHub Actions build without using MacPorts tools and see where that leads..

**Comment by t-paul** [comment]
Ok, so lets merge that state for getting the snapshot builds updated and check the release build separately?

**Comment by kintel** [comment]
Sure, I'm fine merging this branch for now (after disabling the release build job for this branch).
I just wanted to give you some time in case you decided to upgrade your Mac and give this a spin, but happy to just merge for now  :)

**Comment by t-paul** [comment]
I'd say go :rocket:...

**Review by t-paul — APPROVED** [review]
/me closes eyes and clicks merge :scream:.

**Comment by t-paul** [comment]
FWIW, no High Sierra for this MacBookPro, it's Mid-2009, but required is "2010 or later" :disappointed:.

**Pull request merged**
