### PR TITLE
Autocomplete / CallTips for QScintilla

### PR DESCRIPTION
**Pull request by t-paul**
This is based on the scintillaeditor branch and is mainly here for discussing how we want to use the AutoComplete / CallTips feature that is provided by Scintilla.

Things to decide:
- How to format the CallTips display? What information to present?
- What options are needed
  - enable/disable AutoComplete
  - AutoComplete threshold
  - enable/disable CallTips
  - ...

ToDo:
- [ ] Complete list of keywords
- [ ] Move data to separate text file, currently it's just in code

AutoComplete / CallTips
screencast

UserList providing a set of templates to insert at the cursor position (currently triggered by CTRL-I)
screencast

### CODE REVIEW

**Comment by Scalpel78** [comment]
Any more work being done on this?

**Comment by t-paul** [comment]
Nope, still waiting to be picked up again.

**Comment by snoerenberg** [comment]
I would love to use it.

**Comment by t-paul** [comment]
Closing this as it's pretty stale now, rebased version in #2889.

**Pull request closed without merging**
