### PR TITLE
2015.03: Build fix for boost 1.69

### PR DESCRIPTION
**Pull request by hroncok**
Cherry-picked from 8fb64db99ce05da1c72efb8b2f572995fef2ea86

### CODE REVIEW

**Comment by kintel** [comment]
Does this actually build against 2015.03 without C++11 support?

**Comment by hroncok** [comment]
I don't really know. (You don't need to merge it if there are concerns like this, I just wanted to contribute the backport back fo other interested parties.)

**Comment by t-paul** [comment]
With 2019.01-RC2 out, there's probably not going to be any patch release for the ancient branch.

**Comment by hroncok** [comment]
I was thinking other distro packagers.

**Comment by kintel** [comment]
Sounds fair, I'll merge this to the branch, but won't release a new patchlevel update.

**Comment by hroncok** [comment]
Thanks.

**Comment by t-paul** [comment]
I've not heard of any distro packaging not released branches though.

**Comment by hroncok** [comment]
Well we just take patches mostly. And it's always easier if they apply directly.

**Pull request merged**
