### PR TITLE
disable indent-spinbox in IndentLineWrap style

### PR DESCRIPTION
**Pull request by Sharma-Hrishabh**
This commit disables the 'Indent' spin-box when 'Indented' option is chosen from 'Line Wrap Indentation Style'.
The purpose of doing this is explained in issue #2670  (for future contributors)

### CODE REVIEW

**Comment by Sharma-Hrishabh** [comment]
Yaa, you were right @t-paul , that line is not required at both the places. I tested, it out and concluding that it is required only inside the function. It's not working properly outside that function. 

I'm looking over that comparing things.

**Comment by Sharma-Hrishabh** [comment]
Hey @t-paul , I think we can also use the current index of combo-box for comparison, and that would have no relation with the language.

**Comment by Sharma-Hrishabh** [comment]
Hey @t-paul , after checking the documentation and surfing the StackOverflow and forums, I get to know that ->currentText() gives you the second value(i.e displayed on UI) and ->currentData() gives you the first value(i.e untranslated value) on a combo-box
S.o, I changed that to ->currentData() instead.
I have made proper checks by changing the language on my Ubuntu 19.04 System. All is working fine.

**Comment by t-paul** [comment]
Sounds good, Qt documentation says _This property was introduced in Qt 5.2._ and we have minimum version 5.4. now.

**Comment by Sharma-Hrishabh** [comment]
Cool, this is a helpful addition. So, I think this change is serving our purpose.

**Comment by t-paul** [comment]
This works now nicely even when setting non-english language. But I think I found the reason for the other place that was checking the condition. When selecting a value that has the spinbox disabled and restarting the application, the spinbox is not disabled anymore. Changing the combobox fixes it again.

**Comment by Sharma-Hrishabh** [comment]
Ooh, yes you are right @t-paul, I was just restarting the application each time after making, so the default value was fixed. So I didn't observe this. Thanks, you observed it nicely.
It would be nice if we leave comments to explain the existence of this line. Is it allowed @t-paul ?

**Comment by t-paul** [comment]
Yes, adding this comment now is a very good idea so we don't fall into that trap again in case we need to modify this code sometime later.

**Comment by Sharma-Hrishabh** [comment]
Ok @t-paul , I have added proper comments. This will help future contributors.

**Pull request merged**
