### PR TITLE
Enable SVG icons

### LINKED ISSUE #3786: Retina/hi-dpi toolbar icons
Current icons are:
- pixelated on retina/hi-dpi displays
- different styles as they were drawn at different times by different people

I'm happy to draw a new set of toolbar icons if this would be helpful.

New icons would be a unified style with a library of shapes that can be used for future toolbar icons.

They would be as vector so can work at any size, and I would contribute the original artwork and any exported versions (32px, 64px, black, white, etc) with no licence, or your chosen licence, attached.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/98647325-retina-hi-dpi-toolbar-icons?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by t-paul**
Enable use of SVG icons (fixes #3786).

- Set SVG icons directly on actions
- Remove icons from GUI file as they are set in code based on dark-mode detection
- Remove image files that are replaced with SVG generated from `icons.scad`

PR has MacOS CI-build enabled.

ToDo:
- [x] Convert all existing toolbar/menubar icons to SVG
- [x] Fix display, right now icons are just maxing out based on their bounding box, idea is to declare a specific size and patch that into the SVG header to prevent uneven scaling and allow for some empty margin.
- [x] Add QtSVG to AppImage Docker image (https://github.com/openscad/docker-openscad/commit/e109c4b8fab38f453084ff92f9b36f2cc238149f)
- [x] Add QtSVG to MXE Docker image (~https://github.com/openscad/docker-openscad/commit/e109c4b8fab38f453084ff92f9b36f2cc238149f~)
- [x] Test on AppImage (#3802)
- [x] Test on Windows
- [x] Test on MacOS

grafik

grafik

grafik

### CODE REVIEW

**Comment by t-paul** [comment]
@gingerbeardman could you please give that a go, I tested on an old MacBook where it seems to run ok, but I have no access to any HIDPI MacOS system: https://8109-1049088-gh.circle-artifacts.com/0/build/OpenSCAD-2021.06.03.dmg

**Comment by t-paul** [comment]
Windows ZIP (64bit): https://8111-1049088-gh.circle-artifacts.com/0/64-bit/OpenSCAD-2021.06.03.ci8111-x86-64_enable-svg-icons-macos.zip
Linux AppImage: https://8110-1049088-gh.circle-artifacts.com/0/64-bit/OpenSCAD-2021.06.03.ai8110-_enable-svg-icons-macos2021.06.03.ai8110-x86_64.AppImage

Both seem to have issues with displaying the icons unfortunately.

**Comment by gingerbeardman** [comment]
@t-paul icons working fine for me. 

let me know if you need more specific feedback.

**Comment by t-paul** [comment]
Thanks, as long as the icons show up and look ok, we should be good on MacOS. I think I got the Linux AppImage fixed too, just need to solve the issue for the Windows build.

**Pull request merged**
