### PR TITLE
Export icons for File->Export Menu items

### PR DESCRIPTION
**Pull request by TDeagan**
The compare makes this look a lot worse than it should. ( I get a lot of problems with QtCreator changing the indents on files.  My attempts to get things back right are frustratingly inconsistent.  What my diff tool declares identical, GitHub occasionally calls distinct.)

This pull request includes icons in the image subdir for STL,OFF,AMF,DXF,SVG,CSG and PNG and a set of white icons for each format (STL_wht.png, etc.).  

The icons are attached to the designAction* objects in MainWindow.ui.  

I changed what I believe are the correct lines (527-534 in new file,) in mainwin.cc that provide for the switch to the *_wht.png version when defaultcolor < 165.

I'm on windows and haven't managed to get the menu section to change color, so I wasn't able to test the white icons. :-(

### CODE REVIEW

**Comment by kintel** [comment]
That's indeed some weird diffs. I'd probably go back and recommit to avoid this ending up in the history.

**Comment by TDeagan** [comment]
Sounds like the right idea.  It's probably some weirdo end of line thing that windows wants to hide from me.  I will notepad++ it into submission.

**Comment by t-paul** [comment]
Maybe also have a look at https://help.github.com/articles/dealing-with-line-endings/

**Comment by TDeagan** [comment]
Aargh.  Github compare says every single line of src/MainWindow.h is different.  I have made no changes to src/MianWindow.h.  Visual inspection of the compare of src/MainWindow.h looks identical.  Git diff and git difftool locally say they're identical.  I have tried ```git checkout upstream/master -- src/MainWindow.h``` to get the original copy, no change.  I have tried copying the content of the file from Github via copy and paste, no change.  I'm stumped.  I fixed the other files, but I'm out of ideas to get github to quit complaining about src/MainWindow.h

Sorry. :-(

**Comment by TDeagan** [comment]
(Cross posted from the pull request (mighta shoulda been here instead.))

Aargh. Github compare says every single line of src/MainWindow.h is different. I have made no changes to src/MainWindow.h. Visual inspection of the compare of src/MainWindow.h looks identical. Git diff and git difftool locally say they're identical. I have tried git checkout upstream/master -- src/MainWindow.h to get the original copy, no change. I have tried copying the content of the file from Github via copy and paste, no change. I'm stumped. I fixed the other files, but I'm out of ideas to get github to quit complaining about src/MainWindow.h

Sorry. :-(

**Comment by kintel** [comment]
I tried to manually pick the commits, but got a bit confused:
* It looks like you only added the white icons to mainwin.cc
* The master version of mainwin.cc was refactored a bit after you wrote your code, to the merge now conflicts.

I can take a look again on Monday unless you get to it first.

Regarding newlines, this very much sounds like a broken local configuration of git, i.e. that it doesn't correctly convert between local platform newline style and repository newline style. Torsten's link might be revealing.

**Comment by TDeagan** [comment]
I executed the recommended --global command recommended in the link prior to this last commit.  It cleaned up all but the issue with MainWindow.h.  Looking deeply at it, there are 286 lines in the target and 288 in my commit (hidden since Github declares every line diff'd.)    I can see them if I look at the commit in SourceTree (which thinks they are the only diffs.)  

They are an insertion after line 101 (original) of:
```
        void initActionIcon(QAction *action, const char *darkResource, const char *lightResource);
```
a removal of line 208 original of:
```
         void on_pushButtonCompileResultClose_clicked();
```
to be replaced by:
```
        void on_toolButtonCompileResultClose_clicked();
```
and an insertion at line 242 (original) of:
```
    void helpCheatSheet();
```
So I think that somewhere along the line I picked up changes from somewhere, but I have no idea where.

I struggled to pick up on the pattern for the white icons.  I project searched for the use of the term 'white' (hoping to find all the references to the *white.png files) and only found it in mainwin.cc.  So I need to dig in and understand where else they get used (for the life of me I just couldn't find any mention in MainWindow.ui)  So if there's a pointer to where else they get used, I'm all ears :-)

At this point, perhaps the cleanest thing to do is to close this pull request, I can delete this branch altogether, compare my master to openscad/master in Github, start a new branch and do the work over again (until it comes out clean.)

Thoughts?

**Comment by TDeagan** [comment]
Okay, I finally cleared away enough of the cobwebs between my ears to understand that you were telling me that I _hadn't_ added the regular icons instead of that I hadn't added the white ones in enough places.

I have started a new branch clean, good thing, the mechanism in mainwin.cc has changed to 
```
initActionIcon(designActionExportSTL, ":/images/STL.png", ":/images/STL-white.png");
```
so now my changes will be up to date.

I also figured out why Qt Creator was forcing all my tabs to spaces, which was part of the formatting thing. (this had the fix http://doc.qt.digia.com/qtcreator-2.4/creator-indenting-code.html)

I'm closing this pull request and will submit a cleaner/better one.

**Comment by kintel** [comment]
Cool, sorry to be picky, but I hope the frustration comes with a nice feeling of achievement when you're done :)

**Comment by TDeagan** [comment]
No problem!  I am 100% in favor of maintaining standards.  I would much rather refactor/rework/start over than have people grimace when they encounter my code.  Please never hesitate to tell me something needs anything from tweaking to complete do over.  I'm already forcing myself to sit down every day and learn enough matrix math to go try and refactor my scale numbering.

I'm no stranger to frustration and am a junkie for that feeling of achievement that you mention.  This project has been a great opportunity for me (I've somehow fermented out of straight programming into mostly architecture and management professionally these days, it feels great to go work bugs and add UI features and do useful work ;-)

**Comment by MichaelAtOz** [comment]
> (I've somehow fermented out of straight programming into mostly architecture and management professionally these days, it feels great to go work bugs and add UI features and do useful work ;-)

You're not alone...

**Comment by kintel** [comment]
@TDeagan I'm currently looking into converting all icons to SVG to better deal with resolution differences. Do you happen to have the export icons in a vector format which could be exported to SVG? See #1214

**Comment by TDeagan** [comment]
I'm sure I can get them to SVG with Inkscape tracing if nothing else.  I'll
pull them together and get them to you.
--tim

**Comment by kintel** [comment]
Wait, looks like @t-paul actually redrew them in openscad :)

**Comment by TDeagan** [comment]
That is pure Meta-wonderfulness.
--t

**Pull request closed without merging**
