### PR TITLE
Accurate rotations in degrees. Fix for #517.

### PR DESCRIPTION
**Pull request by nophead**
All internal trig operations now in degrees, except dxf ellipses!
Inverse trig functions now give integral degrees when round tripped.
E.g. asin(sin(x)) == x exactly when x is an integer.

### CODE REVIEW

**Comment by kintel** [comment]
@nophead Is this ready for review, or are you still tinkering with it?

**Comment by nophead** [comment]
Yes it is ready for review. 

Getting rid of the uses of M_PI doesn't seem to make as much difference as I thought it would. I think that is because of the 2D system being integers and the grid snapping, etc.  It is still impossible to line everything up.

**Comment by thehans** [comment]
> All internal trig operations now in degrees, except dxf ellipses!
> Inverse trig functions now give integral degrees when round tripped.
> E.g. asin(sin(x)) == x exactly when x is an integer.

Nice, so can/should we update the trig inverse tests for exactness then?
https://github.com/openscad/openscad/blob/master/testdata/scad/functions/trig-tests.scad#L98-L102

**Comment by nophead** [comment]
Yes, epsilon of 0 should work. I added a new test https://github.com/openscad/openscad/blob/master/testdata/scad/functions/inv_trig_tests.scad but I will update the old one and remove mine.

**Comment by nophead** [comment]
Done via #2679.

**Pull request merged**
