### PR TITLE
Removed deprecated assign statement

### PR DESCRIPTION
**Pull request by clothbot**

### CODE REVIEW

**Comment by kintel** [comment]
The test results needs to be updated to reflect this change.

**Comment by kintel** [comment]
Yah, travis really makes things easier. Just wish they had a Windows and Mac version as well :)

**Comment by hroncok** [comment]
They actually have Mac version, but it is currently full. Stay tuned. http://docs.travis-ci.com/user/multi-os/

**Comment by t-paul** [comment]
I think I've read that Mac Travis statement already a year ago, so I guess it's not high on the prio list (or maybe just too expensive due to Apple licensing policies?).

**Pull request merged**
