### PR TITLE
Emacs SCAD mode moved to separate repository.

### PR DESCRIPTION
**Pull request by t-paul**
- Repo: https://github.com/openscad/emacs-scad-mode
- Ref: https://github.com/melpa/melpa/pull/8266

ping #4403.

### CODE REVIEW

**Comment by t-paul** [comment]
@Lenbok let me know if you would like to be added to the new separate repo for the emacs mode.

**Comment by t-paul** [comment]
Link in the [Manual](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_an_external_Editor_with_OpenSCAD) updated, if anyone has other places that should be updated, drop a note here...

**Comment by Lenbok** [comment]
Thanks @t-paul, I don't mind either way. Happy to just submit PRs to the new repo if I have changes.

**Comment by minad** [comment]
The updated package is available now on the following package repositories:

<a href="https://elpa.nongnu.org/nongnu/scad-mode.html">NonGNU ELPA</a>
<a href="https://elpa.nongnu.org/nongnu-devel/scad-mode.html">NonGNU-devel ELPA</a>
<a href="https://melpa.org/#/scad-mode">MELPA</a>
<a href="https://stable.melpa.org/#/scad-mode">MELPA Stable</a>

**Review by kintel — APPROVED** [review]

**Pull request merged**
