### PR TITLE
HIDAPI: Unify decoder

### PR DESCRIPTION
**Pull request by t-paul**
I left the framework for having different functions in, it's not really a big thing and might come in useful later.

### CODE REVIEW

**Comment by t-paul** [comment]
@MichaelAtOz could you please give that a try if the 3D-Mouse is still working? I hope with this change we can easier support the Compact Mouse too and it works for me on Linux but it's not able to open the mouse on my Windows VM.

https://circleci.com/gh/openscad/openscad/1957#artifacts

**Comment by t-paul** [comment]
Oh, another fix incoming, hopefully that makes things work on Windows 10. See https://github.com/signal11/hidapi/issues/231

**Comment by MichaelAtOz** [comment]
The first time I ran it the SM didn't work, it was working yesterday. After unplugging/replugging it worked. So I don't know whether that is related, but I've not had that problem before.
I enabled the Advanced setting, restarted. 
SM worked, I did a bit of jiggling and buttoning, exited, but couldn't find a log file.

**Comment by t-paul** [comment]
The log file should show up in the backup folder as shown in the Library Info window. E.g. on my test VM it's `c:\Users\tp\Documents\OpenSCAD\backups` (it will not create that folder though).

**Comment by MichaelAtOz** [comment]
Log hidapi.log](https://github.com/openscad/openscad/files/2903210/hidapi.log)

Note for the first run I mentioned, there was another OpenSCAD running. Does the SM control switch with the active window?

**Comment by MichaelAtOz** [comment]
p.s. Still Windows 7/64.

**Comment by t-paul** [comment]
I'm not sure how multiple instance behave. I think up to now it would have prevented multiple programs to open the same device.

That actually changes with the latest HIDAPI version and that seems to fix Windows 10, at least on my test VM. Hopefully that's not breaking other Windows versions.

The log looks pretty normal. That's good, so moving to just a single decoder seems to work so far.

@FlipSchaumal maybe give that a try too, it should fix at least case when the mouse is connected via cable.

https://circleci.com/gh/openscad/openscad/1958#artifacts

**Comment by MichaelAtOz** [comment]
Log via wireless USB dongle 
[hidapi.log](https://github.com/openscad/openscad/files/2903258/hidapi.log)

**Comment by t-paul** [comment]
Great, that looks good. So I'll merge this and we can try if that also covers the Compact variant on MacOS which was discussed on the forum.

**Comment by MichaelPFrey** [comment]
awesome. works under linux with a 3Dconnecxion Space Explorer 3D Mouse.
I will also test under Windows 10.

**Comment by MichaelAtOz** [comment]
> I think up to now it would have prevented multiple programs to open the same device. That actually changes with the latest HIDAPI version 

That new version isn't in the above snap?

I just tested, run one of above, run a 2nd, the SM moves the first even with the 2nd on-top-with-focus.

**Comment by MichaelAtOz** [comment]
> awesome. works under linux with a 3Dconnecxion Space Explorer 3D Mouse.

@MichaelPFrey 
All the buttons are customisable?

**Comment by MichaelAtOz** [comment]
> All the buttons are customisable?

Reason I ask, I note the Shift/Alt/Control which lesser SMice lack;
a. It'd be nice to allow reuse, but,
b. Regardless, I have been thinking about Axes Constraint mechanisms.
It is often that you can't prevent a rotation when you attempt a translation etc.
In other S/W Shift/Alt/Control is commonly used to constrain movement.

So, depending on whether the S/A/C keys on your SM are fixed function or customisable may affect the best approach.
I imagine, one-handed, it would be difficult to hold the SM-Shift button while doing a non-trivial movement, so perhaps a toggle mechanism would be better.
...perhaps this should be continued elsewhere...forum?

**Comment by t-paul** [comment]
Yep, I was thinking along the same line, having some way of modifier keys, both via Keyboard and maybe also via the Mouse buttons would be great. But that's food for a new feature request :-).

The snapshot ci1958 from https://github.com/openscad/openscad/pull/2820#issuecomment-467245164 has the latest code. That's the stuff merged to master now.

**Pull request merged**
