### PR TITLE
Update sample git clone command in README to use https: instead of git:.

### PR DESCRIPTION
**Pull request by aidtopia**
This is a tiny correction to the README.md.  I'm learning how to use pull requests so that I can try to contribute a bug fix or two.

### CODE REVIEW

**Comment by t-paul** [comment]
Thanks, both changes look good. Would you mind separating those? It's not a huge problem but with the change log mainly showing the PR titles, it would miss mentioning the animation fix.

**Comment by MichaelPFrey** [comment]
for reference what happens when the git protocol is used:
```
git clone git://github.com/openscad/openscad.git
Cloning into 'openscad'...
fatal: remote error: 
  The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```
https://github.blog/2021-09-01-improving-git-protocol-security-github/

**Comment by aidtopia** [comment]
Yes, of course.  I intended to create separate pull requests but I must have bungled it (newbie).  I’ll try again.

 

Thanks,

Adrian.

**Comment by t-paul** [comment]
No worries, I'm happy to help.

The reason both changes ended up in the same PR is that it was created from your `master` branch. The easiest way for separating things is to create local branches based on `master` for each change. Pushing that to your github repo and creating the PR from the branch will automatically keep things separated.

If you want to discuss how to modify your current repo, let me know. Alternatively it might also be an easy way to just clone everything again and move the changes over into that repo.

**Comment by aidtopia** [comment]
> creating the PR from the branch will automatically keep things separated.

Yep, that's what I attempted the first time.  I've figured out now.  Thanks for the advice.

I'll close this PR and create separate ones.

**Pull request closed without merging**
