### PR TITLE
DRAFT - Supporting New Language Runtimes 

### PR DESCRIPTION
**Pull request by lkarthee**
This a draft PR which provides alternative implementation for supporting language runtimes like Python. 

Still work in progress - please share your feedback. 

@gsohler @kintel @t-paul 

Goals:

1.   Support new language runtimes with minimal changes in GUI files.
2.  Package library `libopenscad` so that it can be interfaced and be able to do things like implementing a package similar to pycairo.
3.  Enable workflows native to the language - pure python scripts with venv, etc
4.  Provide apis for loading and interfacing existing scad libraries into pure language scripts.
5.  Optionally expose some apis for GUI to render and communicate with native language repls like python repl.
6.  Ability to add new language runtimes to OpenSCAD by reading libraries at runtime from path or a folder or config file.

This PR is more about changes for enabling new language runtimes and not an implementation of language runtime.

@gsohler May I include some of your work just to show case things here at draft stage. If this PR is going to be accepted, I will remove all your files.

Goals 1, 2 are near completion - you can review them.

### CODE REVIEW

**Comment by gsohler** [comment]
t-paul has written on 16. august in the mailing list:
On 16.08.23 21:26, jon wrote:
> Can you elaborate on "there's going to be some native Python
> support" please?

I'd point to http://www.guenther-sohler.net/openscad/ for that.

> Could we also add support for Modula 2 and Algol?
> I'm trying to understand where the lines are being drawn, and why.

- Language widely in demand
- Someone (else) doing the actual work (Thanks Günther!)
- Language supports "easy" integration into a C++ application

So without much analysis, my judgement would look something like:

Modula 2 - no
Algol - no
Tcl - no
Lua - probably not
Lisp/Scheme - maybe?
JavaScript - well...?

Also it's extremely unlikely *now* while the python support is
still moving towards integration.

It's going to be another option, in addition to the "normal"
SCAD. The code changes implementing the python support are
surprisingly small as it's using all the geometry infrastructure
that exists for SCAD. The bigger challenge are more the build,
deployment and release topics.

For further discussion, lets maybe create a new dedicated topic /
mail thread ;-). Or use the one from a couple of days ago, where
Sanjeev was asking for "python support for openscad".

======================
t-paul, kintel please share your latest vision with us.

Any answer is fine, i just like to know ....

**Comment by lkarthee** [comment]
@gsohler Thanks for providing [context](https://lists.openscad.org/empathy/thread/NXJ5ZHJHLGC6AM4I2O4H5XWBG6D2VWDY?hash=EF4I35QQ5J3CJCBJBOONT646JXJ5JFTD#EF4I35QQ5J3CJCBJBOONT646JXJ5JFTD). 

@t-paul @kintel Essence of the PR is Hardcoding vs Configuration.

The base idea of the PR - OpenSCAD is make things configurable and making it more open for tinkering. Why should something be hardcoded, if it is a trivial task to make it configurable.

If someone wants to implement a new language support for OpenSCAD, they should be able to do it without needing for code changes in OpenSCAD. 

I find most of the language support repos are just wrappers generating scad code to be fed through command line. I see little value in them. This might be due to lack of public api and shared library.

OpenSCAD need not officially support any language runtimes and keep its code small and nimble. All it has to do is to make it open to tinkering without people having the need to fork and send PRs to main repo. Community will do its magic and innovate. There will be more people providing language runtime through their repos instead scad file generators. 

Python may be fortunate enough to be blessed officially by OpenSCAD. There is no reason for others to be hindered for lack of access which python is getting through hard coding. It can be made configurable. 

Python Language Support PR #4736  makes changes to  openscad.cc, core, geometry and gui folders. With this PR, the changes to  openscad.cc, geometry and gui will not be needed.  Instead of hardcoding things like comment strings, file extensions, file filters in MainWindow, ScintillaEditor, TabManager and UIUtils, they are made configurable through Language Registry.  Python support can be implemented with It can get away with changes to core folders. I have not yet finished analysing changes needed in core folder when implementing a runtime. 

OpenSCAD need not worry about packaging and environment, if it can read `LanguageRuntime` information from shared libraries from a folder or path at runtime. 

Please don't view this PR as a tool to undermine or steal the work of @gsohler 's Python PR. This is just building on it. I made it a draft so that there can be more discussion on language support and features.

**Comment by kintel** [comment]
Thanks for this PR! This was discussed briefly early in the process, and now that things are getting closer it's a great time to revisit and properly design and refactor some of the mechanisms. This is, however, a pretty slow moving and careful process, so don't take it the bad way if it takes a while to review and deal with this PR :)

**Comment by pca006132** [comment]
I think if you want to support arbitrary languages, a C API would be much nicer than a C++ API. Some languages have nice C FFI but no C++ FFI. Also, if you want to test the language registry system, it might be better to move the python binding related stuff elsewhere, so you can really test things like loading DLL.

**Comment by lkarthee** [comment]
Update - PR is progressing smoother than anticipated. I will push code after some cleanup, in a week or two. I could get openscad to work (some extent) from python repl. I am wrapping up C++ api, I will work on C api after C++. 

Regards
Kartheek

**Comment by gsohler** [comment]
This sounds good!
I hope you sync to my branch often enough, my branch is constantly moving ...

**Comment by t-paul** [comment]
I would strongly recommend not trying to cover all topics in a single PR. I do support the idea in general, but if you drop that as one huge PR changing *everything* the chances of review and merge drop significantly.

Just as additional note, the CI is far from covering all environments we support. Huge changes to the build would be a concern. So far I'm not seeing that, so this is only a heads-up in case there are bigger changes brewing in that area.

**Comment by lkarthee** [comment]
Thanks @t-paul,  got your point. Idea is we can have a round of discussion about design once PR is ready. Based on consensus as to what should go in, I will push them in multiple PRs accordingly. 

@gsohler I am watching Python branch in your fork for changes.

**Comment by lkarthee** [comment]
I have a question about global $fn, $fa, $fs variables.

We are setting these variables(if declared globally) on leaf nodes when they are instaniated from AST.

These exist in BuiltinContext as well although not used like below. I have tried to set them in BuiltinContext and they have effect of being when instantiated globally. Is this approach acceptable or am I missing some drawback with this approach ? 

```c

void MainWindow::setRenderVariables(ContextHandle<BuiltinContext>& context)
{
  context->set_variable("$preview", Value(this->is_preview));
  context->set_variable("$t", Value(this->animateWidget->getAnim_tval()));
  context->set_variable("$fn", Value(64)); // just an example - so no worries about hardcoding. 
```

Regards
Kartheek

**Comment by t-paul** [comment]
Please elaborate a bit on what you are trying to achieve.

For OpenSCAD language, it would not be acceptable to globally change the behavior as that obviously would impact potentially all designs in an unexpected way.

For other languages, there might be the need for a different solution as the dynamic scoping behavior of `$` variables is not something other languages provide. Maybe a start could be having a global resolution setting for `$fa`/`$fs` and no global `$fn` at all.

**Comment by lkarthee** [comment]
It's for other languages. I am exploring if they can be set through BuiltinContext as it is being created every time something is rendered or previewed ?

I could set debug modifiers for nodes by setting them on ModuleInstantiation. For example I could create a cube node and call setDebug("#") on it.

**Comment by lkarthee** [comment]
I have few of questions:
- Boolean ops like union,etc work on same type primitives should be either 2D or 3D. Should the public api only allow valid primitives as we have type info? 
- Transforms like offset, linear_extrude, rotate_extrude which work only on 2D nodes. 
- Projection works only on 3D node. 
- Rest all transforms or ops work on both 3d and 2d nodes. Is this correct assumption? 

Regards
Kartheek

**Comment by lkarthee** [comment]
Hi all - i have a mac build working. Most of apis are fluent so you can method chain them for ergonomics. I have used [nanobind](https://nanobind.readthedocs.io/en/latest/) to generate binding as it very easy and fast.

### Environment

First we need to environment variable `OPENSCAD_HOME`
```
export OPENSCAD_HOME=~/erlang-ws/github-ws/latest/openscad/build/OpenSCAD.app/Contents/MacOS/
```

### Context

`OpenSCADContext` can be thought of as an abstraction of file which opened in OpenSCAD editor. All the actions are appended to the context. 

`OpenSCADContext ` is a container for environment variables like `$fn`, `$fs`, `$fa`.  All exports like png, stl, csg are generated from context. 


Context can be created by passing a name. 
```python
ctx = openscadpy.context("red-green")
```
Context can be initialised from a scad file. 
```python
ctx = openscadpy.context_from_file("myexisting.scad")
```
Special variables `$fn`, `$fs`, `$fa` can be set on context which will be passed on to the primitives created. 
```python
ctx.set_fn(32)
# or
ctx.set_fa(10).set_fs(0.5)
```
Example of special variables in action.
```python
>>> green_sphere = ctx.sphere(10).color("green")
>>> green_sphere.node
sphere($fn = 0, $fa = 12, $fs = 2, r = 10)
>>> ctx.set_fa(10).set_fs(1)
<openscadpy.Context object at 0x102761bf0>
>>> green_sphere = ctx.sphere(10).color("green")
>>> green_sphere.node
sphere($fn = 0, $fa = 10, $fs = 1, r = 10) # $fa and $fs are changed as per ctx.set_fa(10).set_fs(1)
```

`use <filename>` can be done by using `ctx.use_file(filename)`.

### Primitives

Primitives are two types Primitive2D and Primitive3D. They are required to eliminate the possibility of mixing them in boolean ops.

A primitive can be created from `Context`.
```python
sphere = ctx.sphere(10)
```
All the operators are exposed as methods of primitive and can be chained.
```python
green_sphere = ctx.sphere(10).color("green")
```

Even though they are created from context, they are not auto added to context. We have to append them as required.

```python
cube  = context.cube(10)
green_sphere = context.sphere(10).difference(cube)
ctx.add(green_sphere)
```

### Sample Programs

``` python
import openscadpy
# needed for initialising some globals in openscad. may be this can be hidden from user by using an cogntextmanager
openscadpy.init_globals() # will segfault if OPENSCAD_HOME is not set in env - will handle this little later.
ctx = openscadpy.context("hello")
red_cube = ctx.cube(10).color("red")
green_sphere = ctx.sphere(10).color("green")
red_cube.difference(green_sphere)
ctx.append(red_cube)
ctx.export_file("red-green.png")
ctx.export_file("red-green.csg")
ctx.export_file("red-green.stl")
```

**Comment by gsohler** [comment]
Hi Ikarthee,

Interesting approach.  I dont know nanobind, but probably i will have a
look inside.

It appears that you started with a different python -openscad flavor and I
am confident that it's working.
The code is beautiful and it's very pythonic!
However it's definitely longer than my code. Pro is: you can probably make
use of more python features as it's more abstract.
Con: i think it's not so readable, its longer code

The intent when creating my pyopenscad clone was to be as identical as
openscad, so users  would not need any additional documentation.
Writing less code to achieve more
shortest code in my pyopenscad is
cube()

6 characters only will display basic code

But I am happy that my work has so much inspiration for others to base on
my work :)

Today I will probably continue on my own SDF mesher(it does not use
marching cubes, but it starts on one point of the surface and grows until
all surface is covered.

**Comment by lkarthee** [comment]
Thank you @gsohler for your kind words. Definitely your work is base and everything is derivative. It is an inspiration for me.

I have no intent of implementing Python bindings. I used nanobind to test the public api i have exposed. Nanobind comes with an advantage of abstracting out low level details.

Even though [post](https://github.com/openscad/openscad/pull/4758#issuecomment-1786500218) appears to dominated by python syntax, it's just exposing the public api. I can test the api only be consuming it.

I think the concise flavour version which you have implemented can wrap c++ public api (please share your thoughts). It will be easy to maintain as public apis will abstract out.

One thing which is missing from public api is `**kwargs` api methods. I will add them shortly which will be more suitable for concise python bindings.

**Comment by pca006132** [comment]
We use nanobind for python binding of manifold as well. We wrote some simple casters that can handle ordinary python lists for vec3, in addition to numpy arrays. If you are interested, feel free to look at our code and discussion in https://github.com/elalish/manifold/pull/537

**Comment by pca006132** [comment]
@gsohler are you planning to make sdf faster? We had some discussions over in manifold about making sdf faster, but it is a hard problem unless you have some assumption about the sdf other than it has to be deterministic (e.g. continuous, or behaves like distance function, which may not hold in general)

**Comment by gsohler** [comment]
Hi Chun Kit LAM

I like the marching cube algorithm a lot and it's definitely very robust!
Only issue with it is that it runs in O(n^3) time and running time will
increase a lot when making a smaller/finer mesh.

This is why I try to find another approach and walking around the surface
suggests to me that it will do so in O(n^2) time only.
Yes I am aware that the algorithm will have issues to find more separated
objects, still I want to continue.

To work on this approach I have found some favorite algorithms: one of them
is a 3D hashmap algorithm where 3d coordinate is the index, and it can find
nearby points  in
N(log) time . I need this to find out if a surface edge is approaching from
the opposite side.
The other algorithm I am using is to re-adjust the normal vector at a given
point by only calling the SDF function 4 times.

All that is just done for my personal challenge and am curious to find out
if my approach will be finally working.

**Comment by pca006132** [comment]
I am actually quite interested in figuring out the set of primitives that you can provide to the user which can make the resulting function *nice* but without sacrificing too much expressiveness. But I probably cannot work on it soon... Good luck with your experiment!

**Comment by lkarthee** [comment]
@kintel @t-paul  Any feedback with api on high level. Can I proceed with this PR ? 

4 ways to proceed: 
 - you like the way this is progressing, I will split the work till now into small PRs and start merging individually.
 - you will review this single pr and merge this after some cleanup on my end.
 - you have some feedback, which needs to be addressed.
 - don't like the direction, abandon pr
 
Two new asset exports need to be added to this effort for this to come to logical conclusion. 
 - export geometry as three.js buffers
 - export geometry as glTF

This will unlock OpenSCAD potential for tinkering and enable new workflows:
- user will have choice of multiple languages in OpenSCAD app.
- It can be used as a backend / backbone for new workflows like Jupyter notebook, Elixir livebook, etc.
- new export formats like three.js buffers and glTF will enable the output to be rendered in web browsers.

For example, [Three CADViewer](https://github.com/bernhard-42/three-cad-viewer) can used to render output in Jupyter notebooks. [Model Viewer](https://modelviewer.dev/) can be used to render glTF output in Jupyter as well. 

@pca006132 @gsohler do share your views on this.

**Comment by bandtank** [comment]
I run a business that pushes schools to adopt tools like openscad. I have been teaching openscad for a while and it has been a hit with students of all ages. Regardless of which languages are selected for integration, I will continue to use openscad because it is an excellent tool. With that said, nearly all of the schools and students I support are teaching Python, which is why I have been using the fork by @gsohler instead of the official version. I was leery at first, but it has been working for ~45 schools (~2,000 students). I've had a handful of kids ask me about nodejs support, but the rest ask about Python.

CAD isn't supposed to be a programming environment as much as it is supposed to be a component and assembly design environment. The programming language plays a supporting role, which means limiting it to a few options to reduce integration complexity will add the most value with the least amount of effort and risk. Picking a ubiquitous language like Python, which is very easy to learn and is being taught to elementary school students, makes the most sense for market capture. It's always nice to have flexibility and options, so I understand the desire to build an abstraction layer, but supporting an arbitrary number of languages is not going to attract enough users to make the effort or risk worthwhile.

I don't understand the argument about safe scripting. My career has been spent in tools like AudCAD, which use LISP. LISP can modify things beyond AutoCAD, but it has never been an issue. People should be expected to know how to operate their computers, which includes executing scripts from various sources. Another example is VBA/Python in Microsoft Office, which warns you a few times and then let's you do whatever you'd like. On that note, I would change openscad to use Python as the native language and be done with it.

Regardless, thanks for the effort and I look forward to an official version that supports more languages. It's all a win no matter what.

**Comment by jordanbrown0** [comment]
If you think of OpenSCAD as a programming environment (like Python) then safety doesn't matter much.  If you think of it as a document environment (like Word, Excel, et cetera) then it matters a lot.  Even experienced users won't be able to practically analyze non-trivial OpenSCAD models for maliciousness, and we'd like to allow for customizer-only users who never look at the program per se.  You should be able to safely download a model and customize it and create STLs.

I don't have a lot of experience with VBA, but I believe that the user has to enable it for each document that they open... and when not enabled, it can't run.  Normal Python as the native language would have no such protection.

**Comment by pca006132** [comment]
Also, VBA is a common security problem for offices...

**Comment by lkarthee** [comment]
I know everyone is volunteering and I appreciate your effort you put in as maintainers. 

I was not expecting the PR to be merged. Instead of just talk talk talk - i went a step further and explained and implemented what I was telling. More of show and tell PR. 

I was waiting for feedback on whether maintainers are in agreement as to: 
- generating shared library 
- exposing public api 
- example python bindings

If this PR goes through Python support has to refactor on public api based on this PR. It's not the other way around. 

I did not get replies(not review) to basic design questions/decisions as to what next - it's little difficult for me to split the same PR and expect maintainers to respond in the future. It's just deferring the problem to future.  I am not expecting any ETAs from maintainers - I am closing and moving on ... 

Thank you @kintel @t-paul . 

Regards
Kartheek

**Comment by lkarthee** [comment]
@pca006132 patience is  a virtue , but communication is the key. May be your choice of words are wrong - calling me frustrated or talking about my frustration might not help anyone. https://github.com/openscad/openscad/pull/4758#issuecomment-1831878534 what part of it communicates I am frustrated or my frustration. I am not frustrated at all.  I have been polite, patient and respectful enough. I have respectfully closed the PR and explained it to everyone the reason why I am doing. The reason is simple - lack of communication from maintainers and I want to close and move on. 

> there are some other works going on right now (e.g. fix PolySet) that we want to finish and make a release, something everyone have been waiting for a long time...

No one communicated that they have things fix first like poly set or others, till then others are deprioritised. There is no roadmap or milestones which indicates things or shows priorities. SCAD language has its short comings and it is a CODE CAD tool. Interface to CAD is through CODE and not GUI. I am failing to understand why addressing CODE related issues are a low priority compared to others. Python PR itself is not merged for almost 1 year. It's a status quo when it comes to CODE. Hopefully this will change.

Even today, people want to defer discussion to split PRs in future. How does this help - same PR split into things and then people revert after  long time (does this make things any better). When people don't agree or disagree on merits of proposal what difference does it make if I split or not. If I hang around long time gaining trust and fixing small bugs, the proposal's  technical merits will remain unchanged ?  it will still be same proposal which will be addressed on merits.

> My recommendation for future contribution (not just to OpenSCAD but for any project) would be to start with simpler bug fixes, gain your trust, and then move on to larger and more abstract refactoring, as suggested by others as well.

Let's say, I gain trust sending small bug fixes, then I send a mediocre proposal. Will it be dealt differently?  Will socialising be given more prominence than merit in a proposal ? I don't think so. 

> From my experience it can be hard to get this kind of abstraction only refactor to merge, unless you demonstrate that this abstraction is consumed somewhere, e.g. by the experimental Python binding or other language bindings. For example, for the PR that adds C API for manifold, they also added a out-of-tree binding for OCaml, which demonstrates that the abstraction is ready for use instead of just a demo.

FYI  -  https://github.com/openscad/openscad/pull/4758#issuecomment-1786500218 . If you look at it I have added sample python bindings using nanobind and how it can be consumed. Let's take an example of shared library packaging and public api. I have shown and explained how it unlocks use cases like server side stl generation and embedding openscad runtime in other applications(like how cairo is embedded). Apart from OpenSCAD app or tricky command line - it will add a new additional interface through api using shared library. 

I wish people read what I have previously posted.

> but the size makes it hard for maintainers to review, 

Is it hard to communicate through simple things like reply or share thoughts on a broad level of discussions or topics like shared library PR can go throught or public api is needed or not. 

When I asked what to do with the PR, I did not receive reply. I waited for a month and decided to close and move on.  I have been clear communicating things from the beginning. 

Instead of blaming me, maybe the communication should be more open and straight forward. Why is it that issue being diverted on to the size of PR.

After waiting for 1 month without any replies and closing the PR after lack of communication. I am being given below reasons (for non communication ?):
- size of PR (which is irrelevant, I have been saying this is a draft and more for discussion)
- gaining trust and attempting small bug fixes (if it is a rule here, mention it somewhere)
- it might become burden to existing maintainers (if help is needed, people should ask)
- code cleanliness (code reviews can address this, I am open for it. For it first we have to reach review stage)

If anyone has any technical discussion about my proposal or code please revert on it. If people have to hang around and socialise for an year or two and send a proposal - it is quite unreasonable.

I am not entitled to anything, on the other hand don't blame me for random things.

Either things are really slow or people don't communicate.

**Comment by pca006132** [comment]
Well I am not blaming you for anything, I just want to point out why this does not get as much attention. Maybe I should not have commented in the first place. Sorry for making you feel offended.

**Comment by kintel** [comment]
@lkarthee I understand that you probably lost motivation on this one, but just a heads-up that the Python integration with OpenSCAD is starting to make it into master just now, see e.g. #5694 

Not much have changed in terms of spare time available, but right now there are some eyes on this, so this could be a good time to for landing any work refactoring/cleaning up the language runtime interface layer, especially if it's combined with an intent to add other languages.

**Pull request closed without merging**
