### PR TITLE
Don't return empty group for "if" statement with failing condition and no "else".

### LINKED ISSUE #3452: Conditional geometry should be completely removed from render tree
Reported via [forum post](http://forum.openscad.org/The-behaviour-if-intersection-has-changed-td30152.html)
```
intersection() {
    cube();
   
    if(false)
        sphere();
}
```
The `if()` should take out the whole subtree, so the result is the cube, not the empty intersection between a cube and an empty object.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/93269375-conditional-geometry-should-be-completely-removed-from-render-tree?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F52063&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by thehans**
fixes #3452

### CODE REVIEW

**Comment by jordanbrown0** [comment]
Does a failing "if" count as a child?

```
module count() {
    echo($children);
}

count() {
    if (false) {
        cube();
    }
}
```

**Comment by thehans** [comment]
Yes it does. 

`$children` is currently based on AST nodes, not CSG tree, because it needs to be determined before/during the expression evaluation stage (ie it needs to be known at the time that `if` conditions will be evaluated, so it can't really depend on results of those conditions).  Also see https://github.com/openscad/openscad/issues/3143

**Review by t-paul — APPROVED** [review]

**Comment by nophead** [comment]
What about the true if case when the child is not geometry, i.e. echo?

**Comment by thehans** [comment]
An `if` with true conditional will group any and all children as usual.  If the children don't happen to contain geometry then the result will be the empty set due to implicit union.

If you think groups without geometry shouldn't count as empty geometry, then you're basically asking for the `lazy-union` feature.

**Comment by nophead** [comment]
Does echo return a special "no geometry" node? If so, can it be propagated upwards so that `if(true) echo()` behaves the same as `echo()` and a module that wraps `echo()` behaves like `echo()` in an intersection?

I don't think it makes sense that `echo()` and `if(false) echo()` don't create an empty group but `if(true) echo()` does.

**Comment by jordanbrown0** [comment]
I'm very nervous about deviating from the "one module invocation, one geometry node" rule, but I agree that once you **do** deviate from it for `echo()` and `if(false) ...`, you should also deviate from it for `if(true)echo();` and similar.  I suspect this also extends to `for(...)echo` and modules containing no "real" geometry.

Note that constructs that *do* contain real geometry, but that result in emptiness - intersections of non-overlapping objects, in particular - should continue to be represented as "real" geometry nodes.

**Comment by thehans** [comment]
So far, group nodes have basically functioned identically to union.  
But it sounds like what people are asking for is that any group with no geometry nodes inside should be treated as a special case and removed from the render tree instead.  
This might be feasible to implement without full lazy union support, but I also worry that this could open another can of worms of unintended consequences and regressions.  Especially this late in a release cycle.

**Pull request merged**
