### PR TITLE
Added new test and fixes for trigonometric functions

### PR DESCRIPTION
**Pull request by thehans**

### CODE REVIEW

**Comment by thehans** [comment]
This addresses #2195 and a bunch of similar/related issues that were discovered as the test was being written.

**Comment by nophead** [comment]
1/0 gives inf and -1/0 gives -inf. I think tan(90) and tan(-90) should do the same rather than nan.

**Comment by doug-moen** [comment]
+1 to what @nophead said. tan(90) should be inf so that cotangent calculations do not break. See my comment in  #2195 for more details.

**Comment by kintel** [comment]
Looks good to me from a code perspective, but I'm not a heavy user of these functions.
I'll merge unless someone raises concerns.

**Pull request merged**
