### PR TITLE
Add SpaceMouse Compact (256f:c635).

### PR DESCRIPTION
**Pull request by t-paul**

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
Just a small concern for long therm maintenance:
The Space Mouse Compact does not look like it has buttons.
Why add a "real" button decode? A dummy button decode could prevent confusion.

**Comment by MichaelPFrey** [comment]
maybe bad - the compact mice has two buttons.

**Comment by MichaelAtOz** [comment]
Anyone know if these have been tested/work?
spacemouse

**Comment by t-paul** [comment]
I have not seen any reports about those.

**Comment by robnee** [comment]
I have a SpaceMouse Wireless (shows up as 256f:c652) but it won't work with OpenScad 2021.01.  It just zooms in an out but nothing else.  I am confused about "stopping the driver".  Does this mean uninstall it?  Won't that break the other programs where it does work?  Is it supposed to remember the axis settings?  How do you save the axis settings?

**Comment by t-paul** [comment]
What OS? Which Driver you refer to? OpenSCAD can't support the official driver as the license 3Dconnexion uses is incompatible with open source software.

Maybe create a new ticket and also attach the output of "Help -> Library Info".

**Comment by robnee** [comment]
I see.  Thank you for the response.  I am on Win 10.  Using task manager I stopped all 5 3dConnexion processes and now the SpaceMouse does not even behave like a scroll wheel like it normally does in unsupported applications.  Is there a better way to "stop the driver"?  

In the Axes preferences HIDAPI is checked.  All the axes are None.  When I set them to something is there a way to save them?  Every time I open openSCAD the Axes settings are lost.  I see this in the hidapi.log

0: HidApiInputDriver::open()
0: Enumerating HID devices...
32: D: 24f0:0140 | path = \\?\hid#vid_24f0&pid_0140&mi_00#8&d66cf6b&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}\kbd, serial = <null>, manufacturer = Metadot - Das Keyboard, product = Keyboard
32: D: 256f:c652 | path = \\?\hid#vid_256f&pid_c652&mi_02#7&8ec9099&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, serial = <null>, manufacturer = 3Dconnexion, product = 3Dconnexion Universal Receiver
32: P: 256f:c652 | \\?\hid#vid_256f&pid_c652&mi_02#7&8ec9099&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
32: R: 256f:c652 | <null>
33: ?: -1
33: E: The supplied user buffer is not valid for the requested operation.
33: D: 256f:c652 | path = \\?\hid#vid_256f&pid_c652&mi_00&col01#7&15004216&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}, serial = <null>, manufacturer = 3Dconnexion, product = 3Dconnexion Universal Receiver
33: P: 256f:c652 | \\?\hid#vid_256f&pid_c652&mi_00&col01#7&15004216&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030}
33: R: 256f:c652 | <null>
134: ?: 0
134: Done enumerating (status = ok).
134: HidApiInputDriver::open(): HidApiInputDriver (256f:c652 - 3Dconnexion Universal Receiver)

I'm happy to open a ticket but don't want to unnecessarily.

**Comment by t-paul** [comment]
I have no advise about the 3DConnexion driver.

Axes setting should be saved automatically, if that does not work, that's a bug.

**Comment by robnee** [comment]
OK.  Thank you.  I appreciate your help and your work on this project.  I will try to pull together as much data as I can first before filing a report.

**Pull request merged**
