### PR TITLE
fix erroneous warning for root modifier 

### PR DESCRIPTION
**Pull request by leonplust**
fix for issue https://github.com/openscad/openscad/issues/2923

### CODE REVIEW

**Comment by t-paul** [comment]
I'm getting a warning for just a single root modifier like in `!cube();`.

**Comment by leonplust** [comment]
Sorry for making a mass in the commits section, I accidentally committed the other issue to this branch

**Comment by kintel** [comment]
I don't think this actually solved the problem. This still gives a warning:
```
module Test() {
    !cube();
}

Test();
Test();
```

**Comment by kintel** [comment]
Will rewrite

**Pull request closed without merging**
