### PR TITLE
Implement quiet mode

### PR DESCRIPTION
**Pull request by ArchimedesPi**
Implements suggestion in #505. Doesn't print anything except error messages when triggered.
The global quiet state is held in `OpenSCAD::quiet`, similar to how debug is handled.
Quiet mode is triggered by **`-q`** or **`--quiet`**.

### CODE REVIEW

**Comment by hroncok** [comment]
Nice. Does it print warnings?

**Comment by ArchimedesPi** [comment]
@hroncok Nope. Should it?
The big problem with this though, is that since we don't have seperate warning, error, and info `PRINT` macros, when a multiline ERROR or WARNING gets printed, with ERROR or WARNING prepended on only one line, only the line starting with ERROR or WARNING gets printed.
I've heard some talk about reimplementing *all* the logging stuff with boost::log, which could solve a bunch of these problems.

**Comment by hroncok** [comment]
It would be really cool to have various verbosity levels with boost::log. I
use similar mechanism with Python logging and it is quite useful.

**Comment by ArchimedesPi** [comment]
Then you could add an optional parameter to --quiet, like --quiet=WARNING.
That would mean hooking in the debug stuff though, for optimal ease-of-use.

**Comment by MichaelAtOz** [comment]
`-q` & `--quiet` needs to be added to `-h` help text. I check against 2017.04.05.

**Pull request merged**
