### PR TITLE
Update progress as we process 2D items

### PR DESCRIPTION
**Pull request by DrCodeWizzard**
Update progress bar as we process 2D items. 
To test open openscad and run the following:
for(o = [0:10:10000]){
translate([o,0])
circle(r=10, center=true);
}

### CODE REVIEW

**Comment by MichaelAtOz** [comment]
Also eventually needs testing with multi-thread enabled.

**Comment by DrCodeWizzard** [comment]
yeah I have not tested it with multithreading enabled (not sure how to flip that switch right now). I would need to see how the progress update is implemented to see what changes would need to be made to make the progress consistent and race condition free...

**Comment by MichaelAtOz** [comment]
Well the 3D one, same mechanism,  works multi-threaded (seems to), I just left the above as a reminder for final checking.

**Comment by DrCodeWizzard** [comment]
ok :-) What's the magic switch for a test?

**Pull request merged**
