### PR TITLE
Major Coding Style Update

### PR DESCRIPTION
**Pull request by kintel**
Initiated by @justbuchanan 

### try it out!

(Save your current work first, then...) Run `./scripts/beautify.sh --all` to reformat everything, then `git diff` to see what changes were made. If you see changes that you dislike, there may be config options (linked above) to change them.

### usage

Initially, you'll want to reformat the whole repository. This is easy to do, but has some downsides:
* lots of extra diffs with open pull requests
  * these are reduced if you run the formatter on each PR branch before attempting to merge, but the extra diffs still make it harder for git to figure out what happened in some situations.
* Sometimes the auto-formatted version of the code is worse than the original.
  * Code comments may need to be re-wrapped - sometimes the auto-formatter wrapping does weird things
  * On occasion, you may need to add `// clang-format off` and `// clang-format on` comments before and after, respectively, some code pieces that you'd prefer manual formatting for.

After the initial formatting, you only need to re-run the formatter on files as they change. In practice, this means encouraging pull-request submitters to run the formatting script and/or running it before merging the pull requests.

Here's a diff showing an initial formatting run on the whole repo. There are a lot of diffs, but most of them are just whitespace. https://github.com/justbuchanan/openscad/commit/02d505ccbad72771603a37c6f15264592e184fd9.

TODO
- [x] Deal with any source code not currently included in `beautify.sh`
- [x] Add note to contributing guide
- [x] Allow running from within the `scripts` dir. Needs to `cd` to the root directory of the repo before running
- [x] Commit minimal patch using a partial `.uncrustify.cfg`
- [x] Gradually patch until we can use a full `.uncrustify.cfg`
- [x] Decide where to perform the big tab -> spaces update
- [x] Consider switching to clang-format once the codebase is cleaner -> this is probably better done as a separate PR as clang-format implements a subset of uncrustify
- [x] Wait for #2243 to be merged
- [ ] Write email to mailing list and transition notes

Notes/questions (to put in email/transition notes):
* README first: doc/hacking.md
* I have an existing PR open. What do I do? (or I have local patches to OpenSCAD, how do I survive all the conflicts?)
   ** Merge with the last pre-coding-style commit (`pre-coding-style` tag): `git fetch origin pre-coding-style`, `git merge origin pre-coding-style`
   ** Install the correct version of uncrustify
   ** Run `./scripts/beautify.sh --all`
   ** Commit your beautified code
   ** Merge with master: `git fetch origin`, `git merge origin/master`
   ** Fix any conflicts
   ** Push to update your PR: `git push`

### CODE REVIEW

**Comment by kintel** [comment]
To make the script runnable from anywhere, we could do smth. like `SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"` and go from there.

**Comment by kintel** [comment]
@t-paul If the above goes as planned, I'll try to finally switch to space indenting. Any last wishes?

**Comment by t-paul** [comment]
Nope, no extra wishes at this time. I'll just tag along :-)

**Comment by kintel** [comment]
@justbuchanan Since you started all this :) ..any last comments/wishes/ideas before I move forward with this?

**Comment by justbuchanan** [comment]
Looks great!

Just one minor note - I pulled the latest and ran the formatter again and I see a few changes still: https://github.com/justbuchanan/openscad/commit/c91afac5e28886efa1dfaad0195bdbf21275f08b. It's likely we're just running different versions of uncrustify (I have 0.66), so doesn't really matter.

Anyways, looks good to me.

**Comment by kintel** [comment]
oh, 0.66 is out. I'll give that a spin.
Good point though, that we need to specify a golden version as uncrustify seems to change rapidly

**Comment by kintel** [comment]
Humm, looks like 0.66 has some issue with `->` operators: https://github.com/uncrustify/uncrustify/issues/1449

**Comment by justbuchanan** [comment]
Yeah I noticed some weirdness with the `->` operator when I ran it. It may be best to stick with the version you have for now as it seems to have less issues. In general though, you won't have much control over what version of `uncrustify` individual contributors run on their PRs, so you can either re-run a specific version of the formatter before merging or accept that there will be occasional inconsistencies.

From my experience using these tools (clang-format mostly in my case), there are always inconsistencies between versions. If you format everything with one version, then again with another, there will almost always be diffs. The good news is that after the initial full-codebase reformat, most re-formatting will happen only on the files changed in a given PR, which keeps the inconsistencies to a minimum.

**Comment by kintel** [comment]
They fixed the bug - will give it a little time to see if it results in a new release.

**Comment by donbright** [comment]
i'm for trying it....  if it can work as well as go-lang format.

**Comment by kintel** [comment]
Doesn't look like `uncrustify` will get another release in a while. I'll probably add some docs about that before merging this..

**Comment by justbuchanan** [comment]
One minor suggestion on the instructions listed at the bottom of the first post. Instead of running `./scripts/beautify.sh --all`, I'd recommend using the default mode (no `--all`), which only touches files that difffer from origin/master. And in that case, it would be best to do the `git fetch` before running the formatter.

**Comment by kintel** [comment]
@justbuchanan The instructions are meant for people who have patches predating the coding style update. In this case they cannot merge with master since every line of code will cause a conflict. The instructions are there to give them a way of resolving that, which is to beautify their entire branch before merging.

If you have a cleaner way of achieving the same, I'd be interested. ..but please test the method on an existing PR, as my first attempt didn't survive that initial test :)

**Comment by justbuchanan** [comment]
Makes sense. My suggestion was to still run the formatter before attempting to merge with the master branch, but to only format files that have been changed on that branch. Because `uncrustify` changes with each release and people are likely to have different versions of it installed, running it on *all* files is likely to give extra diffs that will have to be resolved.

**Comment by kintel** [comment]
I agree with that general sentiment. I should clarify that this is recommended in https://github.com/openscad/openscad/blob/master/doc/hacking.md

**Comment by kintel** [comment]
@justbuchanan Updated in master: https://github.com/openscad/openscad/blob/master/doc/hacking.md

**Comment by t-paul** [comment]
Superseded by #4095.

**Pull request closed without merging**
