### PR TITLE
Use left recursion for "input" in parser

### PR DESCRIPTION
**Pull request by thehans**
This is a first pass at addressing issue #2342 by changing `input` to use left recursion as recommended by bison docs: https://www.gnu.org/software/bison/manual/html_node/Recursion.html#Recursion 

This change seems to allow openscad to get past the compile stage for very large scad files without a "memory exhausted" error from bison.  However it seems the issue is passed further down the chain because (with eg. 40k lines input, 20k elements) it now segfaults in `CSGTreeNormalizer::normalizePass` from I'm guessing too much recursion, at a stack depth of about 18,000 
https://github.com/thehans/openscad/blob/issue2342/src/CSGTreeNormalizer.cc#L100

Not sure if there's some better way to handle `normalizePass` that would allow it to support higher element counts, should it be recurring this much for a flat file input of many translated cubes?

### CODE REVIEW

**Comment by kintel** [comment]
The CSG tree is a binary tree, built using that recursive process. There is room for optimization, but that particular process can be tricky to get right. We have decent test coverage for that though, as I’ve broken that code multiple times already.

**Comment by thehans** [comment]
I did some work to rewrite `CSGTreeNormalizer::normalizePass` to be iterative, which was pretty tricky and the resulting code is not as elegant as I would like.  

I also found that some stack limits would be reached in `CSGProducts::import` and rewrote that as iterative; that one at least is straightforward.  

I am attaching some of the test scad files based on a 500,000 line scad example from issue #2342 , truncated at various lengths for testing:
[ManyCubes_scad.zip](https://github.com/openscad/openscad/files/1853528/ManyCubes_scad.zip)
In these examples there is one element for every 2 lines of .scad code.
I hesitate to add these as actual tests just due to how large of a commit it would be.

Before changes, OpenSCAD would fail to preview just 40,000 lines.  Now it seems to handle up to around 400,000 before things get iffy.   Testing this high requires increasing the default csg element limit in settings.   Previewing around 400kloc a segfault occurs due to stack limits in the way that shared_ptr gets reset recursively in the tree, coming from the code that resets the rootnode in `CSGTreeNormalizer::normalize`
```C++
this->rootnode.reset();
```

Another test I tried was creating large number of elements in a loop.  This does not test stress the parser in the same way, but the normalization issues are the same.  This makes 100k elements for preview testing:
```
xcount = 100;
ycount = 100;
zcount = 10;
totalcount = xcount*ycount*zcount;
echo("total elements:", totalcount);
for(x=[1:xcount],y=[1:ycount],z=[1:zcount]) 
  translate([x,y,z]) cube(0.5);
```

I feel like 100k elements is a fair goal to be capable of displaying, since that's the default limit in preferences/settings anyways.

**Comment by MichaelPFrey** [comment]
just an idea for a parser test case: you could write a phyton script that generates a SCAD file.

**Comment by kintel** [comment]
We already do generate test files, although just using simple substitution in cmake, but it's conceptually no different: https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L1113

**Comment by oysteinkrog** [comment]
I think I ran into this problem in #1991. My code is a complex model (parametric 3d printer), so a much more realistic codebase than #2342. I can test windows binaries if needed.

**Comment by thehans** [comment]
@Kintel I finally added a parser test case generated from python.  Do you think this is ok to merge now?

**Comment by kintel** [comment]
Thanks - I'll try to review this soon. The unrolling of the recursive algorithm scares me a bit, but I think we can mostly trust the tests.

**Pull request merged**
