### PR TITLE
macOS: Support cross compilation and universal builds

### PR DESCRIPTION
**Pull request by kintel**
This adds support for cross-compilation and universal builds of macOS dependencies and binaries (#4036):

Build deps for arm64 on any platform: `./scripts/macosx-build-dependencies.sh -a`
Build deps for x86_64 on any platform: `./scripts/macosx-build-dependencies.sh -x`
Build universal deps: `./scripts/macosx-build-dependencies.sh -a -x`

Build OpenSCAD for arm64 on any platform:
```
mkdir -p build
cd build
cmake -DCMAKE_OSX_ARCHITECTURES=$ARCHS ..
make
```

`CMAKE_OSX_ARCHITECTURES` can be omitted for a native build. Providing `x86_64` or `arm64` (cross-) builds for a specific architecture, and providing `x86_64;arm64` will yield a universal binary.

Tested on:
* [x] Native arm64 -> arm64
* [x] Native arm64 -> x86_64
* [x] Native arm64 -> universal
* [x] Rosetta x86_64 -> arm64
* [x] Rosetta x86_64 -> x86-64
* [x] Rosetta x86_64 -> universal
* [x] Native x86_64 -> x86_64
* [x] Native x86_64 -> arm64
* [x] Native x86_64 -> universal
* [x] CircleCI: Native x86_64 -> x86_64

### CODE REVIEW

**Comment by kintel** [comment]
This is a bit odd: I managed to get a macOS 12.1 VM running using UTM. I downloaded the universal OpenSCAD binary, created a `cube.scad` file on my desktop, and opened it in OpenSCAD. I got asked 4 times if I wanted to allow access to my Desktop folder. I answered "Don't allow" all 4 times, after which the file got opened in OpenSCAD after all :/

**Comment by tcurdt** [comment]
> This is a bit odd: I managed to get a macOS 12.1 VM running using UTM. I downloaded the universal OpenSCAD binary, created a `cube.scad` file on my desktop, and opened it in OpenSCAD. I got asked 4 times if I wanted to allow access to my Desktop folder. I answered "Don't allow" all 4 times, after which the file got opened in OpenSCAD after all :/

The native opening dialog should have given you access to the file. That is kind of expected. To me the real question is why there were 4 tries to access the Desktop folder.

**Comment by kintel** [comment]
I don't quite understand how this mechanism works.. Are you saying that if a user explicitly selects a file in a native dialoge, it will always give access, but if the app tries to access other files in the same folder, it will need to ask for permission?

**Comment by tcurdt** [comment]
> I don't quite understand how this mechanism works.. Are you saying that if a user explicitly selects a file in a native dialog, it will always give access, but if the app tries to access other files in the same folder, it will need to ask for permission?

That's correct - there might be a distinction of sandboxed and non-sandboxed apps though. The file dialog illustrates user intend and as such should grant a piercing of the security sandbox.

> Btw., in the same VM I can reproduce the repeating dialog problem too: If I answer "OK" to the Desktop access question, it still asks the same question again. And every time I open a new file, it keeps asking twice.
System Preferences -> Security & Privacy -> Privacy correctly shows that OpenSCAD has access to the Desktop.

I don't understand why OpenSCAD should have access to the Desktop or even the Downloads folder. I am not aware of any automation in OpenSCAD that writes files without user intend. Writing an STL also asks for the location - and by that has a user intend giving the correct permission.

I am wondering if this is due to these folder locations https://github.com/openscad/openscad/issues/1524 but neither are "Desktop" nor "Downloads".

**Comment by kintel** [comment]
The crash bug was fixed by @ChrisCoxArt. New universal binary: https://10400-1049088-gh.circle-artifacts.com/0/tmp/out/OpenSCAD-2022.01.23.dmg

**Comment by thehans** [comment]
I don't know the first thing about macs, so ignore me if this is irrelevant to the issue, but I was curious enough to search a bit and found this:
https://developer.apple.com/library/archive/documentation/Security/Conceptual/AppSandboxDesignGuide/AppSandboxInDepth/AppSandboxInDepth.html#//apple_ref/doc/uid/TP40011183-CH3-SW1

Sounds like maybe App Sandboxing got enabled for OpenSCAD (maybe unintentionally or involuntarily), but it hasn't any specific file entitlements configured?

**Comment by kintel** [comment]
Not sure if we get sandboxed per se, or if some other aspect of Mandatory Access Control or System Integrity Protection gets enforced. Most Apple docs tend to assume we're writing Cocoa apps using the XCode GUI for config, so it's a bit hard to translate this into something we can give to a compiler or query on an app.

If anyone are able to shine some light on this, I'd be interested in working towards solving this. It's just a bit daunting to chip away at this from scratch.

**Comment by tcurdt** [comment]
Maybe this helps to find out if it's running in the sandbox:

https://stackoverflow.com/questions/12177948/how-do-i-detect-if-my-app-is-sandboxed

Another indication could also be that some of the application specific paths point to a container.

https://developer.apple.com/documentation/foundation/filemanager

**Comment by logiota** [comment]
Great work, I compiled an arm version and halved the compile time!

**Comment by logiota** [comment]
> The crash bug was fixed by @ChrisCoxArt. New universal binary: https://10400-1049088-gh.circle-artifacts.com/0/tmp/out/OpenSCAD-2022.01.23.dmg

Wow this reduced build time by 80%!

**Comment by kintel** [comment]
@logiota The latest version also includes a malloc optimization (#3943) which explains the extra rendering boost.

**Pull request merged**
