### PR TITLE
SVG Import

### PR DESCRIPTION
**Pull request by t-paul**
SVG Importer based on libxml, eigen3 and boost. This is supposed to become a library later, but right now it's simply integrated into the OpenSCAD build system.

The test suite currently has examples from the SVG-Spec, the W3C Test Suite and a collection of images from the OpenClipArt library. The results are published on http://files.openscad.org/svglibtest/ for discussion how specific cases should be handled.

ToDo:
- [x] Drag&Drop should create an import() statement
- [x] Remove the new width/height parameter to import.
- [x] Make experimental
- [ ] Clarify how to handle intersection of multiple imported paths
- [x] Test on Linux
- [x] Test on MacOS
- [ ] Test on Windows
- [x] Add export-import tests
- [ ] Investigate single export-import test failure
- [ ] Test lazy union export (see #350)
- [ ] Look into applying DPI when importing px or unitless designs

Might be considered as well:
- [ ] Viewport clipping -> I don't think this is important (@kintel)

### CODE REVIEW

**Comment by adius** [comment]
What is the future of this one?

**Comment by kintel** [comment]
It needs more love.
I could be possible to add it as an experimental feature while we iron out the remaining issues.

**Comment by adius** [comment]
I think experimental feature sounds like a good idea!

**Comment by kintel** [comment]
@t-paul I brushed a little dust off this one, and added an experimental check. I feel it might make sense to merge to master, to get some more external input on this.

**Comment by t-paul** [comment]
Cool, that would unblock the AMF-Import too :-).

**Comment by kintel** [comment]
..and the export-import test now proves that importing exported svg's yield the same result :)

**Comment by kintel** [comment]
Old SVG test files are here: https://github.com/openscad/svg-tests

**Comment by Neon22** [comment]
This is my test file - I use it in the inkscape to openscad extension. It has nested paths and loops.
[test_inkscape_generate.zip](https://github.com/openscad/openscad/files/372601/test_inkscape_generate.zip)
http://www.thingiverse.com/thing:1065500

**Comment by kintel** [comment]
@Neon22 Thanks, that's helpful. This has been merged to master, so it will be available in the next snapshot build. Perhaps you'd like to test it :) Which OS are you using?

**Comment by Neon22** [comment]
windoze 7.

**Comment by t-paul** [comment]
Nightly builds on OBS are updated, Windows builds are next on my list... `libxml2` is included in MXE and I think I tested Windows builds some time ago, so hopefully no build issues.

**Comment by kintel** [comment]
@t-paul Related to Windows, I just noticed this: http://www.appveyor.com/docs/installed-software

-> They have msys2 installed, so it might be possible to bootstrap a Windows build on that service

**Comment by kintel** [comment]
@Neon22 See http://files.openscad.org/snapshots/ ```OpenSCAD-2016.07.20-x86-*```

**Comment by Neon22** [comment]
Trying this on 64bit zip (exe does not show up anywhere).
Using:
```
import("C:/Users/user3/Downloads/OpenSCAD-2016.07.20-x86-64/openscad-2016.07.20/test_inkscape_generate.svg");
```
but getting format not supported error:
```ERROR: Unsupported file format while trying to import file '"../../test_inkscape_generate.svg"' ```

What's the proper command - any options ?

**Comment by kintel** [comment]
@Neon22 It's still experimental, so you have to enable it in Preferences->Features

**Comment by Neon22** [comment]
ahh brilliant thanks....

**Comment by Neon22** [comment]
Tested:
**Primitives:**
- rect single, multiple - OK
  - does pay attention to rounding but ignores the width of the strokes.
  - fail if rect is hollow - see it as a solid.(note below)
- circle single, multiple - OK
  - does not use stroke width, always solid
- arc - Fail
  - a circle is converted to arc if not complete. very common
- text - Fail
- path - single, nested, multiple - OK
  - stroke is ignored unless path is open then it is used for width.
  - so an unfilled path (outline) appears solid.

**Note:**
1. IMHO Generally acceptable for text to fail. Should add prominent note advice to convert text to path before exporting from app.
2. Arc should not fail.
3. Would be good to have flag to ignore thickness of stroke or not... currently ignored unless an open path.
4. if primitive has no fill but has stroke - should be a closed path of stroke thickness - but currently shows solid. I.e. fill/stroke state ignored everywhere except unclosed path.
5. Files with an item that fails to load - seem to not return successful primitives. Should probably convert all they can and fail silently if one item fails. This may be an anomaly - a file that initially failed to load would load after a different file had succeeded. so may be some instability with initial conditions.

Zip attached of files.
[openscad-svg_tests.zip](https://github.com/openscad/openscad/files/377423/openscad-svg_tests.zip)

**Final note.**
In my inkscape exporter I exported all as polygon lists with linear extrude pattern and height primitives for user control.
Use cases that should be handled IMHO:
- how high to extrude the resulting imported svg - needs to be a parameter as not derivable from svg file.
- whether to use stroke width or not
- for closed paths - interpret as though open (see my jigsaw pattern example for why user might want to do that to the surrounding closed path).
- how to hand the result to a module to do more with it - is it a polygon list.
- check my code (link above) to see what I created in openscad

IF we can't separate the many internal primitives into sep objects then user wil have to manually sep and load several files. In which case its absolutely critical that they are not repositioned/rescaled relative to each other.

**Comment by Neon22** [comment]
Tested: (in general working very well except for Arcs and fill/stroke state. Top marks)
**Primitives:**
- rect single, multiple - OK
  - does pay attention to rounding but ignores the width of the strokes.
  - fail if rect is hollow - see it as a solid.(note below)
- circle single, multiple - OK
  - does not use stroke width, always solid
- arc - Fail
  - a circle is converted to arc if not complete. very common
- text - Fail
- path - single, nested, multiple - OK
  - stroke is ignored unless path is open then it is used for width.
  - so an unfilled path (outline) appears solid.

**Note:**
1. IMHO Generally acceptable for text to fail. Should add prominent note advice to convert text to path before exporting from app.
2. Arc should not fail.
3. Would be good to have flag to ignore thickness of stroke or not... currently ignored unless an open path.
4. if primitive has no fill but has stroke - should be a closed path of stroke thickness - but currently shows solid. I.e. fill/stroke state ignored everywhere except unclosed path.
5. Files with an item that fails to load - seem to not return successful primitives. Should probably convert all they can and fail silently if one item fails. This may be an anomaly - a file that initially failed to load would load after a different file had succeeded. so may be some instability with initial conditions.

Zip attached of files.
[openscad-svg_tests.zip](https://github.com/openscad/openscad/files/377423/openscad-svg_tests.zip)

**Final note.**
In my inkscape exporter I exported all as polygon lists with linear extrude pattern and height primitives for user control.
Use cases that should be handled IMHO:
- how high to extrude the resulting imported svg - needs to be a parameter as not derivable from svg file.
- whether to use stroke width or not
- for closed paths - interpret as though open (see my jigsaw pattern example for why user might want to do that to the surrounding closed path).
- how to hand the result to a module to do more with it - is it a polygon list.
- check my code (link above) to see what I created in openscad

IF we can't separate the many internal primitives into sep objects then user wil have to manually sep and load several files. In which case its absolutely critical that they are not repositioned/rescaled relative to each other.

**Comment by kintel** [comment]
@Neon22 Thanks, that's very helpful. There are a number of things we need to sort out. Let's continue this discussion in #1740.

**Comment by kintel** [comment]
@Neon22 Btw., what was wrong with the arc? It looks correct to me (renders as a 'pacman' in OpenSCAD)

**Comment by Neon22** [comment]
I saw nothing at all. could be this initial condition I was referring to. On initial start it would not load the ..generate.svg nor the arc test but I had loaded rects and circles before trying to load the arc. but the arc failed. I saw nothing.
later I coudl load in 05-complex which is same as generate

**Pull request merged**
