### PR TITLE
Add simple input driver interface, support 3D Mouse devices

### PR DESCRIPTION
**Pull request by t-paul**
See #1433.

Driver backends (optional + compile time selectable):
- [HIDAPI](https://github.com/signal11/hidapi) driver, Windows and macOS
- [SpaceNav](http://spacenav.sourceforge.net/) driver, Linux only
- DBus driver, Linux only - prototype for a simple remote control protocol
- Joystick driver, Linux only

Also contains an initial version of a configuration GUI using low level Qt actions.

ToDo:
- [ ] Add option to enable/disable specific drivers?
- [ ] Tag as experimental feature?

### CODE REVIEW

**Comment by mvackel** [comment]
Hello,
any chance of working on this issue? 3D mouse would be a great feature!

**Comment by MichaelPFrey** [comment]
I made my own fork and branch of inputdriver3.
What would I have to do for a "minimum viable product" that can be merged into the master?
Would making it an "experimental feature" make it more likely to become part of the master branch?
Are the main issues code quality, missing features or "something else"?

**Comment by kintel** [comment]
@MichaelPFrey The TODO list in this issue indicates what's missing. Anything that may affect the stability, forwards compatibility or ability to compile OpenSCAD on all platforms should be made experimental until those issues have been ironed out. ..and will indeed make it more likely to merge early.
Another way to merge early would be to pull out any green refactoring and PR that separately - that would make it easier to review (functional changes vs. structural changes).
..but I haven't looked at the details to see if that's the case with this PR.
For this topic, I'm pretty much trusting @t-paul to make a good judgement and really only do a light review of the changes that may affect existing behavior.

**Comment by t-paul** [comment]
Ok, let me close this and create a pull request for `inputdriver4` to see travis results.

I think I already found one issue with that new branch, it seems to break the `ALT+Up`/`ALT-Down` feature.

**Comment by t-paul** [comment]
Ugh, I suspect my rebase was not against latest master :(

I guess inputdriver5 incoming to fix that...

**Comment by t-paul** [comment]
See  #2130.

**Comment by MichaelAtOz** [comment]
So this is the ongoing issue? I want to add-back the bounty.

**Pull request closed without merging**
