### PR TITLE
DPI Normalized Wireframe Rendering

### PR DESCRIPTION
**Pull request by deckar01**
Use the screen's DPI when calculating the line width and point size of wireframes.

See #2091 

<details>
<summary>1x DPI Wireframe</summary>

screen shot 2017-08-19 at 9 47 33 pm

> Note: The "DPR" value in this screenshot was for debugging and is not included in the PR.
</details>

<details>
<summary>2x DPI Wireframe</summary>

screen shot 2017-08-19 at 9 47 33 pm

> Note: The "DPR" value in this screenshot was for debugging and is not included in the PR.
</details>

### CODE REVIEW

**Comment by kintel** [comment]
Looks reasonable. Thx!

**Comment by deckar01** [comment]
It looks like the Travis build is failing due to `#include <QScreen>`. I don't fully understand why the QT versions are so different between Travis and my local machine. I apologize for the inconvenience.

A backwards compatible namespace could be used to provide `QScreen`, but this process is a bit opaque to me. I think a safer approach might be to put the includes behind the same QT version check that `get_dpi()` uses to make the dependency more explicit.

**Comment by kintel** [comment]
I forgot to review this properly; `OGL_helper.h` needs to be independent of Qt; we only use Qt for the UI, not for the underlying engine. ..so we need another mechanism for passing the DPI into the renderer.

I'll revert the commit for now.

**Comment by deckar01** [comment]
The renderer should probably encapsulate the DPI logic. The problem is that it doesn't encapsulate the actual draw operations. It's kind of weird that a renderer class delegates to a geometry class to draw itself.

It seems more natural to have `Renderer::draw(Polyhedron polyhedron)` than to have `Polyhedron::draw(float dpi)`.

I'm not sure if that is a flaw in the rendering pipeline of this library or a quirk of the CGAL geometry hierarchy.

**Comment by kintel** [comment]
There is a lot of room for refactoring of our renderer. I agree that some of the logic is inverted.
In terms of `OGL_helpers`, this is a helper class from CGAL itself that we had to slightly modify. I would either try to minimize how much we touch that one, or rewrite it completely to fit our needs.

**Pull request merged**
