### PR TITLE
Don't scan for parameters in included files 

### PR DESCRIPTION
**Pull request by amarjeetkapoor1**
In reference to issue #1840 .
It adds the file name to the location of the node and also doesn't scan for parameters in included files.

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
@kintel This PR is failing because of error "memory exhausted" is the case of test related rand.scad.

And the **solution** is to define `#define YYINITDEPTH ` in parser with some value greater than 200 
as what I found it that there is no relocation of stack happening in the parser and the upper limit is 200 not the 20000 as defined by 
`#define YYMAXDEPTH 20000`

So, should I define #define YYINITDEPTH in the parser?

https://stackoverflow.com/questions/20861945/how-to-increase-stack-size-in-bison-and-solve-memory-exhausted

**Comment by amarjeetkapoor1** [comment]
Another way is to define `# define YYLTYPE_IS_TRIVIAL 1` in parser although this also worked but not sure should we do that in general.

**Comment by kintel** [comment]
Defining YYINITDEPTH would make sense _if_ this is actually the issue.
To my understanding, this would only happen you have more than 200 unshifted symbols on the bison stack. That tends to indicate that something is very wrong (e.g. bug in the parser rules), but I haven't looked that the details.

**Comment by amarjeetkapoor1** [comment]
I checked the code of the main branch with YYMAXDEPTH=200 (i.e. no reallocation) and got the memory exhausted error. 

Above error is indeed due to a lot of unshifted symbols on the bison stack which went unnoticed due to the reallocation of the stack but this code is stopping the reallocation which would only be enabled either by defining  `YYLTYPE_IS_TRIVIAL` or by defining our own `yyoverflow` which will be a non-trivial task.

and how would we find the bug in parser rules which is causes memory exhaust?

**Comment by MichaelPFrey** [comment]
Closed/obsolet by #2322?

**Comment by t-paul** [comment]
Yes, should be covered by #2322, tested with a simple case and that worked ok.

**Pull request closed without merging**
