### PR TITLE
Fix for kintel's obj file cube corner testcase .

### PR DESCRIPTION
**Pull request by gsohler**
using information provided by builder.vertexIndex

### CODE REVIEW

**Comment by kintel** [comment]
This implementation still doesn’t maintain more complex manifolds, but it’s an improvement from the current state, so let’s merge it!

**Comment by gsohler** [comment]
This came into my mind during lunch time too.
The Solution you are looking for it the plain dumb solution without
PolySetBuilder and this without PolySetBuilder..
I just introduced the polysetbuilder everywhere when doing the indexed
mode. Apparantly that was too nice 🤣

**Comment by kintel** [comment]
Fixes #5015

**Comment by kintel** [comment]
I'm preparing some tests to exercise the manifold corner cases, so no action needed right now. I'll create new tickets as needed once I understand where we need to go.

**Pull request merged**
