### PR TITLE
Stack trace for function and module calls

### PR DESCRIPTION
**Pull request by MichaelPFrey**
wait for #2630 as they have to work nicely with each other

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
bildschirmfoto von 2018-12-18 22-05-08
bildschirmfoto von 2018-12-18 22-18-38
https://github.com/openscad/openscad/pull/2547#issuecomment-435503679
```
function recurse(x) = max(x, recurse(x));

x = recurse(1);
```
bildschirmfoto von 2018-12-19 22-26-42
https://github.com/openscad/openscad/pull/2547#issuecomment-435662863
```
module a() children();
module b() children();
module c() children();
module d() children();
module e() children();

module recurse(x) {
    a() b() c() d()
        translate(x)
            e()
                rotate(x)
                    recurse();
}
    
recurse(1);
```

bildschirmfoto von 2018-12-19 22-33-58

**Comment by MichaelAtOz** [comment]
Very nice.

What does it do with #2632?

**Comment by MichaelPFrey** [comment]
#2632: Simply crash. The stack trace comes into play after the error already has been detected.
#2632 + #2647: Untested, but I know a similar example:

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/User-Defined_Functions_and_Modules#Recursive_functions
```
function add_up_to(n, sum=0) =
    n==0 ?
        sum :
        add_up_to(n-1, sum+n);
echo(add_up_to(-1));
```
bildschirmfoto von 2018-12-24 23-11-54
```
Compiling design (CSG Tree generation)...
ERROR: Recursion detected calling function 'add_up_to' in file openscad-trace, line 4
TRACE: called by 'add_up_to', in file openscad-trace, line 5.
TRACE: called by 'echo', in file openscad-trace, line 5.
ERROR: Recursion detected calling function 'add_up_to'
Compiling design (CSG Products generation)...
```
This implementation is tail recursive. I think when someone manages to write tail recursive code, knowing that it was called from line 5 should help alot.

**Comment by MichaelPFrey** [comment]
This morning, #2632 does not crash:
bildschirmfoto von 2018-12-25 09-41-48

**Comment by MichaelPFrey** [comment]
bildschirmfoto von 2019-01-02 22-42-09
bildschirmfoto von 2019-01-02 23-22-21
bildschirmfoto von 2019-01-02 23-24-00

**Comment by MichaelPFrey** [comment]
This is interesting:
bildschirmfoto von 2019-01-04 07-52-57

**Comment by MichaelPFrey** [comment]
Outputting the warning twice is more or less an artifact from various refractorings. So: Let's cut off that thing and regenerate the tests.

**Pull request merged**
