### PR TITLE
Updated spanish translation

### PR DESCRIPTION
**Pull request by javialamo**
Some corrections to the spanish translation

### CODE REVIEW

**Comment by kintel** [comment]
Thanks!

**Comment by RedSoxFan04** [comment]
I recently tried OpenScad and noticed that most of it is still in Spanish. Is it a bug in the code? Or has it always been like this? Do you need a translator?

**Comment by t-paul** [comment]
Translation issue on MacOS - ref #1813.

**Comment by kintel** [comment]
@RedSoxFan04 Could you try the latest development snapshots?

**Comment by RedSoxFan04** [comment]
I just tried the latest development snapshot, and you're right, the bug has been squashed. When I opened OpenSCAD, the whole program was in English this time. 

It just took me an extra 30 seconds or so to get it to open because MacOS Sierra has this annoying issue where it will only let you install software from the Mac App Store and "Identified developers", but you can always override by clicking "Open Anyway) in the Security & Privacy section of System Preferences.

I'm glad the language bug has been taken care of.

**Comment by donbright** [comment]
see also https://github.com/openscad/openscad/issues/1818 and https://github.com/openscad/openscad/issues/880

**Pull request merged**
