### PR TITLE
Redesign find and replace panel

### PR DESCRIPTION
**Pull request by onewhl**
Current design of panel is not usability(see issue #962), so I suggest redesign.
How it looks:  
_Find..._
find

_Find and replace..._
findandreplace

### CODE REVIEW

**Comment by kintel** [comment]
@hroncok @t-paul Any comments on this? It looks cleaner to me, so I'll merge unless you have any opinions.

**Comment by t-paul** [comment]
The change does not really address the issue raised in #962, but I don't have a good idea how to solve that except maybe moving the whole find panel to the bottom of the editor.

Apart from that, I agree it looks a bit simpler, even though the texts take quite some screen space. So I'd vote for merging.

**Comment by MichaelAtOz** [comment]
A line across could help (with the above), similarly with the console  (it also provides a visible anchor to drag) 
Should also do something similar to allow gui close of the animate pane.?
gui line

**Comment by t-paul** [comment]
How the title bar is drawn, is up to the selected Qt theme, I don't know if there's a safe way to change things there without the risk of breaking other themes.
Maybe we could try to generate a very thin border around the title bar?

**Comment by kintel** [comment]
Yep, this doesn't address #962, but it still a worthwhile usability upgrade.

**Comment by t-paul** [comment]
Hmm, that broke the nightly builds with the UI file property `clearButtonEnabled`.

```
[  543s] In file included from src/MainWindow.h:6:0,
[  543s]                  from src/openscad.cc:572:
[  543s] objects/ui_MainWindow.h: In member function 'void Ui_MainWindow::setupUi(QMainWindow*)':
[  543s] objects/ui_MainWindow.h:640:25: error: 'class QLineEdit' has no member named 'setClearButtonEnabled'
[  543s]          findInputField->setClearButtonEnabled(true);
[  543s]                          ^
[  543s] objects/ui_MainWindow.h:661:28: error: 'class QLineEdit' has no member named 'setClearButtonEnabled'
[  543s]          replaceInputField->setClearButtonEnabled(true);
[  543s]                             ^
```

**Comment by t-paul** [comment]
Ahh, yes: ["This property was introduced in Qt 5.2."](http://doc.qt.io/qt-5/qlineedit.html#clearButtonEnabled-prop)

I guess we can just remove it for now...

**Comment by kipbits** [comment]
the old design was better(at least on mac). is it possible to change it back?

**Comment by kipbits** [comment]
[#626](https://github.com/openscad/openscad/pull/626) / [#628](https://github.com/openscad/openscad/pull/628) had a better feel on mac. is it possible to switch back. 

also I was thinking a big improvement for find-replace would be to have a find-count, and highlighting of all found words in a different color from normal cursor highlight. I was in the process of trying to maybe do my own when i discovered this thread. 

the feature i am interested in is still not implemented...

**Comment by kipbits** [comment]
I've reverted the design on my local machine(with a few minor changes); still working on adding improvements. I had some confusion with the [qscintilla](http://pyqt.sourceforge.net/Docs/QScintilla2/) editor vs the legacy([qtextedit](http://doc.qt.io/qt-4.8/qtextedit-members.html)) editor. It appears that all functionality is handled by [scintillaeditor.cpp](https://github.com/openscad/openscad/blob/master/src/scintillaeditor.cpp), and that [legacyeditor.cc](https://github.com/openscad/openscad/blob/master/src/legacyeditor.cc) no longer gets called on for anything? I would like to try and add find-count, and highlighting-of-all-found-matches. I think this can be done with [scintilla](http://www.scintilla.org/ScintillaDoc.html) using [Markers](http://www.scintilla.org/ScintillaDoc.html#Markers) and [Indicators](http://www.scintilla.org/ScintillaDoc.html#Indicators). Might take me abit of time so I'm posting this here, but if knowbody has any objections I'll see what i can do... expect a PR.

**Comment by kintel** [comment]
@kipbits The idea is to eventually kill the old editor. We just wanted to make sure there aren't any showstopper bugs in the scintilla one. Having the old editor available makes it easy to test if a particular issue is related to the editor itself or of it's an issue with another component.

**Comment by kipbits** [comment]
OK, I finally got around to working and making some changes here. I have highlighting-match-words working now, but i'm still working on the find-count display. Also, I made a few minor changes for sake of code clarity. I'm going to try and do it all in one big PR, unless find-count turns out to be too difficult
screen shot 2017-01-29 at 11 41 17 am

**Comment by kipbits** [comment]
continue discussion: https://github.com/openscad/openscad/pull/1922

**Pull request merged**
