### PR TITLE
FindReplace: Highlight found match words & find-count

### PR DESCRIPTION
**Pull request by kipbits**
These changes are to implement highlighting of found matches for
enhanced find&replace functionality.

Highlighting was implemented by designating a new indicator number 9 to
represent all find-related-indicators, and are updated through the
addition of the following functions&variables:
ScintillaEditor::resetFindIndicators(
MainWindow::hideFind(
MainWindow::showFind(
MainWindow::showFindAndReplace(
& variable:
ScintillaEditor.findIndicatorNumber

A few other changes were made to current class member names to prevent
confusion with the new functionality, and to improve readability:
MainWindow::find(
   ->   MainWindow::showFind(
MainWindow::findAndReplace(
   ->   MainWindow::showFindAndReplace(
ScintillaEditor.indicatorNumber
   ->   ScintillaEditor.errorindicatorNumber

I also made a few adjustments to MainWindow.ui I tried to go for a
compromise of the original legacy design, and what changes have been
made to the design, I hope this aesthetic change is accepted along with
the find-highlight-functionality as 1 PR.

Also Note, resetFindIndicators( returns an int. this is a find count
number, and I still have plans to display a find count in my next PR.

Thankyou

### CODE REVIEW

**Comment by kipbits** [comment]
see previous discussion: https://github.com/openscad/openscad/pull/1767

**Comment by t-paul** [comment]
Can you restore the MCAD git submodule? Because this is missing, all the test cases failed.

**Comment by kipbits** [comment]
just the empty folder?

**Comment by t-paul** [comment]
Yes, I guess so, the reference is in https://github.com/openscad/openscad/blob/master/.gitmodules which seems to be unchanged.

**Comment by kipbits** [comment]
i don't know how it ended up being empty. is it possible to add that back in in the next pr or do i need to close this and start over?

**Comment by kipbits** [comment]
or give me a moment let me see if i can change it....

**Comment by t-paul** [comment]
It's normally empty. The submodule is only used by the test suite, so if that's not run, it's just an empty folder that could be initialized by "git submodule".

**Comment by kipbits** [comment]
ok hope that fixes it?

**Comment by t-paul** [comment]
We'll see the Travis report below in half an hour or so.

**Comment by kipbits** [comment]
...?

**Comment by t-paul** [comment]
Hum, looks like one of the Linux builds crashed due to some package download issue and the macOS did timeout. Both unrelated to the actual pull request, so the test run issue seems to be fixed.

**Comment by kipbits** [comment]
I'm going to try and add find count display. Expect another commit by the end of the day...

**Comment by kipbits** [comment]
display find count is a little more difficult than anticipated. trying to make a subclass of QLineEdit that holds a Label. can't get past error:
Undefined symbols for architecture x86_64:
QWordSearchField::QWordSearchField(QWidget*)", referenced from:
Ui_MainWindow::setupUi(QMainWindow*) in mainwin.o
QWordSearchField is my invented class. I'm trying to model it after QGLView, and some old sample code.
any hints?

**Comment by kipbits** [comment]
well that didn't fix it...

Undefined symbols for architecture x86_64:
  "QWordSearchField::QWordSearchField(QFrame*)", referenced from:
      Ui_MainWindow::setupUi(QMainWindow*) in mainwin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

QWordSearchField.h
```
#ifndef QWORDSEARCHFIELD_H
#define QWORDSEARCHFIELD_H

#include <QLineEdit>
#include <QLabel>

class QWordSearchField : public QLineEdit
{
    Q_OBJECT
    
public:
    QWordSearchField(QFrame *parent = NULL);
    
protected:
    //void resizeEvent(QResizeEvent *);
    
private slots:
    //void updateFieldLabel(const QString &text);
    
private:
    QLabel *fieldLabel;
};

#endif /* QWORDSEARCHFIELD_H */
```

QWordSearchField.cpp
```
#include "QWordSearchField.h"

QWordSearchField::QWordSearchField(QFrame *parent) : QLineEdit(parent)
{
    fieldLabel = new QLabel(this);//, Qt::WindowFlags f = Qt::Widget);
}
/*
void QWordSearchField::resizeEvent(QResizeEvent *)
{
    QSize size = fieldLabel->sizeHint();
    int frameWidth = style()->pixelMetric(QStyle::PM_DefaultFrameWidth);
    fieldLabel->move(rect().right() - frameWidth - sz.width(),
                      (rect().bottom() + 1 - size.height())/2);
}

void QWordSearchField::updateFieldLabel(const QString& text)
{
    fieldLabel->setVisible(!text.isEmpty());
}*/
```

changes in MainWindow.ui
```
...
  <customwidget>
   <class>QWordSearchField</class>
   <extends>QFrame</extends>
   <header>QWordSearchField.h</header>
   <container>1</container>
  </customwidget>
```

don't see what i'm missing?

**Comment by kipbits** [comment]
Success! Finally

looks like i just forgot to add 
```
src/QWordSearchField.h
src/QWordSearchField.cc
```
 to my **openscad.pro**

**Comment by kipbits** [comment]
ok I've got the basics of find-count working, still some bugs so i have not pushed the changes. Wondering if it could be related to a bug in QScintilla 2.7?
 anyway here is a picture:
screen shot 2017-02-01 at 6 36 11 pm

**Comment by MichaelAtOz** [comment]
@kipbits looks good, thanks for this. 
I code more complex things in Notepad++ and find this feature extremely useful, will be glad when it's there for my minor edits done within OpenSCAD.

**Comment by kipbits** [comment]
can't figure out this minor bug with the find count lagging by 1 event. 

just uploaded what i got

**Comment by kipbits** [comment]
oops! looks like my mcad is still screwed up...

**Comment by kipbits** [comment]
or should i have left the folder in. I'm bit confused about this travis-ci. other pr's seam to not need this?

**Comment by kipbits** [comment]
or at least they don't have the same number of files changed that i have. the majority of my files changed are in from the MCAD folder i just dragged and dropped from a backup repository. 

did i do this correctly or should i be doing something else?

**Comment by kipbits** [comment]
ok i guess that was it then. 
hope you like it!

**Comment by kipbits** [comment]
99% tests passed???

**Comment by kintel** [comment]
@kipbits You MCAD is still causing an issue - you shouldn't commit any changes to the MCAD folder. I think the best way forward would be to back out any commits you made to MCAD and force-push your branch. ..or if it's easier, just re-commit your changes on top of master and force-push.

**Comment by kintel** [comment]
@kipbits Btw., I think the test failures are my fault. Try merging with the latest master.

**Comment by kipbits** [comment]
fewer fails, still not 100%

**Comment by kipbits** [comment]
could failure of tests #2 & #3 have anything to do with my use of console outputs? I can remove that if it might help

**Comment by kintel** [comment]
@kipbits Sorry about the test failures - the current master should (finally) be good now - try to merge.

**Comment by kipbits** [comment]
ok lets see if that does it.

Also find count label now displays the correct value

**Comment by kintel** [comment]
@kipbits The tests look good now. Btw., could you get rid of the MCAD commits, either by squashing the pull request or by force-pushing a clean branch?

**Comment by kipbits** [comment]
unsure how to fix MCAD. There was an error when i first cloned the openscad repository, and now when i click the link in [files changed](https://github.com/openscad/openscad/pull/1922/files) i get the following error:

```
-ssh: Could not resolve hostname ..: nodename nor servname provided, or not known

[Process completed]
```

**Comment by kintel** [comment]
I think you need to go back in history and remove all commits touching MCAD. Alternatively, clone a fresh OpenSCAD and recommit your changes without touching MCAD.

**Comment by kipbits** [comment]
ok I cloned fresh and created a new PR. it doesn't seem to have fixed anything. 
continue on #1938

**Comment by kipbits** [comment]
i seem to have lost the folder for this PR. 
happily all the changes are preserved in #1938

**Comment by kipbits** [comment]
now on #1947

**Pull request closed without merging**
