### PR TITLE
Gui updates

### PR DESCRIPTION
**Pull request by t-paul**
This is fixing the issues from #1149 and includes the new Toolbar icons from #1109.

- [ ] reconsider look of the render icon
- [ ] reconsider look of the reset-view icon

snapshot2

### CODE REVIEW

**Comment by MichaelAtOz** [comment]
I think the size of the compile error message is a bit over the top compared to all the other GUI items
It also resizes the edit window to make room when the overall window is small. Also grows the window if needed. I'm not sure if there are still people out there with small monitors?? But I occasionally use small OpenSCAD windows side-by-side.

Also, is it possible to ignore DEPRECATED for this purpose? There is little you can do about it and it stuffs up the display for every compile.

warning

**Comment by t-paul** [comment]
The font should be fixed already.

**Comment by MichaelAtOz** [comment]
For info that was 2015.01.08.

**Comment by t-paul** [comment]
It's work in progress. I just closed issue #1149 as the pull request now exists here.

**Comment by t-paul** [comment]
Snapshots 2015.01.10 are online. Note that those are including both the ```gui-updates``` (#1150) and the ```win-version-detect``` (#1076) changes which are not yet merged...

Please check the reported windows version too. The change is supposed to detect win8.1 but of cause it should still correctly report older Windows version as well.

**Comment by MichaelAtOz** [comment]
1. Windows version appears to be correct for my W7. Would there be any need to report Windows 32 bit v's 64 bit? (it does show that gcc is 64 bit)

2. The compile warning message is better, but the close icon needs work:
compile icon

3. The new splash screen background is better but it conflicts with the two buttons:
splash screen

**Comment by Scalpel78** [comment]
My splash screen looks slightly better than Michaels.

image

But how do you get the dark background inside the main application? I can set the viewport and the editor to dark themes, but not the application itself.

image

**Comment by MichaelAtOz** [comment]
> But how do you get the dark background inside the main application? I can set the viewport and the editor to dark themes, but not the application itself.

I suspect that is Windows Display Personalisation. Tho I think the OP is Linux or Mac.

**Comment by t-paul** [comment]
For a 32bit build running on a 64bit system, it will include [WOW64](http://en.wikipedia.org/wiki/WoW64) in the version line (which has nothing to do with the game :smiley:).

**Pull request merged**
