### PR TITLE
Customizer: Refractoring and beautify

### LINKED ISSUE #1845: Customizer GUI Improvements
Moved from #1781 
- [ ] Make whole parameter display a bit more compact (borders, name only bold not bigger font size...)
- [ ] Match Window border width with other windows (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Fix font sizes in Windows (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Check vertical spacing (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Fix slider paging (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Replace labels "+" and "-" with three separate labels ( someone found them misleading):
  1. New - for a new Preset.
  2. Update - to update the current Preset with the current parameter values.
  3. Delete - to delete the current Preset (after a confirmation).
- [ ] Check mouse scrolling behavior (parameter pane vs. range controls) (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18761))

### PR DESCRIPTION
**Pull request by MichaelPFrey**
**Cosmetic**
- Cosmetic changes should close #1845 _(except the scrolling issue)_
- layout more compact
- new option "inline details" options for designers that use short variables names _(note: line wrap is intentionally disabled)_
- removed the headline, make the button full width _(-> helps with short headlines, "feels" more consistent)_
- sliderValue
  * now above the slider, so that the value does not affect the length of the slider _(when dealing with "big" numbers it gets "glitch" as the growing text forces the slider to scale down, changing the value, allowing the slider to grow...)_
  * sliderValue is now a doubleSpinBox _(allows the user to directly enter a value)_

bildschirmfoto von 2017-11-02 22-54-16

**Functionality**
-  Replaced the labels "+" and "-" with three separate labels _(see also #1845)_
-  parameter widget will not be deleted and recreated when the render/compile is caused by
  * the animation timer _(-> allows the customizer to work better with animations)_
  * the ParameterWidget _(-> improves user experience)_
- user can now set the range for vectors
  - examples: 
    Vector1=[12.5]; //[0:20]
    Vector2=[10,35]; //[0:5:100]
    Vector3=[12,34,45];//[-5:0.5:5]
    Vector4=[12,34,46,24];//[10:2:50]

**Code clean up**
- OOP: Reduced scope & visibility of variables and methods
- Naming of Variables and Function

### CODE REVIEW

**Comment by kintel** [comment]
Nice! Looks pretty clean to me.
Anyone have any opinions on this before I merge?

**Comment by MichaelAtOz** [comment]
Much better, maybe the vertical spacing around the slider could be tighter? I'm an extremist when it come to screen real-estate...

**Comment by MichaelPFrey** [comment]
@MichaelAtOz 
A lot of what I did here was more fighting with QT, then intentionally setting the spacing between elements. (which also explains, why the UI looked how it looked before)
This time: The QStackedWidget sets its size to the biggest widget contained by default.
crop

**Comment by MichaelAtOz** [comment]
Well I can't complain about anything now. ;)

**Comment by kintel** [comment]
@MichaelPFrey I see you're actively modifying this PR. Give me a hint when you deem it stable enough to merge (by removing the <kbd>DON'T MERGE</kbd> tag)

**Comment by MichaelPFrey** [comment]
@kintel thank you, will do.
Currently, I am mainly testing, but the better the customizer works, the easier it gets notice when something simply does not "feel" right.

**Comment by MichaelPFrey** [comment]
@kintel it looks to me, as if I can not remove the the label.
Would/Could you remove the label "Do Not Merge" Label and add the "Customizer" label?
I have done my tests. Next will be updating the documentation, but for that I would like to have it in the master branch.

**Comment by kintel** [comment]
thx!

**Comment by t-paul** [comment]
I'd vote for not supporting HTML in the description. It's already a problem in the console window where it makes things much more complicated to change.

**Comment by MichaelPFrey** [comment]
@t-paul Just for your information:
The HTML support was/is enabled (intentional or not) for a long time now.
This "feature" was just undocumented. I found this feature already enabled will I was going trough the UI.
I would suggest to discuss this separately from this pull request, as the "feature" clearly predates my changes.

**Comment by t-paul** [comment]
True, and yes, creating a new issue is best. Still documenting makes it sort of official.

**Comment by MichaelPFrey** [comment]
Understood, I now removed the section from the wikibooks.

**Comment by t-paul** [comment]
Thanks, created #2184 to discuss and track that issue separately...

**Pull request merged**
