### PR TITLE
Change license for example files.

### PR DESCRIPTION
**Pull request by t-paul**
- Change the examples written by me to CC0
- Include CC0 license text

### CODE REVIEW

**Comment by hroncok** [comment]
So now we have:
 * CC0 examples by Paul
 * CC BY-SA examples (Advanced/fractal.scad)
 * CC - GNU GPL (in fact GNU GPLv2+) examples (Shapes/sphere.scad and Shapes/chopped_blocks.scad)
 * no license (assuming the same license as OpenSCAD use applies) examples (multiple)

Any chance for simplification?

**Comment by t-paul** [comment]
Yes, the plan is to get all licensed as CC0.

**Comment by hroncok** [comment]
Great.

**Comment by kintel** [comment]
@hroncok Just pushed a fix - only fractal is left. Waiting to hear from the authors.

**Pull request merged**
