### PR TITLE
macOS package upgrade: 

### PR DESCRIPTION
**Pull request by kintel**
gmp 6.2.1, libffi 3.4.2

### CODE REVIEW

**Comment by kintel** [comment]
Took out poppler for now, see comment in https://github.com/openscad/openscad/issues/3920

**Comment by t-paul** [comment]
Maybe we can integrate the updates/fixes from https://github.com/openscad/openscad/commits/qt5-upgrade-macos here too.

**Comment by kintel** [comment]
Nice! I might separate out the qt stuff and continue on that branch instead. Trying to limit the  scope of my PRs in case I get too busy elsewhere:)

**Comment by kintel** [comment]
Pulled out qt and qscintilla as well; will create separate PRs for those.

**Comment by kintel** [comment]
Slimmed this down it its minimal state. Also uploaded built libraries from CircleCI and update the sha. Not sure if this is the ideal way of doing that these days. Let me know if there is a better process.

**Comment by t-paul** [comment]
No, nothing better at this point. It's not happening too often, so I've not spend much time thinking about a better solution.

**Review by t-paul — APPROVED** [review]

**Pull request merged**
