### PR TITLE
added line number option on editor preferences

### PR DESCRIPTION
**Pull request by jasleenkaur**
Added Check Box for enabling/disabling line number in QScintilla Preference Options.

### CODE REVIEW

**Comment by kintel** [comment]
Thanks.

A few minor suggestions:
* Rename ```enableLineNumber``` to plural? i.e. ```enableLineNumbers```
* Change "Enable Line Number" to "Display Line Numbers"

**Comment by jasleenkaur** [comment]
done.

**Comment by kintel** [comment]
thx

**Comment by t-paul** [comment]
Hiding the line numbers works fine, it does not reclaim the space though.

openscad-hide-line-numbers

**Comment by kintel** [comment]
I noticed as well. That space is used for error indicators. One extension to this could be to open the margin on demand. Perhaps look at how other Scintilla-based editors solve this.

**Comment by t-paul** [comment]
Yeah, we can't hide it completely, but it could shrink to the minimum size required for the other stuff, in the picture above it's sized for 4 digit line numbers. IIRC we already do the resizing in our code.

**Comment by jasleenkaur** [comment]
https://github.com/openscad/openscad/pull/1615

**Pull request merged**
