### PR TITLE
Test re-submission of PR 2399 to see if CircleCI triggers

### PR DESCRIPTION
**Pull request by justbuchanan**
See comments on #2399

### CODE REVIEW

**Comment by justbuchanan** [comment]
Strange. I've had this working on other repos with circleci before and the only setting I know of that's relevant is the "Build forked pull requests" toggle that you already turned on.

**Comment by t-paul** [comment]
Yep, that's what I'm reading everywhere, so I'm a bit suprised it's not working.

**Comment by t-paul** [comment]
Oh, I think it's the webhook on github side not posting the event.

**Comment by justbuchanan** [comment]
Yeah that would make sense. Maybe the instructions here could help? https://discuss.circleci.com/t/troubleshooting-when-circle-doesnt-build-after-pushes-to-github/12414/4

**Comment by t-paul** [comment]
I've enabled pull requests for the webhook, could you try again?

**Comment by justbuchanan** [comment]
It works!

**Pull request closed without merging**
