### PR TITLE
warn, when an assigment from the RootModule overwritten by an include

### PR DESCRIPTION
**Pull request by MichaelPFrey**
beforemainafter

I used the uncomplete code as used by assert, so I added an "assert(false);" into my test files.

### CODE REVIEW

**Comment by nophead** [comment]
I now get this with an empty file that includes my library. It isn't very helpful because it doesn't specify the filename. There are hundreds of files, some used, some included and many of the have a length defined.

image

**Comment by MichaelPFrey** [comment]
@nophead I have not done a lot of testing with "use", so I would expect the issue be something related to the use instruction. The solution will likely be just to disable the warning when a file is being "used". I am going to look into it.

**Comment by nophead** [comment]
I used an editor that can search all the files for "length =" and show line numbers of matching lines and it turned out they were duplicate definitions inside modules in a used file. They were a valid bug as there should only have been one definition in each module but fortunately the last one was the correct one.

It is a useful warning but it needs to show the file name, not just the line number.

**Comment by kintel** [comment]
Since this is already merged, could someone summarize this as a new issue?

**Comment by nophead** [comment]
OK, #2513

**Pull request merged**
