### PR TITLE
Update icon-nightly.scad (moon color)

### PR DESCRIPTION
**Pull request by UBaer21**
more yellowish for better contrast on gray window background

### CODE REVIEW

**Comment by kintel** [comment]
IMO, it doesn't look very good unless we do something about the stars too

**Comment by UBaer21** [comment]
Making them the same color will have no contrast to the moon
image

it also seems that the exported logo that is used has no transparency on the surface.
image

here a "SlateGrey" variant
image

**Comment by kintel** [comment]
The original was rather quick&dirty. I wonder if it would look better with the stars were yellow, and embedded into the surface of the sphere rather than subtracted. ..or perhaps slightly embossed?
Transparency rendering is currently not great, so we may need to play around to make the rendering look decent

**Comment by UBaer21** [comment]
image

here in gold on surface

**Comment by UBaer21** [comment]
closing and changing to
image

**Comment by jordanbrown0** [comment]
I never knew about the moon and stars, because the largest I ever see this icon is about 30x30 pixels.  They are quite cool, but are they really useful at icon sizes?

**Pull request closed without merging**
