### PR TITLE
Add ccache to cmake. #2109

### PR DESCRIPTION
**Pull request by justbuchanan**
This caches compiled object files, which can significantly speed up partial re-builds. This is most useful when switching between git branches. Normally, any changed files and dependencies would need to be re-compiled each time you switch branches. With ccache, any file that was previously compiled with the same inputs can be re-used from the cache.

I added a check so that it will only use ccache if it is installed.

### CODE REVIEW

**Comment by kintel** [comment]
Will this clear the ccache cache on `make clean`? If not, what's the process for clearing the cache (to be able to perform a full rebuild for cases where ccache fails or you change any environment not detected by ccache)?

**Comment by kintel** [comment]
Oh, btw., running ccache on TravisCI could be really interesting.

**Comment by justbuchanan** [comment]
Ccache stores things in `~/.ccache`, so clearing that directory will reset the cache. `make clean` doesn't have any effect on ccache. In theory, ccache records all relevant environment bits for each compilation, so it *shouldn't* be susceptible to the types of situations where `make clean` would fix a build issue. In practice, it's possible you may need to reset ccache, but I haven't encountered that yet after using ccache for several projects.

I think TravisCI would see a pretty large speed improvement with ccache. The only thing we'd need to do after this PR is add the ccache directory to travis's cache list.

**Comment by kintel** [comment]
I guess my question is more like: Does ccache figure out what compiler you're using and correctly wipe the cache if you `apt-get upgrade` your compiler?, and does it know what environment variables influence the build?

**Comment by justbuchanan** [comment]
Yes, it records the compiler that was used and all of the parameters passed to it. Their website has a more complete list of what goes in the hash that identifies each object file: https://ccache.samba.org/manual.html#_common_hashed_information.

Ccache is invoked by `make` just before the compiler. Where `make` would have previously done something like `gcc src/main.cc -o build/main.o`, it instead invokes `ccache gcc src/main.cc -o build/main.o`. In this way, ccache can record compiler info and all relevant parameters, which it hashes together to identify the object file. Then ccache invokes the compiler itself, passing on the parameters.

**Comment by justbuchanan** [comment]
I tried enabling this for TravisCi and it seems to make a fairly large difference.

Before:
image

After:
image


The speedup won't be quite as big for commits that actually change code though.

**Comment by kintel** [comment]
Note: TravisCI builds OpenSCAD using qmake. cmake is only used to build some smaller test utilities. Not sure how to enable ccache for the qmake build, but that should have a more significant impact.

**Comment by justbuchanan** [comment]
TravisCI actually sets up ccache differently when you add `ccache: travis` to the config. If you look in the build logs, you'll see:
* export PATH=/usr/lib/ccache:$PATH
* Check for working C compiler: /usr/lib/ccache/gcc -- works
* Check for working CXX compiler: /usr/lib/ccache/g++ -- works

This applies ccache to the qmake setup, independent of the changes I made to the CMakeLists.txt file.

Btw, it looks like the test cmake setup is separate from the main one. Should I also add ccache to tests/CMakeLists.txt?

**Comment by kintel** [comment]
Yes, it wouldn't hurt adding ccache to tests/CMakeLists.txt, for consistency.

**Comment by kintel** [comment]
I'm happy with this as is, but one final question: Is there an easy way for me to enable ccache locally for the qmake build system?

**Comment by kintel** [comment]
Humm, I guess for qmake I need to override some env. variables to trick qmake into using ccache as a compiler..

**Comment by justbuchanan** [comment]
I just tried and the export command I showed from travis didn't work for me either... I tried doing `export PATH="/usr/lib/ccache/bin:$PATH"` instead and it worked for me. A quick test you can do is `which c++`, which should give you `/usr/lib/ccache/bin/c++`. I'm not sure why the travis command didn't include the `/bin` at the end of the path.

**Comment by kintel** [comment]
On macOS, qmake appears to be too smart and doesn't look in the PATH for the compiler. This is probably why TravisCI has their own hand-tuned system containing ccache rather than installing it using homebrew.

**Comment by justbuchanan** [comment]
Recent versions of qmake have a ccache option builtin: https://codereview.qt-project.org/#/c/196345/.

If there's an easy way to check the version, we could turn it on when it's available. Aside from the version-checking, it looks as simple as `CONFIG += ccache`.

**Comment by kintel** [comment]
Nice - wasn't aware of that; perhaps time to upgrade Qt..

**Comment by kintel** [comment]
It should be possible to do (untested):
```
!lessThan(QT_VERSION, 5.9): CONFIG += ccache
```

**Comment by justbuchanan** [comment]
Cool, I tried that out and it works well. I also tested with the version set to a higher number than I have, and it worked fine and didn't use ccache.

**Comment by kintel** [comment]
ok, let's try this. If anything goes wrong we can add a flag to disable/enable it.

**Comment by kintel** [comment]
@justbuchanan Could you have a look at this build failure: https://travis-ci.org/openscad/openscad/jobs/293137464

-> somehow the Mac build still times out. It technically succeeds, but somehow still times out. Any ideas?

**Comment by justbuchanan** [comment]
Hmm, that's strange. I see "could not download cache" in the travis logs. Maybe it's a failure on their end? I'll open a test PR to trigger another build and see if it has better luck.

image

**Comment by donbright** [comment]
sorry i am a broken record on this stuff but it needs to be said. 

in my opinion and experience, a tradeoff between reliability of build vs speed of build  -> my vote is always going to be with reliability. the time we save building is not worth the time lost to debugging errors caused by not having a clean build. one of these speedups is 20 minutes out of 70 minutes.

we should be asking, why does it take 70 minutes to build in the first place? there is too much unnecessary code, too much duplicated code, too much complicated code that could be simplified. 

my two cents (yes i realize i am outvoted but that is no reason, not to vote!)

**Pull request merged**
