### PR TITLE
Customizer: show_if for groups

### PR DESCRIPTION
**Pull request by MichaelPFrey**
Example SCAD Files:
```
sphereF=true;
boxF=true;

/*[sphere] show_if(sphereF)*/
r = 10;
/*[box] show_if(boxF)*/
b = 10;
/*[cylinder] show_if(cylinderF)*/
r2 = 1;

if(sphereF) sphere(r);
if(boxF) translate([r,0,0])cube(b);
```

```
show = "box + sphere"; //["box + sphere", "box", "sphere"]

/*[sphere] show_if(sphereF)*/
r = 10;
/*[box] show_if(boxF)*/
b = 10;
/*[cylinder] show_if(cylinderF)*/
r2 = 1;

/*[hidden]*/    
sphereF = (show=="box + sphere") || (show=="sphere");
boxF =    (show=="box + sphere") || (show=="box");

if(sphereF) sphere(r);
if(boxF) translate([r,0,0])cube(b);
```

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
This would be an exclusive feature.
It is not supported by thingiverse.

**Comment by t-paul** [comment]
I'm still thinking it would be useful to have the comments as compatible with Thingiverse as possible.
The proposal for a native customizer markup included also that the actual meta data is parsed along the script not scraped from comments. Some examples are listed in the wiki - https://github.com/openscad/openscad/wiki/Meta-Data-Use-Cases

**Comment by MichaelPFrey** [comment]
Currently, the Thingiverse customizer is not working, so I can not test. I presume that incompatible syntax/features simply get ignored (similarly to how our customizer reacts).

Using our own meta data syntax would break compatibility of SCAD files. (a new syntax yields errors in old releases)
Expanding the comment syntax is "compatible" as in it gets ignored when not support (but it still provides context information to a person editing SCAD files)

Our own meta data syntax would presumably coexist with the comment style for support of thingiverse files.

Presuming that we do not want to have two UI and Back end codes, the new meta data style would presumably generate the same or similar data-structures as the current comment passed parser. So, any extension to the comment based syntax could be reused for the meta data style syntax.

**Comment by t-paul** [comment]
Yeah, the fixing seems to be still work in progress. We talked with one of the admins on IRC, but I don't know what the current state is. I tried earlier today and the "it's not working" marker is gone, but it's still producing the "can't load library" error.

The main problem I see with extensions in the comment syntax is that it's confusing for the user when trying to test stuff locally and then only part of the features work on Thingiverse.

The native syntax would not be compatible with older versions of OpenSCAD of cause, but that's the case with all new language features. When using new features, the new OpenSCAD version is required. I think that's not too surprising for users. We do try to not break older scripts with new versions as that is very annyoing. E.g. there's a number of things that are deprecated for quite some time but still work while producing a warning.

As for the UI, yes, that's supposed to work with just one data structure which is already called `Annotation` as that was coming from the native prototype I did quite some time ago :-).

The benefit of using the normal parser would also help making the `show_if()` more powerful as that could be an annotation parameter featuring full expression logic, like `visible = sphere_selected && radius > 6` although the scoping might be a tiny challenge to get it most useful.

**Comment by MichaelPFrey** [comment]
Take a look how I implemented the conditions: show_if() as implemented  is using a boolean from the context of the root_module. So, that actually works:
```
/*[sphere] show_if(sphereF)*/
r = 10;
/*[hidden]*/    
sphereF = (show=="box + sphere") || (show=="sphere");
```
For someone new to openSCAD it might consider it strange that the assignment is after the first usage of the variable in the script - but within OpenSCAD that is "by nature" correct.
I was thinking about parsing the condition - but that would open up a can of worms.

Using a variable look up on to the root module context is pretty elegant as the user has the full power of OpenSCAD.

The draw back of this implementation is off-course, that the condition is only evaluated after a compile.

**Comment by MichaelPFrey** [comment]
@kintel What do you prefer? Expanding the comment syntax for now or adding a new meta data syntax? (Note: expanding the comment syntax does not mean we can not add a meta data syntax latter - but the more feature we add in the comment syntax the less need will be for a native syntax)

**Comment by kintel** [comment]
I've always viewed the comment syntax as a temporary workaround to help transitioning into a better design meta-data format. The big question is when someone will have time to work on the latter, so the current comment-based syntax may end up having more permanence than initially expected.

I find it slightly scary to start adding more parsing logic to the comment syntax.
If you find this syntax really helpful, I suggest we keep it, but take note that we should reconsider this when making the next stable release; i.e. make it easy to disable.

**Comment by MichaelPFrey** [comment]
The argument with parser complexity is convincing for me. Every hack for it self maybe reasonable, but it stacks up - and that on top of a comment parser that it self is has room to improve. So, I close that pull request for now and may revisit it later.

**Pull request closed without merging**
