### PR TITLE
Issue432

### PR DESCRIPTION
**Pull request by robertlugg**
Added a check to confirm that the directory of the output file exists.  If not that output is skipped.  I'm happy to adjust behavior but this seems close to what the requestor asked for.

### CODE REVIEW

**Comment by robertlugg** [comment]
I’d be happy to implement others. but I struggled to see how I might do them. I could “touch” a file in the directory to check for write access. Maybe these checks belong after it fails so that they don’t waste time in the normal case??

**Comment by t-paul** [comment]
Boost filesystem should work with the `permissions()` call looking at this example: https://stackoverflow.com/questions/9776050/how-to-get-file-permissions-with-c-boost-library - At least on Linux that seems to work nicely.

**Comment by robertlugg** [comment]
Ok. I’ll experiment a bit more.  I don’t know how to see what group applies to me. But there must be a way. So am I in the owner, group. Or world?  The touch method will Tell through experimentation.

**Comment by t-paul** [comment]
Right, I don't see boost handling that. The low-level way on Linux is `access()` (https://www.gnu.org/software/libc/manual/html_node/Testing-File-Access.html) which is not directly available on Windows, but there seems to be `_access()`,

**Comment by robertlugg** [comment]
Would you take a look at the pull request I just put in?

**Pull request merged**
