### PR TITLE
Download Qt from archive folder if main download fails.

### PR DESCRIPTION
**Pull request by t-paul**

### CODE REVIEW

**Comment by ChrisCoxArt** [comment]
This does not work.
The curl call succeeds, but returns the text of the 404 page. The tar extraction then fails.

sh-3.2$ ./scripts/macosx-build-dependencies.sh
Detected Lion (10.7) or earlier
Building for 10.9 or later
Setting number of CPUs to 24
Using basedir: /Volumes/Development/openscad/../libraries
double_conversion eigen gmp mpfr glew gettext libffi freetype ragel harfbuzz libzip libxml2 fontconfig hidapi libuuid lib3mf glib2 boost poppler pixman cairo cgal qt5 opencsg qscintilla
Building packages: double_conversion eigen gmp mpfr glew gettext libffi freetype ragel harfbuzz libzip libxml2 fontconfig hidapi libuuid lib3mf glib2 boost poppler pixman cairo cgal qt5 opencsg qscintilla 

double_conversion 3.1.5 already installed - not building
eigen 3.3.7 already installed - not building
gmp 6.1.2 already installed - not building
mpfr 4.0.2 already installed - not building
glew 2.1.0 already installed - not building
gettext 0.21 already installed - not building
libffi 3.2.1 already installed - not building
freetype 2.9.1 already installed - not building
ragel 6.10 already installed - not building
harfbuzz 2.3.1 already installed - not building
libzip 1.5.1 already installed - not building
libxml2 2.9.9 already installed - not building
fontconfig 2.13.1 already installed - not building
hidapi 0.11.0 already installed - not building
libuuid 1.6.2 already installed - not building
lib3mf 1.8.1 already installed - not building
glib2 2.56.3 already installed - not building
boost 1.74.0 already installed - not building
poppler 21.10.0 already installed - not building
pixman 0.40.0 already installed - not building
cairo 1.16.0 already installed - not building
cgal 5.2 already installed - not building
Building Qt 5.9.9 ...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   310  100   310    0     0    890      0 --:--:-- --:--:-- --:--:--   890
100   196  100   196    0     0    183      0  0:00:01  0:00:01 --:--:--   544
tar: Error opening archive: Unrecognized archive format

**Comment by ChrisCoxArt** [comment]
And the script exits when tar fails, so I can't check for the existence of the directory it should extract.

**Comment by t-paul** [comment]
Right, looks like it needs a temporary `set +e` to prevent the script from exitting...

**Comment by ChrisCoxArt** [comment]
Set+e
tar ...
Set -e
works. Sigh, it's been too long since I've had to deal with bash scripts.

**Comment by ChrisCoxArt** [comment]
Slow to test this, because Qt throttles their server - it's taking over 2 hours to download each Qt build.
But at least the fallback archive download is going now.

**Comment by t-paul** [comment]
Thanks for confirming, `set +e` change merged via #3918.

**Pull request merged**
