### PR TITLE
Probe

### PR DESCRIPTION
**Pull request by blobule**
A while ago I posted about adding a feature to measure geometry dimensions (see issue #301).
Time has passed, openscad improved, and I still need this feature. So I re-implemented it for the current openscad version.

It adds a new function, probe(), which will analyse the geometry of its first children, set some variables about its bounding box, and then evaluate the remaining children with those variables available. The variables are:
bbempty : true if the geometry is empty
bbmin and bbmax : the minimum and maximum coordinates of the bounding box
bbsize and bbcenter : the size and center of the bounding box

For example, you can do this:
probe() {
    sphere(r=10);
    echo(bbsize);
}
and you shoud see the size (near 10x10x10) displayed. To get the geometry, you have to repeat it:
probe() {
   sphere();
   sphere();
}
So to center only in X the object, simply do this:
probe() {
   object();
   translate([-bbcenter[0],0,0]) object();
}
You can impose fast computation using $exact=false, which will turn off CGAL. In all cases, it must be understood that this function has a computational cost. This is why I call it probe(), to suggest it will do some work, rather than bounds(), for example.

To display the bounding of an object, you can do this:
module see_bbox() {
    probe()  {
        children();
        if( !bbempty ) {
            %translate(bbcenter) cube(bbsize,center=true);
            children(); // display the geometry itself
        }
    }
}

If used sparingly, this function can help do things that are impossible right now because they require to estimate dimensions on complex geometry, which can be mathematically intractable.

Here are a few example of what you can do easily using probe(). It can align objects bounding boxes in many different ways. It makes attaching objects together very easy also.
probe_bbox

It makes "probing" objects possibile: you can intersect with a "probe" and obtain specific measures that can be used to place other objects. For example:

piston

Also, you can do more complex things, like search for complex intersections that are very hard to compute in any other way. For example:
touch

Technically, the probe() function is located in control.cc. It evaluates the geometry just like render, and can process polyset as well as nef_polyhedron representations.

This is the first pull request I make... I have no idea if its going to work or if this is the proper procedure to submit for openscad. In any case, I truly enjoy openscad and I think it really needs that feature. I hope it can be useful.

I will post documentation, examples and tests on request.

### CODE REVIEW

**Comment by MatthiasWM** [comment]
I would lie to suggest some changes, making the call more usable and maybe a bit more obvious.

* I would change the name from `probe()` to `query()`
* given the huge number of possible queries that could be done for any geometry, I suggest you add parameters that declare the kind of query, for example `query(bounding_box, center) { cube(); }` calculates the bounding box and center, but not the rotation, or whatever else we can come up with
* I would avoid using hardcoded names for the variables. Use the parameters to give the variables a name: `query(bounding_box=myBBox, center=steves_cube_position) { ... }`. When called, `myBBox` would now contain the bounding box as an array of two vectors, and `steves_cube_position` would contain a single vector pointing to the center of the geometry
* lastly, I would change the scope: set the variable in the caller scope, not in the child scope. That way, you can query the bounding box of two geometries and do something by combining the results

 - Wonko

**Comment by MatthiasWM** [comment]
Here is my suggestion and implementation of a different syntax, based on you code:

https://github.com/openscad/openscad/issues/301#issuecomment-134706375

What do you think?

**Comment by blobule** [comment]
Hi,

These are good suggestions, in my opinion.
One thing however: i suggest not to break the local scoping. Since you
suggest to allow changing the variable that hold the results, its easy to
keep local scoping:

Query(bbox=mybbox1) {
    Geometry1();
    Query(bbox=mybbox2) {
     Geometry2();
     Use mybbox1 & mybbox2 in result geometry;
     }
}

Otherwise feel free to use my code. I feel that querying geometries is a
very important feature lacking from openscad.

Sincerely,
Sebastien roy

**Comment by runsun** [comment]
> Here are a few example ...

Nice. Looking forward to it. I've been working on a polyhedron lib for 2 years. If OpenSCAD can do what you show here, I would probably have saved my time for something else.

**Comment by deolhoney** [comment]
Hey,
I wanted to find a volume of objects in OpenSCAD.
can we find a volume of objects in a OpenSCAD?
If we can find a volume of a objects in a  OpenSCAD suggest me please how can we find a volume of a objects in a OpenSCAD.

**Comment by blobule** [comment]
Hi!

I've implemented volume computation in openscad, based on my original
probe() work.

Wee here for examples (near the end of the thread):

http://forum.openscad.org/Volume-and-Center-of-mass-td15421.html

If there is interest, I will submit a pull request, but last time I got
"checks failed"  and no help to figure whats going on.

In the mean time, if you use Linux maybe I can help you get my version
compiled to get volumes.


Cheers,

Sebastien

**Comment by deolhoney** [comment]
blobule <notifications@github.com>
3:58 AM (3 hours ago)
to openscad/opens., me, Comment
Hi!

I've implemented volume computation in openscad, based on my original
probe() work.

Wee here for examples (near the end of the thread):

http://forum.openscad.org/Volume-and-Center-of-mass-td15421.html

If there is interest, I will submit a pull request, but last time I got
"checks failed" and no help to figure whats going on.

In the mean time, if you use Linux maybe I can help you get my version
compiled to get volumes.

Yes I am using Linux(ubuntu 14.04).Please help me to how to find out a
volume.
3:58 AM (2 hours ago)

**Comment by deolhoney** [comment]
Hey!!!
I am using Linux operation system.
I can find a volume of an object in OpenSCAD.
How can I find a volume of an object in OpenSCAD suggested me Please.

**Comment by blobule** [comment]
Hi!

My fork of openscad is here:

https://github.com/blobule/openscad

If you can clone it and compile it, it will feature the probe() function
with bounding box, volume and center of mass.

Check out the readme file in the repository for info on how to compile.

If you manage to compile, tell me and I will send you some examples.
I will be working today to make the version up to date with the current
openscad. I am using version 2015-07-12.

As a first example, try this:

probe(volume-true) {
    sphere(10);
    echo(volume);
    sphere(10);
}

It shoud print something near 4188, but less than that because of the
facets...

Anyway,
Keep me posted.

If everything goes well on my side, I will have an updated version soon,
and I will make a pull request to incorporated probe() into openscad.

Cheers,

Sebastien

**Comment by blobule** [comment]
I forgot...
If you use my github blobule/openscad fork, use the branch "probe".

Sebastien

**Comment by deolhoney** [comment]
Hi!!
when I am putting writing a code which you send me in an OpenSCAD.
When I compile it with (f6) ,"I am facing an error"

"Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown module 'probe'. 
WARNING: Ignoring unknown variable 'volume'. 
ECHO: undef
Rendering Polygon Mesh using CGAL...
CGAL Cache hit: sphere($fn=0,$fa=12,$fs=2,r=10);group(); (1043904 bytes)
Geometries in cache: 2
Geometry cache size in bytes: 62072
CGAL Polyhedrons in cache: 1
CGAL cache size in bytes: 1043904
Total rendering time: 0 hours, 0 minutes, 0 seconds
   Top level object is a 3D object:
   Simple:        yes
   Vertices:      450
   Halfedges:    2524
   Edges:        1262
   Halffacets:   1628
   Facets:        814
   Volumes:         2
Rendering finished."


Sir please tell me why I got this error and how can I remove this error and the volume I got in this compiler was not correct.
please suggest me so that  what can I do so that I can get a correct answer.

I am using a latest version of an OpenSCAD also ("OpenSCAD version 2016.06.25")

**Comment by deolhoney** [comment]
Today, I am installing a probe function in openSCAD and probe function is working also in it but know I am facing an error 
probe volume=1
WARNING: Ignoring unknown variable 'volume'. 
WARNING: Ignoring unknown variable 'centroid'. 
ECHO: "volume=", undef, " centroid=", undef
WARNING: Ignoring unknown variable 'centroid'. 
Rendering Polygon Mesh using CGAL.

suggest me how can  compile my volume and centroid by ignoring this error.

**Comment by blobule** [comment]
Make sure you used branch probe of blobule/openscad : https://github.com/blobule/openscad/tree/probe
Also, make sure this code prints something:
```
probe(volume=true) {
    sphere(20);
    echo("volume is ",volume);
}
```
If this works but you get errors on your code, attach a sample .scad and I'll check it out.

**Comment by deolhoney** [comment]
The code you send me know working but know onward, I got  the other error.


Compiling design (CSG Tree generation)...
probe volume=1
Center of mass: decomposed into 1 convex parts
Center of mass: decomposition took 0.613158 s
ECHO: "volume is ", 32902.9
Rendering Polygon Mesh using CGAL...
WARNING: No top level geometry to render

**Comment by blobule** [comment]
What do you want to do with the volume computation?
Usually, we use the bounding box to align objects. The volume does not have very many obvious uses...

**Comment by deolhoney** [comment]
I have  to make a project that we have to find a volume of any object which is build in openscad in my tranning

**Comment by blobule** [comment]
I am sorry, but I can't help you here.
If you post some code or you explain **precisely** what you want to do, I can't help you.
Sorry.

**Comment by deolhoney** [comment]
Please, help me without your help I am unable to find a volume.
here I send you a code of a chair if we wanted tho find a volume of chair how can we find it.

"code of a chair"
x=20;

y=20;

z=2;

cube([x ,y, z], center = true);

translate([10, 0, 20 * sin(90)])

rotate([0, 90, 0]) translate ([10 ,0 ,-1]) cube([x, y, z], center = true);

for (i = [8, -8], j = [8, -8]){

translate([i, j, 10 * sin(270)])

cube([4, 4, 20], center = true);

}


how can we find a volume of this.

**Comment by blobule** [comment]
Please make sure you understand how module works. See here : https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/User-Defined_Functions_and_Modules#Modules

Put your geometry inside a module, like this:
module chair() {
    ... your chair geometry here ...
}
Then display it by calling the module like this:
chair();

When you want to know the volume, just do
probe() {
    chair();
    echo(volume);
}

You need a deeper understanding of openscad, and more practice. Modules are the key to using openscad efficiently.

**Comment by deolhoney** [comment]
Hiii!!!

A lot of Thnx for helping me to find a volume.

**Pull request closed without merging**
