### PR TITLE
Console messages now only use HTML to highlight errors/warnings.

### PR DESCRIPTION
**Pull request by thehans**
fix issue #3140

### CODE REVIEW

**Comment by t-paul** [comment]
Hmm, looks like `echo()` can still generate HTML.

**Comment by thehans** [comment]
@t-paul I can't get it to do so.  Can you post an example test case?

**Comment by t-paul** [comment]
Oh, maybe the system update failed. I'll recompile latest master and check again.

**Comment by t-paul** [comment]
Yes, false alarm, reason was that debian testing now ships CGAL5 which failed the build.

**Pull request merged**
