### PR TITLE
allow trailing commas for function call such as let()

### PR DESCRIPTION
**Pull request by leonplust**
Fix issue https://github.com/openscad/openscad/issues/2882. 

For this PR I got very important help from t-paul, I was working toward a wrong direction before. 

Besides allowing trailing comma, considering his advice, I changed arguments to argument_list making the difference is more noticeable. I personally found it hard to notice when I first started working on it. 

Also, because definition_arguments is being used in other files, I am not sure if I should change all of them to keep consistency so I had it remain the same for now. 

I am not sure if I should open another PR for this or not. Please let me know if any change is needed.

### CODE REVIEW

**Comment by leonplust** [comment]
Since it's originally requested for let(), I created a test case based on let-module-tests, adding trailing comma for all let(). Is this good for the test case?

**Comment by leonplust** [comment]
I have made some fixes and created a new test case for function calls. The previous test case has been renamed to trailing-comma-module-test.

**Comment by leonplust** [comment]
I have removed those duplicate test and added the test case to the individual test

**Comment by t-paul** [comment]
Superseded by #3814.

**Pull request closed without merging**
