### PR TITLE
Throttle progress bar updates to 5 per second

### PR DESCRIPTION
**Pull request by thehans**
Addresses Issue #2636

### CODE REVIEW

**Comment by t-paul** [comment]
Did you measure this really helps? From my tests so far, the issue seems to be more that there are too many events created, so it would be more effective to have `progress_report_prep()` only tag nodes where it is useful to fire the callback.

**Comment by t-paul** [comment]
Ahh, found the note in #2636. That's quite some difference.

**Comment by thehans** [comment]
Yes I ended up putting the throttle around the contents of `report_func` since you noted that commenting out that function gave a speedup.

**Comment by t-paul** [comment]
Ahh, I see. With that big difference, it's certainly nice to have.

**Comment by thehans** [comment]
OK, changed :)

**Pull request merged**
