### PR TITLE
Add "Export to Clipboard" to copy the current 3d view to the system clipboard.

### PR DESCRIPTION
**Pull request by t-paul**
Tested only on Linux so far (Copy to LibreOffice Writer works).

TODO:
- [x] test on Mac OS
- [x] test on Windows

### CODE REVIEW

**Comment by kintel** [comment]
Tested on OS X - export to clipboard and paste to imgur.com works!
Some comments:
* Perhaps this belongs in some other menu, with a convenient shortcut?
* Are there any other tools doing similar things?

**Comment by MichaelAtOz** [comment]
'Copy Viewport' in Edit menu? With Ctrl-Shift-C (as a modifier of std copy shortcut)?

**Comment by t-paul** [comment]
Sounds good to me, patch updated. Tested on Windows, copy&paste into Write document works.

**Comment by t-paul** [comment]
Windows snapshots (2015-05-16) are updated based on current master + this patch.

**Comment by MichaelAtOz** [comment]
Works nicely, W7/64, paste to Word, paste to Infranview (save as .jpg).

Anything else from Master need testing?

**Comment by t-paul** [comment]
Master has currently only some additional fixes, most notably @kintel fixed #1325.

Otherwise, I'm uploading a special preview version for #1110 to toy with the proposed `trace()` module which is not yet in master (as `OpenSCAD-2015.05.17-x86-{32,64}_potrace.zip`, feature needs to be enabled in preferences).

**Pull request merged**
