### PR TITLE
Export WRL

### PR DESCRIPTION
**Pull request by podsvirov**
[VRML](https://en.wikipedia.org/wiki/VRML) - Virtual Reality Modeling Language (aka world - *.wrl)

There uses a proven algorithm designed to export to OFF format.

Example of use: exported geometry can be loaded into [FreeCAD](https://www.freecadweb.org/) or through the [Coin3D](https://github.com/coin3d) (OpenInventor) API ([C++](https://github.com/coin3d/coin)/[Python](https://github.com/coin3d/pivy)).

### CODE REVIEW

**Comment by t-paul** [comment]
Nice! I've did some testing and it works nicely with FreeCAD. It does not load in KiCAD.

Looking at the files coming with KiCAD, it seems it likes actual v2.0 files. Manual modification of an exported file (and using a material from KiCAD) gave me:
```
#VRML V2.0 utf8

Shape {
    appearance Appearance {material DEF PLASTIC-YELLOW-01 Material {
        ambientIntensity 0.522
        diffuseColor 0.832 0.680 0.066
        specularColor 0.160 0.203 0.320
        emissiveColor 0.0 0.0 0.0
        shininess 0.25
        transparency 0.0
        }
    }
}

Shape { geometry IndexedFaceSet { creaseAngle 0.50 coordIndex [
0,1,2,3,-1,
4,5,6,7,-1,
7,6,1,0,-1,
6,5,2,1,-1,
5,4,3,2,-1,
4,7,0,3,-1
] coord Coordinate { point [
0 0 10,
10 0 10,
10 10 10,
0 10 10,
0 10 0,
10 10 0,
10 0 0,
0 0 0
] } } appearance Appearance{material USE PLASTIC-YELLOW-01} }
```
Do you think it would be ok to use that to cover more apps? Would that work with Coin3D?

**Comment by podsvirov** [comment]
@t-paul, thanks for file sample. I have been update `export_wrl` function. It's also work with `Coin3D`/`FreeCAD` for me. Please review again.

**Comment by t-paul** [comment]
KiCAD seems to be a bit more picky about what to import. Unfortunately I can't see any way to get some sort of error message or indication what the issue is, it's just leaving the 3d preview view black.

I can successfully import if the file has the `creaseAngle` property and a material setting. I've imported the OpenSCAD VRML into MeshLab and exported again. This added an embedded material node, so I've tried to modify that to match the default OpenSCAD yellow colors and the final file imports fine in both MeshLab and KiCAD showing the object in yellow:

```
#VRML V2.0 utf8

Shape {

geometry IndexedFaceSet {

creaseAngle .5

coord Coordinate { point [
0 0 1,
1 0 1,
1 1 1,
0 1 1,
0 1 0,
1 1 0,
1 0 0,
0 0 0
] }

coordIndex [
0,1,2,3,-1,
4,5,6,7,-1,
7,6,1,0,-1,
6,5,2,1,-1,
5,4,3,2,-1,
4,7,0,3,-1
]

}

appearance Appearance { material Material {
ambientIntensity 0.3
diffuseColor .97647 .843137 .172549
specularColor .2 .2 .2
shininess .3
} }

}
```
I hope adding those `creaseAngle` and `appearence` nodes does not break other cases.

**Comment by podsvirov** [comment]
@t-paul, applied. Please review again.

**Comment by t-paul** [comment]
Awesome, KiCAD is finally happy importing a scaled down version of the `LetterBlock` example.
kicad-screenshot

With the current limitations regarding coloring that might not be the most important case right now, but being able to transfer designs into KiCAD now at all is great.

**Review by t-paul — APPROVED** [review]
Thanks! The attention to details is nice to see, keeping the export unified, taking care of icons and command line options. If you don't have any tests with other applications open, I'll merge once the CI-builds go green.

**Comment by podsvirov** [comment]
@t-paul, have a good weekend. Looking forward to the next release :-)

**Comment by t-paul** [comment]
Thanks, you too. Release will likely take a while, but the nightly builds with the export included will automatically show up on the download page latest tomorrow.

**Pull request merged**
