### PR TITLE
 warn on the use of unknown $variables, closing #2468

### PR DESCRIPTION
**Pull request by MichaelPFrey**
- [x] wait for #2535 beeing merged to master
- [x] wait for #2543 beeing merged to master
- [x] wait for #2520 beeing merged to master
(this is a low priority change in my opinion - this also gives people time to prepare for the change)
- [x] merge master with this branch
- [x] update test cases
- [x] remove do not merge label

### CODE REVIEW

**Comment by nophead** [comment]
Looks like I might have been relying on this bug. I thought that comparing a variable with undef not giving a warning was deliberate but it might just have been this bug.

It seems reasonable that you should be able to compare against undef to guard against using an undefined variable without the test triggering an undefined variable use warning.

**Comment by MichaelPFrey** [comment]
Hhmmm... in the moment of the variable lookup we can not know that it is for an undef comparison.

I would suggest a separate "isUndef()" methode/function for just that.

Note that c++ has an isnan() function [1](https://en.cppreference.com/w/cpp/numeric/math/isnan) because of how strange Nan compares [2](https://en.wikipedia.org/wiki/NaN#Comparison_with_NaN). So going for a function for a special variable state is not unrepresented.

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out. I thought repeated identical warnings where supposed to be suppressed?

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out. I thought repeated identical warnings where supposed to be suppressed?

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out. I thought repeated identical warnings where supposed to be suppressed?

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out. I thought repeated identical warnings where supposed to be suppressed?

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out. I thought repeated identical warnings where supposed to be suppressed?

**Comment by nophead** [comment]
Can I suggest isUndef is added before this is merged as I can't live with half a million warnings in all my projects. It takes a long time to spit them out! I thought repeated identical warnings were supposed to be suppressed?

**Pull request merged**
