### PR TITLE
debug GUI indicator, lexter line numbers, lexter column numbers

### LINKED ISSUE #4210: the parser does not count new line in context of use and include
Example:
```
use

<12>

assert(false);
```
Note that the assert is on line 5, but the error is reported for line 3:
```
Parsing design (AST generation)...
Saved backup file: /home/michael/snap/openscad-nightly/3300/.local/share/OpenSCAD/backups/unsaved-backup-NqXAMFfz.scad
WARNING: Can't open library '12'.
Compiling design (CSG Tree generation)...
[ERROR: Assertion 'false' failed in file , line 3](https://github.com/openscad/openscad/issues/3,/home/michael)
[TRACE: called by 'assert' in file , line 3](https://github.com/openscad/openscad/issues/3,/home/michael)
Compiling design (CSG Products generation)...
```

Screenshot from 2022-04-09 22-32-34

I am already working on a fix, but I want to have an issue here to collect and document examples.

### PR DESCRIPTION
**Pull request by MichaelPFrey**
fixes #4210, adds regression test for #4210

note: this could interact with #4209, so after merging either, the other merge requests tests should be rerun.

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
```
use

<12>

assert(false);
```
nightly build above, this merge request below:
Screenshot from 2022-04-10 09-15-30

**Comment by MichaelPFrey** [comment]
the linenumbers test open in nightly and this merge request:

Screenshot from 2022-04-10 09-22-10

**Comment by MichaelPFrey** [comment]
Here the original issue I was working on:
```
use<test>
use <hello>
use <1
2>
use <3
4>
use

<34>

include<test>
include <hello>
include  <1
2>
include <3
4>

include
<34>
```
nightly build left, this merge request right. Folder below.
Screenshot from 2022-04-10 09-04-30

The folder is relevant, as includes only get indicated, when the file exists.

Focus on the underlines below the paths. The syntax highlighting is different due to the nightly build not yet having #4205.

The issue being fixed is difficult to illustrate, but the example in the previous comments and the test case should be indicative that had an issue with line numbers and that the indicator/link feature is based on column and line numbers should be obvious.

**Comment by MichaelPFrey** [comment]
show case that the column counting works: Nightly above, this merge request below:
```
use<test> use <hello> use <2> use <4> use <34>

include<test> include <hello> include  <2> include <4> include<34>
```
Screenshot from 2022-04-10 12-33-50
```
use<test> use <hello> use <2> use <4> use <34>
use <
1
2
2
>
include<test> include <hello> include  <2> include <4> include<34>


```
Screenshot from 2022-04-10 12-36-13

**Review by t-paul — APPROVED** [review]
Nice!

**Pull request merged**
