### PR TITLE
Fix resource folder lookup (fixes #5394).

### LINKED ISSUE #5394: Previewing complains about missing shader files
**Describe the bug**
I press F5 to preview; this issue seems independent of what source I'm using. I get the following ERRORs in my console:

```
Saved backup file: /home/dank/.local/share/OpenSCAD/backups/unsaved-backup-uNircUCo.scad
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
Geometries in cache: 1
Geometry cache size in bytes: 848
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
ERROR: Cannot open shader source file: 'Preview.vert'   <----
ERROR: Cannot open shader source file: 'Preview.frag'   <----
ERROR: Cannot open shader source file: 'Preview.vert'   <----
ERROR: Cannot open shader source file: 'Preview.frag'   <----
Compile and preview finished.
Total rendering time: 0:00:00.035
```

**To Reproduce**
1. Install OpenSCAD from current sources.
2. Preview a valid SCAD file.

**Expected behavior**
I don't expect to see these errors. I'm presumably also not seeing the intended effects.

**Code reproducing the issue**
Any valid SCAD will reproduce.

**Screenshots**
I think the provided output probably suffices for now.

**Environment and Version info (please complete the following information):**
 - OS: Debian Unstable
 - System: AMD64 + 2080Ti
 - OpenSCAD Version 2024.10.24 with Manifold enabled, installed from source

**Library & Graphics card information**
If applicable, add the content of the Help->Library Info window, or the output of running the `openscad --info` command.
```
[schwarzgerat](0) $ openscad --info
Could not initialize localization.
QObject::startTimer: Timers can only be used with threads started with QThread
OpenSCAD Version: 2024.10.24
System information: Linux 6.11.4nlb2 #116 SMP Thu Oct 17 19:23:44 EDT 2024 x86_64 Debian GNU/Linux trixie/sid 64 CPUs 251.57 GB RAM
User Agent: OpenSCAD/2024.10.24 (Linux x86_64; Debian GNU/Linux trixie/sid)
Compiler: GCC "14.2.0" 64bit
MinGW build: No
Debug build: No
Boost version: 1_83
Eigen version: 3.4.0
CGAL version, kernels: 6.0.1, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.5.0
Qt version: 5.15.13
QScintilla version: 2.14.1
InputDrivers: 
GLib version: 2.82.2
lodepng version: 20230410
libzip version: 1.11.1
fontconfig version: 2.15.0
freetype version: 2.13.3
harfbuzz version: 10.0.1
cairo version: 1.18.2
lib3mf version: 1.8.1
Application Path: /home/dank
Documents Path: /home/dank/.local/share
User Documents Path: /home/dank
Resource Path: /home/dank
User Library Path: /home/dank/.local/share/OpenSCAD/libraries
User Config Path: /home/dank/.config/OpenSCAD
Backup Path: /home/dank/.local/share/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  /home/dank/.local/share/OpenSCAD/libraries
  /home/dank

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  /home/dank/.local/share/fonts
  /usr/local/share/fonts
  /usr/share/fonts
  /home/dank/.fonts
  /home/dank/.Fontmatrix/Activated
  /usr/share/texmf/fonts/opentype/public/lm
  /usr/share/texmf/fonts/opentype/public/lm-math
  /usr/share/texmf/fonts/opentype/public/tex-gyre-math
  /usr/share/texmf/fonts/opentype/public/tex-gyre
  /usr/share/fonts/X11
  /usr/share/fonts/cMap
  /usr/share/fonts/cmap
  /usr/share/fonts/eot
  /usr/share/fonts/fonts-go
  /usr/share/fonts/opentype
  /usr/share/fonts/pc
  /usr/share/fonts/svg
  /usr/share/fonts/truetype
  /usr/share/fonts/type1
  /usr/share/fonts/woff
  /usr/share/fonts/xscreensaver
  /usr/share/fonts/X11/100dpi
  /usr/share/fonts/X11/Type1
  /usr/share/fonts/X11/encodings
  /usr/share/fonts/X11/misc
  /usr/share/fonts/X11/util
  /usr/share/fonts/cmap/adobe-cns1
  /usr/share/fonts/cmap/adobe-gb1
  /usr/share/fonts/cmap/adobe-japan1
  /usr/share/fonts/cmap/adobe-japan2
  /usr/share/fonts/cmap/adobe-korea1
  /usr/share/fonts/eot/font-awesome
  /usr/share/fonts/eot/fork-awesome
  /usr/share/fonts/opentype/3270
  /usr/share/fonts/opentype/alegreya-sans
  /usr/share/fonts/opentype/artemisia
  /usr/share/fonts/opentype/asana-math
  /usr/share/fonts/opentype/cabin
  /usr/share/fonts/opentype/cantarell
  /usr/share/fonts/opentype/comic-neue
  /usr/share/fonts/opentype/complutum
  /usr/share/fonts/opentype/courier-prime
  /usr/share/fonts/opentype/didot
  /usr/share/fonts/opentype/ebgaramond
  /usr/share/fonts/opentype/firacode
  /usr/share/fonts/opentype/font-awesome
  /usr/share/fonts/opentype/fonts-hosny-amiri
  /usr/share/fonts/opentype/freefont
  /usr/share/fonts/opentype/gentiumplus
  /usr/share/fonts/opentype/inter
  /usr/share/fonts/opentype/ipaexfont-gothic
  /usr/share/fonts/opentype/ipaexfont-mincho
  /usr/share/fonts/opentype/ipafont-gothic
  /usr/share/fonts/opentype/ipafont-mincho
  /usr/share/fonts/opentype/league-spartan
  /usr/share/fonts/opentype/linux-libertine
  /usr/share/fonts/opentype/lobster
  /usr/share/fonts/opentype/lobstertwo
  /usr/share/fonts/opentype/mathjax
  /usr/share/fonts/opentype/neohellenic
  /usr/share/fonts/opentype/noto
  /usr/share/fonts/opentype/olga
  /usr/share/fonts/opentype/porson
  /usr/share/fonts/opentype/roboto
  /usr/share/fonts/opentype/solomos
  /usr/share/fonts/opentype/stix
  /usr/share/fonts/opentype/stix-word
  /usr/share/fonts/opentype/tlwg
  /usr/share/fonts/opentype/unifont
  /usr/share/fonts/opentype/urw-base35
  /usr/share/fonts/svg/font-awesome
  /usr/share/fonts/svg/fork-awesome
  /usr/share/fonts/truetype/3270
  /usr/share/fonts/truetype/adf
  /usr/share/fonts/truetype/agave
  /usr/share/fonts/truetype/amiga
  /usr/share/fonts/truetype/ancient-scripts
  /usr/share/fonts/truetype/andika
  /usr/share/fonts/truetype/anonymous-pro
  /usr/share/fonts/truetype/arphic
  /usr/share/fonts/truetype/arphic-bkai00mp
  /usr/share/fonts/truetype/arphic-bsmi00lp
  /usr/share/fonts/truetype/arphic-gbsn00lp
  /usr/share/fonts/truetype/arphic-gkai00mp
  /usr/share/fonts/truetype/artemisia
  /usr/share/fonts/truetype/asana-math
  /usr/share/fonts/truetype/babelstone
  /usr/share/fonts/truetype/baekmuk
  /usr/share/fonts/truetype/baskerville
  /usr/share/fonts/truetype/cardo
  /usr/share/fonts/truetype/cascadia-code
  /usr/share/fonts/truetype/charis
  /usr/share/fonts/truetype/clear-sans
  /usr/share/fonts/truetype/cmu
  /usr/share/fonts/truetype/comfortaa
  /usr/share/fonts/truetype/complutum
  /usr/share/fonts/truetype/croscore
  /usr/share/fonts/truetype/crosextra
  /usr/share/fonts/truetype/culmus
  /usr/share/fonts/truetype/dejavu
  /usr/share/fonts/truetype/didot
  /usr/share/fonts/truetype/doulos
  /usr/share/fonts/truetype/droid
  /usr/share/fonts/truetype/ebgaramond
  /usr/share/fonts/truetype/elusive-icons
  /usr/share/fonts/truetype/firacode
  /usr/share/fonts/truetype/font-awesome
  /usr/share/fonts/truetype/fonts-atarismall
  /usr/share/fonts/truetype/fork-awesome
  /usr/share/fonts/truetype/freefont
  /usr/share/fonts/truetype/gentium
  /usr/share/fonts/truetype/gentium-basic
  /usr/share/fonts/truetype/gentiumplus
  /usr/share/fonts/truetype/gentiumplus-compact
  /usr/share/fonts/truetype/glyphicons
  /usr/share/fonts/truetype/hack
  /usr/share/fonts/truetype/humor-sans
  /usr/share/fonts/truetype/inconsolata
  /usr/share/fonts/truetype/jetbrains-mono
  /usr/share/fonts/truetype/jsmath
  /usr/share/fonts/truetype/junicode
  /usr/share/fonts/truetype/katex
  /usr/share/fonts/truetype/khmeros
  /usr/share/fonts/truetype/lato
  /usr/share/fonts/truetype/liberation
  /usr/share/fonts/truetype/liberation2
  /usr/share/fonts/truetype/libreoffice
  /usr/share/fonts/truetype/lyx
  /usr/share/fonts/truetype/monoid
  /usr/share/fonts/truetype/msttcorefonts
  /usr/share/fonts/truetype/nanum
  /usr/share/fonts/truetype/neohellenic
  /usr/share/fonts/truetype/noto
  /usr/share/fonts/truetype/olga
  /usr/share/fonts/truetype/open-sans
  /usr/share/fonts/truetype/openoffice
  /usr/share/fonts/truetype/osifont
  /usr/share/fonts/truetype/padauk
  /usr/share/fonts/truetype/paratype
  /usr/share/fonts/truetype/porson
  /usr/share/fonts/truetype/povray
  /usr/share/fonts/truetype/quicksand
  /usr/share/fonts/truetype/roboto
  /usr/share/fonts/truetype/sixtyfour
  /usr/share/fonts/truetype/solomos
  /usr/share/fonts/truetype/staypuft
  /usr/share/fonts/truetype/terminus
  /usr/share/fonts/truetype/ttf-bitstream-vera
  /usr/share/fonts/truetype/ttf-staypuft
  /usr/share/fonts/truetype/tuffy
  /usr/share/fonts/truetype/unfonts-core
  /usr/share/fonts/truetype/unfonts-extra
  /usr/share/fonts/truetype/unifont
  /usr/share/fonts/type1/gsfonts
  /usr/share/fonts/type1/texlive-fonts-recommended
  /usr/share/fonts/type1/urw-base35
  /usr/share/fonts/woff/ebgaramond
  /usr/share/fonts/woff/font-awesome
  /usr/share/fonts/woff/fork-awesome
  /usr/share/fonts/X11/encodings/large
  /usr/share/fonts/opentype/roboto/slab
  /usr/share/fonts/truetype/roboto/hinted
  /usr/share/fonts/truetype/roboto/slab
  /usr/share/fonts/truetype/roboto/unhinted
  /usr/share/fonts/truetype/roboto/unhinted/RobotoTTF


GL context creator: GLX (new)
GLX version: 1.4
PNG generator: lodepng

GLEW version: 2.2.0
OpenGL Version: 4.6.0 NVIDIA 545.23.06
GL Renderer: NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

[schwarzgerat](0) $ 
```

**Additional context**
I can look into this myself, but wanted to get the bug filed. Thanks for the great software!

### PR DESCRIPTION
**Pull request by t-paul**
Tests:
- [x] Linux application
- [x] AppImage
- [x] Windows
- [x] MacOS

### CODE REVIEW

**Comment by t-paul** [comment]
Tests look ok so far, @kintel can you have a look if it also works on macos?

**Comment by kintel** [comment]
> Tests look ok so far, @kintel can you have a look if it also works on macos?

A regular dev build works in cmd-line mode. I'm building a dev snapshot too and will test that to be on the safe side.

**Comment by kintel** [comment]
macOS ok

**Comment by t-paul** [comment]
Ok, lookup fix take two. Lets see if we still missed some case.

**Pull request merged**
