### PR TITLE
Handle unclosed start conditions. Fixes #1890

### LINKED ISSUE #1890: Critical error for unclosed block comment
TODO:
* [x] Make sure customizer doesn't crash
* [ ] Make the OpenSCAD output a parser error for unclosed `/*`
* [ ] Make the OpenSCAD output a parser error for unclosed `"`

When this code is previewed:
`/*`

OpenSCAD pops up this alert:
screenshot from 2016-12-11 19 38 40

The application no longer previews or renders after fixing the error and adding geometry.

Ideally this error would be notified through the console, and handled such that OpenSCAD would continue to function.

### PR DESCRIPTION
**Pull request by kintel**
TODO:

* [x] Add tests
* [x] Test with customizer

### CODE REVIEW

**Comment by amarjeetkapoor1** [comment]
It working for use and include but not for `"` and I even tested after replicating the code for `/* ` which was missing but it didn't worked for both cases.

Plus I also tried by changing the position of line in the given block.

Is it working on your system?

**Comment by kintel** [comment]
I did some light testing and it looked ok. If you find anything that doesn't work, please here so we can add it to test cases.

**Comment by amarjeetkapoor1** [comment]
Simple test case for which it didn't work:

Test Case 1:

`"`

Test Case 2:
`/*`

**Comment by amarjeetkapoor1** [comment]
I have made some changes and now it's working.

Earlier this was causing the problem and the unclosed comments and string were not getting detected.
`
src/lexer.l:222: multiple <<EOF>> rules for start condition cond_string
src/lexer.l:233: multiple <<EOF>> rules for start condition cond_lcomment
`
But still unable to get why was this message was getting displayed.

**Comment by kintel** [comment]
@amarjeetkapoor1 I've added test cases. Could you check that the customizer behaves correctly now, as described in #1890?

**Comment by amarjeetkapoor1** [comment]
Changes related to customizer have been made before this. To counter this problem. So, customizer was behaving correctly and is behaving correctly.

Just one more thing. Does it seems okay to have two error messages?

```
ERROR: Parser error in file "/home/amarjeet/mountPoint/projects/openscad/examples/Parametric/sign.scad", line 58: Unterminated string 
ERROR: Parser error in file "/home/amarjeet/mountPoint/projects/openscad/examples/Parametric/sign.scad", line 58: syntax error 
ERROR: Compilation failed! 
```

**Comment by kintel** [comment]
Regarding the two parser errors: That's suboptimal. I couldn't figure out how to suppress the generic "syntax" error. Any ideas?

**Comment by amarjeetkapoor1** [comment]
No idea at present.

**Pull request merged**
