### PR TITLE
fix customizer vectors highest precision bug

### PR DESCRIPTION
**Pull request by Sharma-Hrishabh**
I have tried to do a quick fix for #3243 
Two approaches came into my mind-
1) To look over the highest precision by dividing the value by 10.0 and keeping the count until the value becomes 0.0
2) Converting the value into the string and using string manipulation (I found this approach on the internet), while I was searching for some inbuilt C++ function to do the same.

As, toDouble() already truncates(roundoff) the doubles to 5 decimal places, so both the approaches will take nearly constant time.
I chose the second approach, as working with doubles/floats is always tricky.

### CODE REVIEW

**Comment by t-paul** [comment]
That seems to duplicate the behavior of `ParameterVirtualWidget::setPrecision()` which does that calculation in a different way.

I wonder if there's a way to use the double-conversion library. I've seen the library mentioned in #3092 has a way of getting the highest precision that can restore the same number, not sure if double-conversion allows that. That is supposed to get rid of those 3.0000000001 issues.

**Comment by Sharma-Hrishabh** [comment]
I tested the Ryu library, it is working fine, but still, I'm confused, why in converting back the obtained character array to double, it always pads with extra zeroes up to 6 decimal places, if required, that is not desirable. Actually, the paper and video mentioned that it would cut off as many digits as possible, but while converting back to the double again, it is rounding the result to 6th decimal place. I think I need to give some more time in understanding the paper.

Also, I got your point of repetition, of the same code. So, for time being, is it a good idea to modify setPrecision method to get the highest precision from the vector and then set the precision according to it, keeping the same approach?

**Comment by t-paul** [comment]
Ah, interesting. I need to watch that video again.

To keep this PR simple, lets just unify those 2 functions so we don't calculate twice with different strategies. It sounds like we do want to have some rounding to prevent that crazy high number of decimals case.

**Comment by Sharma-Hrishabh** [comment]
Yes, I agree. The current implementation supports the highest precision up to 7 decimal places and rounding off according to that. So, 3.00000004000001 truncates to 3.0000000 & 3.00000006000001 truncates to 3.0000001.
It doesn't cut automatically to the possible as many as digits. It is being hardcoded to look up to 7 decimal places and rounding off accordingly if the number of decimal digits are more than that.

**Comment by Sharma-Hrishabh** [comment]
I just read #3098 , extending the GUI for this would be a good idea.

**Comment by Sharma-Hrishabh** [comment]
Hey @t-paul , I think, rather than checking the highest Precision, it would be great to add a GUI box in the customizer itself to set the precision.

**Comment by t-paul** [comment]
Yes, I think we should have more options in the GUI, to give the user actual control. But this PR is still useful as it could apply for the hopefully soon to be released bugfix version.

**Pull request merged**
