### PR TITLE
Speed up OpenGL 3d mesh drawing significantly by batching whole polyheda

### PR DESCRIPTION
**Pull request by OskarLinde**

### CODE REVIEW

**Comment by manthrax** [comment]
Curious why this was closed? I have a complex mesh that renders at < 1 fps in OpenSCAD, and at 60 fps frame locked in a simple webgl app. Why is the preview renderer so slow? I'd like to help fix this if possible..

**Comment by t-paul** [comment]
Looks like it was automatically closed when the unstable branch was deleted. If there's no matching existing issue, feel free to create one. It's a big topic on the wishlist anyway: https://github.com/openscad/openscad/wiki/Project%3A-Improve-OpenGL-rendering

Slow preview can have other reasons too, check the FAQ entry "[Why is the preview so slow?](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_is_the_preview_so_slow.3F)"

Help would be much appreciated as this is likely not something that can be changed in a day or two...

**Comment by kintel** [comment]
See #1518 which is a newer pull request addressing this. Still needs more work - help would be appreciated.

**Comment by manthrax** [comment]
Thanks for the quick response.

Having read the threads you linked, I now understand why rendering is a bottleneck, namely that preview is performing CSG on the fly using screenspace techniques! I had no idea this was this case,

Improving on OpenCSGs renderer is a bit out of my ballpark.. I will keep an eye on this repo if i see anything I may be qualified to contribute on, but for now, let me just say, You've done amazing work on OpenSCAD, and it really is my favorite tool for parametric modelling!

Thanks!!

**Pull request closed without merging**
