### PR TITLE
Don't use PolySetBuilder for linear_extrude

### LINKED ISSUE #5046: Bypass PolySetBuilder for rotate- and linear extrude
PolySetBuilder can in some cases create a non-manifold objects for linear_extrude and rotate_extrude.
Example: rotate_extrude of a 2D object with a single vertex touching the Y axis.
With our new indexed PolySet class, and using the Manifold geometry backend, it _should_ be possible to make these objects proper manifolds and utilize them in CSG operations.

See also #3567

### PR DESCRIPTION
**Pull request by kintel**
This will make yield manifold meshes for corner cases of linear_extrude. This will allow us to process geometry which is currently failing.

Split out linear_extrude-related functions into a separate `linear_extrude.cc` file.

Partially fixes #5046

### CODE REVIEW

**Comment by kintel** [comment]
This example is not manifold in this PR, but is fine in master:
```
linear_extrude(height=3, scale=[0,1]) {
  translate([.49,0,0])square();
  translate([-.49,0,0])square();
}
```

**Comment by gsohler** [comment]
> linear_extrude(height=3, scale=[0,1]) {
>   translate([.49,0,0])square();
>   translate([-.49,0,0])square();
> }

I cant see an issue here  in my linextrude branch. maybe different settings ? i am using manifold feature here

image

**Comment by kintel** [comment]
Did you sync your branch to this one?

**Comment by gsohler** [comment]
> Did you sync your branch to this one?

nope, I synced to latest master and i don' t see the issue.
It' s little unusual to me to sync to something which is not merged
As I am quite confident, that your PR will merge, I'll either wait for that
.. or i can accept instructions, how to merge to a PR which is not merged ...

let me know

**Comment by kintel** [comment]
The mentioned issue is a bug I introduced in this PR, which I need to fix before merging.

**Pull request merged**
