### PR TITLE
Added Linux Virginia support for dependencies

### PR DESCRIPTION
**Pull request by atossell91**
Added a new case in the get-dependencies scripts to account for the new Linux Mint (Virginia).

It calls the same function as the previous Linux Mint case, but I figured a new case make sense for a new version of the OS.

#5265

### CODE REVIEW

**Review by t-paul — APPROVED** [review]
Thanks!

**Comment by t-paul** [comment]
I just saw that #5193 was still pending which does some more cleanup and also updates the Mint rule. It would be great if you could check if that also works for you on recent Mint.

**Comment by atossell91** [comment]
@t-paul I uninstalled all of the dependencies, and then reinstalled them with the script and built openscad. Everything went well, so #5193 should be good to go!

**Comment by t-paul** [comment]
Awesome, thanks! Sorry for the overlapping effort.

**Pull request closed without merging**
