### PR TITLE
Build standalone executable WASM node binary (+ fix regressions & check wasm builds in CI)

### PR DESCRIPTION
**Pull request by ochafik**
While *casually* reading the Emscripten manual (esp.  [emcc options](https://emscripten.org/docs/tools_reference/emcc.html) & [Emscripten Compiler Settings](https://emscripten.org/docs/tools_reference/settings_reference.html)), I stumbled across [-sNODERAWFS](https://emscripten.org/docs/tools_reference/settings_reference.html#noderawfs), which gives JS access to the filesystem.

So... this PR adds a new WASM build type, which you can [download from circleci's artefacts](https://app.circleci.com/pipelines/github/openscad/openscad/5163/workflows/f6ade9bc-44d1-4df8-9b61-a6d2a6d2e29a/jobs/19910/artifacts) or build with:

<details>
<summary>Show commands to checkout this branch</summary>

```bash
git remote add ochafik https://github.com/ochafik/openscad
git fetch ochafik
git checkout ochafik/node-build
```
</details>

```bash
./scripts/wasm-base-docker-run.sh \
  emcmake cmake -B build -DWASM_BUILD_TYPE=node -DCMAKE_BUILD_TYPE=Release -DEXPERIMENTAL=1

./scripts/wasm-base-docker-run.sh \
  cmake --build build -j2
```

Then run *quite normally* (apart from the fact it's a self-contained JS w/ WASM payload 🤯, and the usual limitations from [openscad/openscad-wasm](https://github.com/openscad/openscad-wasm)):

```bash
./build/openscad.js \
  --backend=manifold \
  examples/Basics/CSG-modules.scad \
  -o out.stl
```

TODOs:
- [ ] Fix [circleci build](https://app.circleci.com/pipelines/github/openscad/openscad)
- [ ] [Enable circleci in Github Checks](https://app.circleci.com/settings/organization/github/openscad/vcs)?
- [x] Fixed a couple of WASM regressions (stackLimit + program location) that caused https://github.com/openscad/openscad-playground/issues/60
- [x] Added a ccache-friendly build helper script
- [x] Ensure circleci is happy to build {web,node} ~~x {Debug,Release}~~
- [x] Test node binary in circleci
- [x] Test web binary in circleci w/ puppeteer

For bonus points / later:
- [ ] Find out what fontconfig needs not to crash when `text` is used
- [ ] Run the deno tests from https://github.com/openscad/openscad-wasm (not sure how yet)
- [ ] Test headless rendering (see https://github.com/openscad/openscad-wasm/issues/17)
- [ ] Test multithreading (Manifold + TBB)
- [ ] Unpause wasm build on https://github.com/openscad/openscad-ci + add node variant

cc/ @t-paul @DSchroer

### CODE REVIEW

**Comment by gsohler** [comment]
great step!
Does JS(node)  support named function parameters like SCAD language does ?
like
cube([2,  center=true)

**Comment by ochafik** [comment]
@gsohler yes anything that works in the [Web Playground](http://ochafik.com/openscad2) should work, except some know issues with text (fontconfig expects some specific files) and possibly other limitations.

**Comment by gsohler** [comment]
i could not find the openscad.js in your branch. is it ready for check in ?

**Comment by ochafik** [comment]
@gsohler we don't check in build artefacts, but you can download it (zipped) from [this circleci integration run result page](https://app.circleci.com/pipelines/github/openscad/openscad/5165/workflows/4fb6c926-fa8c-4a93-a74f-361a71ec7072/jobs/19919/artifacts) (see "All checks have passed" block above -> "Show all checks" -> "CircleCI branch build").

That zip contains openscad.js, which you can put anywhere (e.g. even in your PATH) to call as an executable if you have Node installed.

**Review by kintel — APPROVED** [review]

**Comment by kintel** [comment]
@ochafik It looks like the new tests are actually failing after merging this: 
https://app.circleci.com/pipelines/github/openscad/openscad/5791/workflows/3a5e3693-e87c-41db-9db9-18e388c11ed7/jobs/21716
https://app.circleci.com/pipelines/github/openscad/openscad/5791/workflows/3a5e3693-e87c-41db-9db9-18e388c11ed7/jobs/21717

**Pull request merged**
