### PR TITLE
Extrude and minor tweaks

### PR DESCRIPTION
**Pull request by mhermier**
Hi,
I would like to propose these some small changes set.
There are minor changes to offer some tools to simplify some printing code, and a big change that add a generalized extrude. The last one is based on rotate_extrude, but use a list of transformation matrix to describe the extrusion path. Since it is a general extrude, I think it really should be named 'extrude'.
It is not a perfect tool, and might generate some broken volumes. But I consider it an advanced command like 'polygon' or 'polyhedron' which can also generate bad volumes. So it should not be a big deal.

### CODE REVIEW

**Comment by t-paul** [comment]
Can you please provide some details/examples how this will be used in scripts, e.g. showing off some of the extended features?

**Comment by mhermier** [comment]
I'm looking why travis is failling (probably because I missed to make test) and I'll post here a script that show a few of the capabilities.

**Comment by mhermier** [comment]
A crude and uninteresting example, I'll try to do something more representative ASAP:

function rotate_matrix(angle = [0, 0, 0], translate = [0, 0, 0], scale = [1, 1]) =
(
  let (s_a = 1)
  let (s_b = scale[1])
  let (s_g = scale[0])
  let (cos_a = s_a * cos(angle[2]))
  let (sin_a = s_a * sin(angle[2]))
  let (cos_b = s_b * cos(angle[1]))
  let (sin_b = s_b * sin(angle[1]))
  let (cos_g = s_g * cos(angle[0]))
  let (sin_g = s_g * sin(angle[0]))

  [[ cos_a * cos_b, cos_a * sin_b * sin_g - sin_a * cos_g, cos_a * sin_b * cos_g + sin_a * sin_g, translate[0]],
   [ sin_a * cos_b, sin_a * sin_b * sin_g + cos_a * cos_g, cos_a * sin_b * cos_g - cos_a * sin_g, translate[0]],
   [ -sin_b,        cos_b * sin_g,                         cos_b * cos_g,                         translate[0]],
   [ 0,             0,                                     0,                                     1]]
);

angle = 270;

path = [ for (i = [0 : 5 : angle])
           rotate_matrix(angle = [90, 0, i], scale = [abs(cos(i)), abs(cos(i))]) ];
//echo (path);
extrude(path, convexity = 10, flip_faces = false, is_ring = false)
  translate([10.5, 0])
    difference() {
      circle(10);
      square(17, center = true);
    }

**Comment by mhermier** [comment]
For the simple usage you provide a 'path' as a vector of transform matrices. I would recommend having Z rotation axis to be unitary (at least not null), just in case we need to/can use it to compute flip_faces.
'is_ring' boolean make the extrude a ring by joining first and last element of the path.
'convexity' and 'flip_faces' are used to fix rendering. first has the usual meaning and the second fix orientation if the 2D object orientation is reversed.

Quite some eye candy examples:

function transform_matrix(angle = [0, 0, 0], translate = [0, 0, 0], scale = [1, 1]) =
(
  let (s_a = 1)
  let (s_b = scale[1])
  let (s_g = scale[0])
  let (cos_a = s_a * cos(angle[2]))
  let (sin_a = s_a * sin(angle[2]))
  let (cos_b = s_b * cos(angle[1]))
  let (sin_b = s_b * sin(angle[1]))
  let (cos_g = s_g * cos(angle[0]))
  let (sin_g = s_g * sin(angle[0]))

  [[ cos_a * cos_b, cos_a * sin_b * sin_g - sin_a * cos_g, cos_a * sin_b * cos_g + sin_a * sin_g, translate[0]],
   [ sin_a * cos_b, sin_a * sin_b * sin_g + cos_a * cos_g, cos_a * sin_b * cos_g - cos_a * sin_g, translate[1]],
   [ -sin_b,        cos_b * sin_g,                         cos_b * cos_g,                         translate[2]],
   [ 0,             0,                                     0,                                     1]]
);

module star(r_ext = 2, r_int = 1, branches = 5)
{
  steps = 2 * branches;
  polygon([for (i = [0 : steps - 1])
            let(angle = i * 360 / steps)
              [cos(angle), sin(angle)] * (i % 2 == 0 ? r_ext : r_int)]);
}

{
  $fn = 360 / 2;
  epsilon = 0.1;
  r = 3;
  h = 10;
  pitch = .75;
  path = [ for (angle = [-360 : 2 : ((h + pitch) * 360 / pitch)])
             transform_matrix(angle = [90, 0, angle],
                              translate = [r * cos(angle), r * sin(angle), angle * pitch / 360 ])];

  intersection()
  {
    union() {
      cylinder(h = h, r = r);
      extrude(path, convexity = ceil(h / pitch), flip_faces = true)
        polygon([[.5, 0], [0, .25], [-epsilon, .25], [-epsilon, -.25], [0, -.25]]);
    }
    cylinder(h = h, r = 2 * r);
  }
}

translate([0, 15, 2])
{
  path_step = 2;
  path_twists = 2;
  path = [for (angle = [0: path_step: 360 - path_step])
            transform_matrix(angle = [90, angle * path_twists, angle],
                             translate = [cos(angle), sin(angle), 0] * 5)];
  extrude(path, is_ring = true)
    rotate([0, 0, 90])
      star();
}

translate([0, -15, 0])
{
  path = [for (step = [10 : -1 : 0])
            let (angle = [0, 0, 2.5 * step])
            step % 2 == 0 ?
              transform_matrix(angle = angle, translate = [0, 0, step / 2]) :
              transform_matrix(angle = angle, translate = [0, 0, (step + 1.2) / 2], scale = [1.3, 1.3])
         ];
  extrude(path)
    star();
}

**Comment by mhermier** [comment]
I fixed testsuite locally, but I'm not really happy about one change. Will resubmit a rebased branch as soon as I have time to look again at that change.

**Comment by kintel** [comment]
Cleaning up some old PR which we, unfortunately, didn't give enough love to see through.

**Pull request closed without merging**
