### PR TITLE
Solves issue #2978 where the Background Modifier lost the x-ray

### PR DESCRIPTION
**Pull request by henwist**
function of objects in a difference clause.

### CODE REVIEW

**Comment by henwist** [comment]
I have spent 4-5 daýs to find this problem of the background modifier in a difference clause and finally found a solution. Git bisect revealed the first commit that have this problem and the last good:

> bad checkout 97cab4589bc995fdacc43383433040d3953b316b
good checkout 44a063275188b68b757fb9b0899168c081d217a0

  Unfortunately this PR fails at three tests regarding the background modifier

>   507 - opencsgtest_background-modifier (Failed)
        508 - opencsgtest_background-modifier2 (Failed)
        519 - opencsgtest_highlight-and-background-modifier (Failed)

This PR may reveal a bug - see ./testdata/scad/3D/features/background-modifier.scad and rotate the view and the red sphere will go havoc and rotate all over the place.

So the first object in a difference will rotate as expected with the main sphere, but the second object in the difference will go havoc (e.g the red sphere). I have seen this happen before in game development and that problem happened when the object wasn't translated to the center of the world before it was rotated.
Does somebody have an idea where to look in the code for this new problem of the red rotating sphere?

**Comment by nophead** [comment]
I can't see anything wrong with the release version. Is it your change that has broken it?

image

**Comment by henwist** [comment]
I meant my version with this pull request applied on the latest master branch, breaks the rotation of the picture you added above. Then the red sphere will rotate around as the planets rotates around the sun. So I think this pull request introduce a hidden "bug" where a rotation is not performed as it should be, when '%' is added inside a difference() clause.

**Comment by nophead** [comment]
OK, I see what you mean now. 

image

It doesn't do it in the throwntogether mode, I don't know if that is a clue.

**Comment by nophead** [comment]
Also, not only does the sphere orbit, but it shouldn't be shown at all. I would expect % to have no visible effect at all and to just remove it from the F6 view because any colour overrides the transparent X-ray effect,

**Comment by nophead** [comment]
I got this in the command terminal

```
WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!! WARNING!!!
YOUR CODE IS RELYING ON DEPRECATED FUNCTIONALTIY IN THE JASPER LIBRARY.
THIS FUNCTIONALITY WILL BE REMOVED IN THE NEAR FUTURE.
PLEASE FIX THIS PROBLEM BEFORE YOUR CODE STOPS WORKING!
The specific problem is as follows:
negative buffer size for jas_stream_memopen
```

**Comment by t-paul** [comment]
Haha, wat? According to https://bugs.launchpad.net/inkscape/+bug/1747111 this could come from gdk-pixbuf2. I'm not aware of any direct dependency with that name.

**Comment by nophead** [comment]
This was @henwist,s PR build with MSYS2.

**Comment by t-paul** [comment]
Hmm, bug seems fixed for some time, maybe MSYS2 still has an older version... https://gitlab.gnome.org/GNOME/gdk-pixbuf/issues/73

**Comment by henwist** [comment]
@nophead - funny though these code snippets below perform very different when press F5 (and rotate the view) and with this pull request applied onto the latest main branch:

---
> //snippet 1:
%translate([0,-9,0]) difference() {
color("green") cube([10,4,10], center=true);
color("red") translate([0,-2,0]) sphere(3);
}

---

with regard to (notice that just the % is moved into the difference()):

----

>//snippet 2:
 translate([0,-9,0]) difference() {
color("green") cube([10,4,10], center=true);
%color("red") translate([0,-2,0]) sphere(3);
}

----

snippet1 result:
snippet1

---

snippet2 result:
snippet2

**Comment by henwist** [comment]
Well i found why #2978 cannot draw correctly:
**EDIT: Closing this PR as the problem is not solved by this pull request. The sequence of object in a difference() clause matters namely. Commenting this in the original issue #2978 .**

**Comment by henwist** [comment]
Reopen this PR due to a new found solution that nails the problem down and finally solves the issue!

Two pictures are changed in the ctest to comply with changed code - thus maybe a discussion on  which pictures are correct for the scad test code.

Test code ./openscad/testdata/scad/3D/features/background-modifier2.scad:

--------

```
color("Blue"){
        translate([-30,-10,-10]) cube([70,50,2]);
        translate([40,-10,-10]) cube([2,50,30]);
        translate([-30,40,-10]) cube([70,2,30]);
}

translate([-20,0,0]) difference() {
    intersection() {
        sphere(10);
        cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}

%translate([-20,20,0]) difference() {
    intersection() {
        sphere(10);
        cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}

difference() {
    intersection() {
        sphere(10);
        cube(15, center=true);
    }
  %cylinder(h=20, r=5, center=true);
}

translate([20,0,0]) difference() {
    %intersection() {
        sphere(10);
        cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}

translate([0,20,0]) difference() {
    intersection() {
        %sphere(10);
        cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}

translate([20,20,0]) difference() {
    intersection() {
        sphere(10);
        %cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}
```
-----

**Current master branch, test 508 - opencsgtest_background-modifier2 expected pic:**
background-modifier2-expected

--------

**This PR branch, test 508 - opencsgtest_background-modifier2 expected pic:**
background-modifier2-expected

-------

**Current master branch, test 879 - throwntogethertest_background-modifier2 expected pic:**
background-modifier2-expected

------

**This PR branch, test 508 - throwntogethertest_background-modifier2 expected pic:**
background-modifier2-expected

-----

Note: it is just the lower right figure (dice) that is changed between the two versions per test picture.

**So - is this PR more correct regarding the resulting pictures than the master branch?**

**Comment by MichaelAtOz** [comment]
> So - is this PR more correct regarding the resulting pictures than the master branch?

Looks good to me.

**Comment by MichaelAtOz** [comment]
Note that the blue background causes `UI-WARNING: Object may not be a valid 2-manifold and may need repair!`.
Not the fault of this change, but probably easily fixed here.?
Change line 3 to `translate([40,-10,-10]) cube([2,52,30]);` fixes the singularity on the corner.

**Comment by henwist** [comment]
Sorry... wrong button on wrong mouse on wrong computer :-)

**Comment by henwist** [comment]
@MichaelAtOz - consider it done:-)- Thanks for the hint.

**Comment by t-paul** [comment]
No, rendering the subtracted cylinder in the following case is wrong.
```
translate([20,0,0]) difference() {
    %intersection() {
        sphere(10);
        cube(15, center=true);
    }
    cylinder(h=20, r=5, center=true);
}
```

**Comment by t-paul** [comment]
Hmm, actually following the definition from the documentation, including the warning, it would be correct and match the result of the F6 render.

**Pull request merged**
