### PR TITLE
Fix Russian translation

### PR DESCRIPTION
**Pull request by kromanenko**
Small fixes of two mistakes:
Fix view direction name.
Divide two sentences with a whitespace.

### CODE REVIEW

**Comment by kromanenko** [comment]
@prokoudine , please review this change.

**Comment by kintel** [comment]
@t-paul Can you spot why there's a `sed` error on CircleCI on this one?
```
Binary created: /root/workspace/mingw32.static.posix/OpenSCAD-2018.11.04.ci330-x86-32.zip
Installer created: /root/workspace/mingw32.static.posix/OpenSCAD-2018.11.04.ci330-x86-32-Installer.exe

Not building regression tests package
sed: -e expression #1, char 33: unknown option to `s'
Exited with code 1
```

**Comment by t-paul** [comment]
That's caused by CircleCI naming pull requests `pull/<number>` fixed by https://github.com/openscad/openscad/commit/a79a84ee00f14189ea2c8065e429e3b5b568c244.

**Comment by kintel** [comment]
Included in #2551

**Pull request closed without merging**
