### PR TITLE
more precise manifold construction

### PR DESCRIPTION
**Pull request by pca006132**
Simplified the code a bit, and avoids the mesh quantization.

### CODE REVIEW

**Comment by pca006132** [comment]
`cgalpng_issue1165` is actually quite weird, I think both outputs are valid from the point of view of manifold. If we do exact arithmetic without doing decimation, I think the output with a membrane is fine. But manifold may also remove the membrane, as we have some heuristics to remove that (which may or may not work).

And while getting this, I think there is a bug in our cache implementation: two `multimatrix` that differs by tiny amounts may be considered the same by the cache due to its rounding behavior. And for cases like `cgalpng_issue1165`, tiny differences may make the membrane appear or disappear, and this rounding for cache can make it confusing to the user. (they have to flush the cache to get a 'correct' result). I was thinking about changing the code to use doubleconversion, with the most precise string, but it is failing a lot of tests because the csg file is now different, so it is not included in this PR.

**Comment by kintel** [comment]
Issue 1165 was originally a tessellation issue; CGAL would output the top concave face as one large concave polygon, and our triangulator didn't handle the concavity properly. Removing tiny details < some epsilon is fine. Challenge is, of course, dealing with test differences across different geometry backends.

We should discuss the cache issue elsewhere. Not sure if this would be the ideal example to use for highlighting/testing that.

**Comment by pca006132** [comment]
for some reason this fails https://www.thingiverse.com/thing:1958354

need further investigation

**Comment by kintel** [comment]
As mentioned on IRC: A polyhedron where two triangles exactly touches also fails: https://github.com/openscad/openscad/blob/9d464b8c71c9f720cde62d468aac011cb57a134e/tests/data/scad/3D/misc/polyhedron-self-touch-face.scad

**Comment by kintel** [comment]
> for some reason this fails https://www.thingiverse.com/thing:1958354
> 
> need further investigation

The objects generated by that library are terrible:
Screenshot 2024-02-26 at 00 38 39

**Pull request closed without merging**
