### PR TITLE
Use default clipper cleaning distance

### PR DESCRIPTION
**Pull request by thehans**
To minimize negative effects of clipper's flawed cleaning algorithm.  If distance not specified, clipper uses 1.415 ~= sqrt(2), the length of one diagonal.  http://www.angusj.com/delphi/clipper/documentation/Docs/Units/ClipperLib/Functions/CleanPolygons.htm

Proposed improvement for Issue #999

### CODE REVIEW

**Comment by kintel** [comment]
I think it's worth trying this, but we should add some test cases that exercise this a bit. There are some examples in #999 that could be used as a starting point.

FYI: Failing testcases usually live in https://github.com/openscad/openscad/tree/master/testdata/scad/bugs and are added here: https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L1481

They are not run by default, but can be run using `ctest -C Bugs`. Once an issue is fixed, we tend to move the testcase to https://github.com/openscad/openscad/tree/master/testdata/scad/3D/issues and from then on leave it running as a normal regression test.

**Comment by thehans** [comment]
@kintel The failing test was added in PR #2197.

This PR has been updated to move the new test into passing `issues` folder, and has passed successfully. I think it should be all good to merge.

**Comment by kintel** [comment]
@thehans Has a conflict against master now..
I'll have a look at this; do some more extensive manual testing.

**Comment by kintel** [comment]
OK, I tested against all reported duplicates of this issue. Looks good - I think the current test case covers what we need to test.

-> if you fix the conflict we can merge this.

**Comment by thehans** [comment]
Ah, completely did not see the conflict.  After a brief complete mangling of this PR branch I think I have it back in order now.

**Pull request merged**
