### PR TITLE
Add Option to Invert Mouse Buttons on 3DView

### LINKED ISSUE #3981: Add preference option to swap left and right mouse buttons.
Many other applications that I use, usually user the left-mouse-button for translation and the right-mouse-button for rotation. 
Can a swap option (checkbox) be added to the Preferences?
Thank you.

### PR DESCRIPTION
**Pull request by osfesa**
Please, let me know if you are not happy with the change.

Fixes  #3981.

### CODE REVIEW

**Comment by MichaelPFrey** [comment]
I am unsure about the name. I personally would call this "Swap Mouse Buttons".
When I read "Invert Mouse Buttons" I think inverting of pressed/released.
But am not a native English speaker, so feel free show me a reference.

Microsoft uses _swap_ and _switch_. [1](https://support.microsoft.com/en-us/windows/change-mouse-settings-e81356a4-0e74-fe38-7d01-9d79fbf8712bl)
Others call it right and left handed mouse. (but this is not the point here)
"remap" is also used sometimes for such a feature, but that would be to broad.
Reverse Mouse button is also sometimes used.

Other thoughts on the name?

**Comment by t-paul** [comment]
I'm bringing more votes for "Swap Mouse Buttons" :smile:.

Otherwise the change looks good.

**Comment by osfesa** [comment]
I like "Swap mouse buttons" too. I'll submit the new name soon.

**Review by t-paul — APPROVED** [review]
:tada:

**Pull request merged**
